### ISSUE TITLE
Update jscs-bem version

### ISSUE THREAD

**Issue by sipayRT** [bem/bem-core#1009]

**Comment by qfox** [comment]
@sipayRT Есть смысл сам jscs-bem обновить, кстати. Там много чего сделано в jscs@1.13.1 и jscs-jsdoc@1.0.0 ;-) В т.ч., можно правила код стайла уточнить.

**Comment by sipayRT** [comment]
@zxqfox потом еще раз апну версию - не проблема :)

**Comment by sipayRT** [comment]
@zxqfox хотя, можно и посмотреть на изменения.

**Comment by tadatuta** [comment]
Please refer https://github.com/bem/bem-core/commit/37fb01bce722792cf8e11ac325ae5b28376cc00b as a part of https://github.com/bem/bem-core/pull/1059

**Comment by sipayRT** [comment]
Close because of #1059
