### ISSUE TITLE
identify: Get rid of onlyGet argument

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#1028]
As we don't use `onlyGet` argument anywhere, we can remake the API of the module to works like this `identify(...args)`. 

This will be help us to reduce copy-paste like `var fnId = identify(fn) + (fnCtx? identify(fnCtx) : '')`

**Comment by aristov** [comment]
`onlyGet` [is used](https://github.com/bem/bem-core/blob/v3/common.blocks/i-bem-dom/i-bem-dom.js#L636) in `i-bem-dom` before #977 changes. Are you sure that it'll not be needed later?

**Comment by narqo** [comment]
Yes, we are. It was introduced mainly for the part you have found. As we don't do manual DOM traversing in our new event-system it can be dropped safely.

**Comment by narqo** [comment]
Landed with #1035
