### ISSUE TITLE
i-bem__dom: dropElemCache is broken?

### ISSUE THREAD

**Issue by qfox** [bem/bem-core#1037]
Looks like it's broken, because it uses `names + buildModPostfix(modName, modVal)` instead of `this.__self.buildClass(name, modName, modVal)` that contains `blockName`.

/cc @Yeti-or

**Comment by qfox** [comment]
Wow, dat fight between @levonet and @tavriaforever.

**Comment by aristov** [comment]
Mad robots...

**Comment by dfilatov** [comment]
I can't wait until robots start writing code

**Comment by dfilatov** [comment]
@zxqfox I don't understand why cache key should contain blockName.

**Comment by qfox** [comment]
@dfilatov same here, but for now it looks like a bug.

**Comment by dfilatov** [comment]
@zxqfox Sorry, I can't make head or tail of what you have written. Could you explain?

**Comment by dfilatov** [comment]
ping

**Comment by qfox** [comment]
@dfilatov текущий dropElemCache работает только без параметров, потому что elem кеширует с названием блока, а первый удаляет без. Зачем там название блока — не знаю, в PR наименьшее кол-во измененного кода, по-хорошему, нужны тесты.

**Comment by Yeti-or** [comment]
@dfilatov мы разбирали пр в bem-bl и выяснилось что dropElemCache не работает: https://github.com/bem/bem-bl/pull/634

**Comment by dfilatov** [comment]
oк, теперь я понял

**Comment by narqo** [comment]
Fixed with #1042
