### ISSUE TITLE
i-bem: Add deprecation notes to things that will be changed or removed in 4.0

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#1047]
We already have made some notable changes in v4 and the actual list of changes is not completed yet. 

This is a meta issue, to not to forget to add deprecation notes to the v2 branch, when the the final scope of the 4.0 will be ready.

Note "v2" label and "4.0" milestone here, shows that the actual work would be done in v2 and it blocks 4.0.

**Comment by veged** [comment]
changes are too big, we can't provide any possibility of simultaneous usage of both API versions (so one of them can be warned as deprecated)
