### ISSUE TITLE
next-tick: use `MutationObserver` if possible

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-core#1055]

**Comment by narqo** [comment]
According to [this research](https://github.com/YuzuJS/setImmediate#macrotasks-and-microtasks) there is some difference in a way how `MutationObserver` works, comparing to other ways to emulate `next-tick`. Are you sure it can be used?

To be honest, I can't said, I completely understand the difference. So just asking ;)

**Comment by dfilatov** [comment]
I've checked some popular libraries such as Bluebird, rsvp and figured out they use `MutationObserver` first of all.
And I've made my own simple tests which proved that using `MutationObserver` was much "faster" than `postMessage`.

**Comment by dfilatov** [comment]
@narqo I think it fits to our purposes.

**Comment by dfilatov** [comment]
I've realized the difference (different behaviour with eventloop). So you're right we need to think careful of its usage within this module.
