### ISSUE TITLE
jquery__events_type_pointernative: pointerdown event works incorrectly in IE Edge

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#1066]
Looks like our pointerevents polyfill works badly in the upcoming IE Edge. At least blocks `select` and `dropdown` from bem-components 2.1.x are closing immediately after the user clicks on their `button`.

Here are the suggestions from Microsoft Edge Team, sent to the front-end team of "_[project with bem-components]_":

> [..] When a user clicks on the drop down list _[e.g. block `select`]_, this issue occurs because there are two sets of events that fire for the down event, which then triggers listeners for up events. In one case, there is a check for msPointerEnabled which listens for the MS prefixed pointer, or fallback to mouse. In another case, there is a check for non-prefixed pointerdown. In previous versions of Internet Explorer when the prefixed msPointer was enabled, this listened to pointerdown twice, which internally resolved to the same event and only fired once. Now in Windows 10, with prefixed mspointer disabled, [_the project with bem-component_] listens to mousedown and pointerdown, which triggers the events twice, so the drop downs are double toggled.
> 
> Here is the logic that listens to either mspointer events or mouse:
> T.msPointerEnabled ? v.registerSource("ms", I) : (v.registerSource("mouse", E), "undefined" != typeof e.ontouchstart && v.registerSource("touch", x)), v.register(a);
> 
> This triggers their own generated pointerdown events which trigger the pointerpress events. It is recommended for [_the project with bem-component_] to add a check for non-prefixed pointerEnabled which listens to non-prefixed versions and this should still work with the duplicated listener since it will be the same event.

**Comment by arikon** [comment]
We are going to use PEP in `islands`: https://github.com/jquery/PEP
