### ISSUE TITLE
 querystring.parse некорректно обрабатывает строку с хэшем на конце

### ISSUE THREAD

**Issue by oberset** [bem/bem-core#1067]
qqq=1&aaa=2&param1=2#hash 

Вызов querystring.parse запишет #hash в значение param1

{
  qqq: "1",
  aaa: "2",
  param1: "2#hash"
}

Костыль для решения проблемы:

``` javascript
var data = querystring.parse(str);
if (typeof data === 'object') {
    var prop;

    for (var i in data) {
        if (data.hasOwnProperty(i)) {
            prop = i;
        }
    }

    if (prop) {
        var val = data[prop];

        if (prop.indexOf('#') !== -1) {
            var validProp = prop.split('#')[0];
            if (validProp) {
                delete data[prop];
                data[validProp] = val;
            }
        } else if (val.indexOf('#') !== -1) {
            data[prop] = data[prop].split('#')[0];
        }
    }
}
```

**Comment by narqo** [comment]
С точки зрения `querystring` поведение нормальное (qs в node.js работает так же). Посмотри модуль uri в [bem-history@v2](https://github.com/bem/bem-history/tree/v2/common.blocks/uri), кажется, он решает твои задачи

**Comment by qfox** [comment]
@narqo qs в nodejs очень примитивный, так-то.

@oberset кажется, что есть непонимание что такое querystring и что такое uri.

`/?<querystring>#foobar` — это uri, и с точки зрения `querystring` парсера `#` не является служебным символом, значит и не парсится. Либо надо руками отрезать (костыль), но лучше посмотреть откуда приезжает эта строка, потому что если это не часть значения параметра — её там не должно быть.

**Comment by narqo** [comment]
Все таки это стандартное поведение для всех языков: проверил `uri.ParseQuery()` в go, `urlparse.parse_qsl()` в python и даже `parse_str()` в php :) Для входной строки из описания, результат один и тот же.

Как уже написал @zxqfox:

> [..] если это не часть значения параметра — её (_символ `#`_) там не должно быть
