### ISSUE TITLE
page: CSP meta-tag support

### ISSUE THREAD

**Issue by arikon** [bem/bem-core#1070]
Proposing forward-porting of Content Security Policy (CSP) support from `bem-bl`'s `b-page` to the `page` block.

PR to `bem-bl`: https://github.com/bem/bem-bl/pull/650
PR to `islands`: https://nda.ya.ru/3QnPqJ

**Comment by Guria** [comment]
CSP support was added in #882 
bem/bem-bl#650 seems about csp meta-tag

**Comment by arikon** [comment]
@Guria Yes, it is about meta-tag with Content Security Policy

**Comment by narqo** [comment]
@arikon is it true, that these things from bem/bem-bl#650 are made just to set proper **defaults** for CSP policies, which are needed _mostly_ for Yandex services? If not, why not to just ask users to add proper `meta` tag with `{ elem : 'meta' }`?

**Comment by arikon** [comment]
@narqo It is a feature to set CSP more conventionally, not like single string as a value of attribute. We could also provide reasonable defaults (`self` for most policies etc).

**Comment by aristov** [comment]
Since we don't have an ability to specify any reasonable rich defaults for general open-source projects (like we do at Yandex), it looks that plain HTML meta tag is easier for usage instead of understating custom BEMJSON API.
Discussed with @veged and @narqo
