### ISSUE TITLE
Nested promises handling in bemtree is broken

### ISSUE THREAD

**Issue by apsavin** [bem/bem-core#1079]

**Comment by apsavin** [comment]
@veged, can somebody add tests?

**Comment by veged** [comment]
can you do it yourself?

**Comment by apsavin** [comment]
I can, but where should I add it? It seems that `i-bem.spec.js` isn't the right place.

**Comment by veged** [comment]
let's make it like https://github.com/bem/bem-core/tree/v2/common.blocks/i-bem/i-bem.test.bemhtml — `i-bem.test.bemtree`

**Comment by apsavin** [comment]
ok, I'll try.

**Comment by aristov** [comment]
Close in favour of #1107

**Comment by apsavin** [comment]
Hmm, I think, this issues are different.

**Comment by dfilatov** [comment]
Let's move all discussions about BEMTREE and BEMHTML to https://github.com/bem/bem-xjst/issues
