### ISSUE TITLE
jquery__events_type_pointerclick: Remove FastClick

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#1088]
Our `jquery__events_type_pointerclick` is based on [FastClick](https://github.com/ftlabs/fastclick) library which (unfortunaly) brings a lot of non-obvious problems to native behaviour on touch device. We definitely should think again and decide if we really needs it in the core.

See http://developer.telerik.com/featured/300-ms-click-delay-ios-8/ for potential ways to prevent 300ms click delay in **some** mobile browsers.

**Comment by veged** [comment]
now in iOS9 we have broken `radio-group` and `checkbox` because of FastClick — after discussion with @dfilatov and @narqo we think of removing FastClick

**Comment by veged** [comment]
finally decide to remove fastclick

**Comment by narqo** [comment]
N.B. Current iOS versions support `touch-action: manipulation` which seems to solve 300ms lag. We need to add this CSS rules to every controls in bem-components.

**Comment by veged** [comment]
need port to v4
