### ISSUE TITLE
BEMTREE: Support native promises

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#1095]
node.js and [most browsers](http://caniuse.com/#feat=promises) already have native support for promises.

**Comment by narqo** [comment]
One need to think about how such values will be serialized to BEMJSON, so _any_ promise implementation could be used, regardless of JS engine

**Comment by tadatuta** [comment]
When all promises are resolved we should map the whole queue of them to their results.

**Comment by veged** [comment]
seems like this issue is belong to [bem-xjst](https://github.com/bem/bem-xjst/)
