### ISSUE TITLE
Put `BEMContext` as field to the first arg of `oninit`

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#1099]
This issue is based on an answer from @indutny via email. It'll be implemented this way in `bem-xjst 2.0` and gives possibility to affect `BEMContext` within templates.

// cc @veged @narqo @arikon

**Comment by qfox** [comment]
Looks like a wise decision. :+1:

**Comment by arikon** [comment]
:+1: 

First arg is `exports`. And it is a better fit for `BEMContext`.

**Comment by veged** [comment]
:+1:

**Comment by tadatuta** [comment]
Давайте еще раз подумаем, а точно ли оно нужно? Еще не поздно откатить в Islands.

// cc @veged @narqo @indutny

**Comment by arikon** [comment]
Откатывать так же нужно будет в `bem-xjst@3.x`.

Вопрос в следующем: а правда ли кому-то может понадобиться доступ из шаблонов к `BEMContext` (не из `oninit()`)? Если да, то для каких целей?

**Comment by tadatuta** [comment]
обсудили, точно делаем

**Comment by narqo** [comment]
Решили закрыть в пользу #1258. В v2 уже делать ничего масштабного не будем.
