### ISSUE TITLE
Feedback for "Справочное руководство по BEMJSON"

### ISSUE THREAD

**Issue by a-x-** [bem/bem-core#1105]
There is inaccuracy.

> js    Либо флаг о наличии клиентского JavaScript у данной сущности, либо параметры JavaScript  Boolean

must be:
`Boolean|Object`

---

https://ru.bem.info/technology/bemjson/v2/bemjson/#Представление-html

**Comment by a-x-** [comment]
И ещё эта фидбечница не добавляет ссылки,
вам же так наверно не очень удобно?

**Comment by tadatuta** [comment]
Thank you!
