### ISSUE TITLE
Don't change api of BEMTREE in v3

### ISSUE THREAD

**Issue by apsavin** [bem/bem-core#1107]
Guys, we've changed api of BEMTREE in 3.0 because I wanted to handle errors. I think, we should restore it back before official publication of 3.0. 

Why? 
- it's always better to don't break
- consistency with BEMHTML

How?

We should implement some option like `strict: true`. It may be false by default.
1. It will allow ignore errors for people who want to do so.
2. It will allow to handle errors properly for those who want
3. It will allow to ignore errors in production environment

What do you think about this proposal? 
If you agree, can you suggest me the way how to implement such option?

**Comment by apsavin** [comment]
@veged ? @narqo ?

**Comment by narqo** [comment]
My opinion there's nothing wrong about fixing wrong decisions that were implemented centaurs ago. I don't understand what kind of consistency with BEMHTML you're talking about. 

I think promises gives you ability to make all kinds of decisions you've listed. You still can use `bemtree.apply().always(/* i don't give a fck about errors */)` don't you?

**Comment by apsavin** [comment]
> My opinion there's nothing wrong about fixing wrong decisions that were implemented

Exactly what I'm talking about.

Of course, users can now ignore errors or handle them.

I just don't like the way _how_ and I think we can change it before release.

The main thought is: "strict" option and `BEMTREE.apply().then(onF, onR)` is better then `BEMTREE.apply().spread(function(bemjson, promise){ return promise.done(function (){onF(bemjson);}, onR);})`.

**Comment by narqo** [comment]
Oh, now I see. I was absolutely sure that we already have such strict behaviour in `v3`. We need to drop this `spread` requirements from `v3`, and start using normal promises there. No additional options are needed.

**Comment by veged** [comment]
speaking about `v3` we can do such API changes — :+1: 

we just need to ensure about documentation in changelog

**Comment by dfilatov** [comment]
Let's move all discussions about BEMTREE and BEMHTML to https://github.com/bem/bem-xjst/issues
