### ISSUE TITLE
Block returned false on beforeSetMod->js->inited is considered inited anyway

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#1111]
``` js
{
    beforeSetMod: {
            js: {
                inited: function() {
                    if (this.domElem.is(':hidden')) {
                            return false;
                    }
                }
            }
        },
}
```

Manual `BEMDOM.init()`on same element after it's become visible can't init block.

For more details please refer to https://github.com/bem/bem-forum-content-ru/issues/528

// @h4

**Comment by h4** [comment]
Отличный id для issue, ящитаю ;)

**Comment by tadatuta** [comment]
We discussed the issue and decided that it'll make `i-bem__dom` too complicated and actually won't give possibility to solve original issue as we won't be able to address an instance until the block is inited (as so `this.domElem` will be undefined).
