### ISSUE TITLE
Optional ymodules block declaration

### ISSUE THREAD

**Issue by DimitryDushkin** [bem/bem-core#1112]
I think old BEM block declaration syntax was much clearer and less verbose.

For example, I need to use static method of one block into another. That will be:

``` js
// i-ga.js
modules.define(
    'i-ga',
    ['i-bem'],
    function(provide, BEM) {

    provide(BEM.decl(this.name, {}, {

        hit: function(propertyType, cardId) {
            console.log('Google Analytics hit ', propertyType, cardId);
        }

    }));

});
```
- 

``` js
// property.js
modules.define(
    'property',
    ['i-bem__dom', 'i-ga'],
    function(provide, BEM, GA) {

    provide(BEM.decl(this.name, {

        _onPhoneClick: function() {
            GA.hit(this.getMod('type'), this.params.id);
        }

    }));

});
```

+

``` js
// property.deps.js
({
    shouldDeps: { block: 'i-ga' }
})
```

It's 160 on unnecessary symbols (or 10 LOC) + 1 indent about ymodules declaration and require in 2 files.

I think it's unnecessary because:
— `BEM.decl` is already way to declare block. `modules.define` is duplication of block declaration;
— dependency on `i-ga` is already defined in `property.deps.js`. Using it in module declaration is duplication;
— because of `deps.js` block `property` already have `i-ga` block declaration in `BEM` object;
— in this example there is no benefit from using module system. I also think in 99% cases of declaring i-bem blocks there is no benefit from ymodules.

I think more straightforward and unobtrusive way will be:
— Get back or make optional old i-bem block declaration way without ymodules. Yes, with global variable `BEM`.
— OR have all `BEM.decl` in one big `ymodules.define(function() { ... });`;
— OR Get rid of deps.js in favor of module dependecies that we already have in `block.js` file.

Sorry for may be "holywar" mood of issue. I am not insisting on this changes and such. I just want more clear code with less duplication.)

**Comment by qfox** [comment]
Feels like https://github.com/bem/bem-core/issues/1109 should helps a lot with code cleaning.

**Comment by DimitryDushkin** [comment]
@zxqfox yes, that's great proposal, almost perfect.

**Comment by DimitryDushkin** [comment]
May be this issue can be closed in favor of https://github.com/bem/bem-core/issues/1109

**Comment by narqo** [comment]
> — BEM.decl is already way to declare block. modules.define is duplication of block declaration;

Regardless the topic itself, you really don't need to use `BEM.decl` in most cases now. The only thing that it was used for previously was to have (some sort of) class definition system, as well as a namespace.

With `ym` we don't have this namespace problems now, so your `i-ga` example should be rewritten like this:

``` js
modules.define('i-ga', function(provide) {
    provide({
        hit: function(propertyType, cardId) {
            console.log('Google Analytics hit ', propertyType, cardId);
        }
    });
});
```

You can use [`inherit` module](https://ru.bem.info/libs/bem-core/v2.7.0/desktop/inherit/docs/) (sorry about this link to russian docs, english version is still in progress ;) if you need to have classes/inheritance.

`ym` (as any module system) gives us opportunity to write and use any kind of utilities, without the need to put them into `i-bem.js` or `jquery` boxes, as we had to in "bem-bl times". So now `i-bem.js` is on it's way to become a pure view layer on top of the DOM with much clearer goals (IMHO).

I agree that the syntax of `ym` definitions looks quite verbose now, but please, keep in mind, that [bem-core 1.0 was release 2 years ago](https://github.com/bem/bem-core/blob/v1.0.0/CHANGELOG.md), and the only (semi-) asynchronous module system was AMD, which was not suitable for us, as we still do need async provide in some cases.

> — OR Get rid of deps.js in favor of module dependecies that we already have in block.js file.

If it's suitable for your project, you can use [deps-with-modules](https://github.com/enb-make/enb-modules#deps-with-modules) enb tech for that.

**Comment by narqo** [comment]
All for #1109

**Comment by DimitryDushkin** [comment]
@narqo thank you for such remarkable answer. I got all the answers.
