### ISSUE TITLE
Refact ENB config

### ISSUE THREAD

**Issue by blond** [bem/bem-core#1127]
We need to simplify the `.enb/make.js` file.

Part of the logic can be move by tasks:
- `.enb/tasks/dist`
- `.enb/tasks/specs`
- `.enb/tasks/tmpl-specs`
- `.enb/tasks/tests`
- `.enb/tasks/examples`
- `.enb/tasks/docs`

And also collect common code:
- `.enb/techs.js`
- `.enb/config.js`
- `.enb/helpers.js`

**Comment by tadatuta** [comment]
looks fine
