### ISSUE TITLE
Switch to min.{css,js} instead of leading underscore for built files

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#1128]
...to be more like others and get rid of `.nojekyll` on `gh-pages`

**Comment by blond** [comment]
What kind of files are we talking about? Bundles? Examples?

**Comment by tadatuta** [comment]
I'm about any occurrences of `_*.{css,js}`

**Comment by blond** [comment]
How about just  `?.css` and `?.js`?

```
.tmp.css
.tmp.js
index.css
index.js
```

In `enb-stylus@2.0` package you can use [compress](https://github.com/enb-make/enb-stylus/blob/master/api.ru.md#compress) option. And similar behavior we want to support in `enb-diverse-js`.

Then the result may be:

```
index.css
index.js
```

**Comment by tadatuta** [comment]
What about `borschik` step in this scheme?

**Comment by blond** [comment]
In this scheme there is no possibility to use `borschik` at least for styles. But we can use `PostCSS`.

What is the problem we need to solve with `borschik` for styles?
