### ISSUE TITLE
Use csswring to minify CSS

### ISSUE THREAD

**Issue by blond** [bem/bem-core#1130]
See https://github.com/hail2u/node-csswring

We use this plugin in [enb-stylus](https://github.com/enb-make/enb-stylus#Минимизация-css-кода) package and in `islands` library.

**Comment by tadatuta** [comment]
We visited a talk of @demiazz and he advertised for http://cssnano.co/

**Comment by blond** [comment]
`cssnano` has performance problems: http://goalsmashers.github.io/css-minification-benchmark/

Wherein compression quality better 5-10 percent.

**Comment by tadatuta** [comment]
Closing in favour of CSSO :)
