### ISSUE TITLE
dist: use `devMode: true` for `.dev.bemhtml.js`

### ISSUE THREAD

**Issue by blond** [bem/bem-core#1143]

**Comment by tadatuta** [comment]
I'm not sure it's a good idea — dev mode is too slow.

**Comment by blond** [comment]
@tadatuta Let's compare `BEMHTML.apply()` for blocks of `bem-core`? I think the big difference is not expected.

**Comment by tadatuta** [comment]
What is the reason to have templates in dev mode?

**Comment by blond** [comment]
for debug? =)

**Comment by tadatuta** [comment]
I think it's useless
