### ISSUE TITLE
Feedback for "События"

### ISSUE THREAD

**Issue by FA73F0X** [bem/bem-core#1149]
На движке WebKit не отображается стрелочка для прокрутки страницы вверх.

**Comment by tadatuta** [comment]
@FA73F0X Можно чуть больше подробностей? У меня на macOS 10.10.4 в Safari 8.0.7 (10600.7.12) стрелка на странице https://ru.bem.info/events/talksworks-spb-2015/ присутствует.

**Comment by FA73F0X** [comment]
@tadatuta Можно и подробнее) Правый нижний угол win10 chrome 44.0.2403.157 m например здесь https://ru.bem.info/method/filesystem/ 
![alt text](http://s017.radikal.ru/i411/1508/dc/9d1c04e384e4.png)

```
<div class="content__arrow-up content__arrow-up_visible">⬆</div>
```

**Comment by tadatuta** [comment]
@gela-d похоже, нужно найти символ поуниверсальнее либо просто перейти на svg

**Comment by FA73F0X** [comment]
@gela-d SVG надежнее )

**Comment by gela-d** [comment]
@FA73F0X @tadatuta спасибо! В ближайшее время выкатим нормальную стрелочку.

**Comment by gela-d** [comment]
Выкатили на bem.info новую стрелочку. @FA73F0X проверь, пожалуйста, все ли хорошо.

**Comment by FA73F0X** [comment]
@gela-d если Вам интересно мое мнение ) то я бы еще стили подправил. Например так:

```
.content__arrow-up {
    right: 20px;
    bottom: 7px;
    width: 20px;
    height: 20px;
}
```

**Comment by gela-d** [comment]
Интересно :)
Но, при этих стилях, стрелочка становится сильно меньше и начинает закрывать край текста в некоторых случаях
![2015-08-25_1805](https://cloud.githubusercontent.com/assets/1333220/9470307/0a30ef40-4b54-11e5-83f7-b58fce3f9bf2.png)

**Comment by FA73F0X** [comment]
@gela-d да тут два разных верстальщика сделают по разному, а если еще дизайнера позвать с тестировщиком появятся еще варианты оформления ) Я по размеру верхней иконки смотрел. 
![alt text](http://s019.radikal.ru/i621/1508/35/dbffa1874b37.png)
Да и первоначальная иконка не была большой(хотя она была менее заметна и к месту).

**Comment by gela-d** [comment]
@FA73F0X ты все правильно говоришь, за неимением дизайнера каждый бы сделал по своему чувству прекрасного :)
