### ISSUE TITLE
Rename `common.docs` to `docs` dir

### ISSUE THREAD

**Issue by blond** [bem/bem-core#1156]
- `common.docs` easily confused with built documentation (`desktop.docs`, `touch.docs`)
- `docs` is more common and usual name

**Comment by sipayRT** [comment]
:+1:

**Comment by veged** [comment]
can't catch a problem at all

**Comment by tadatuta** [comment]
that costs us nothing but will make some external tools easier to use, so I'd keep this issue open

**Comment by veged** [comment]
can't understand why "nothing" — we need to commit something, moreover need to fix build tools for site, also we consciously consider this docs as "blocks in .*.md techs"
