### ISSUE TITLE
Use API v2 for `.bem/levels/*.js`

### ISSUE THREAD

**Issue by veged** [bem/bem-core#1216]
Get rid of `Tech module "bundles" at <SKIPED>/bem-core/.bem/levels/bundles.js is using API V1.` and `Tech module "blocks" at <SKIPED>/bem-core/.bem/levels/blocks.js is using API V1.`

**Comment by tadatuta** [comment]
@veged 
Please provide the way to reproduce.

I tested following commands in the root of `bem-core` folder:

``` sh
bem create -b blah
bem create -b b1 -l blah.blocks -T browser.js
bem create -b page1 -l blah.bundles -T bemjson.js
```

and got no warns.

**Comment by veged** [comment]
can't catch more isolated but, you can try check out https://github.com/shriming/chat/tree/issues/18 (note branch `issues/18`) and do `cd frontend && bem create -b bla -T blocks`

**Comment by tadatuta** [comment]
This is not an issue of `bem-core`, please refer to https://github.com/shriming/chat/issues/43 for fix.
