### ISSUE TITLE
docs: describe breaking changes in 2.7.0

### ISSUE THREAD

**Issue by Guria** [bem/bem-core#1220]
See https://github.com/bem/bem-forum-content-ru/issues/600 for  reference

> What do I do if I accidentally release a backwards incompatible change as a minor version?
> 
> As soon as you realize that you've broken the Semantic Versioning spec, fix the problem and release a new minor version that corrects the problem and restores backwards compatibility. Even under this circumstance, it is unacceptable to modify versioned releases. If it's appropriate, document the offending version and inform your users of the problem so that they are aware of the offending version.

**Comment by veged** [comment]
@Guria could you provide PR?

**Comment by Guria** [comment]
Sorry, I don't remember details

**Comment by veged** [comment]
I'm afraid it's lost topicality since v3 and new versions of bem-xjst
