### ISSUE TITLE
Feedback for "События"

### ISSUE THREAD

**Issue by bu1ka** [bem/bem-core#1233]
Кажется [тут](https://ru.bem.info/technology/i-bem/v2/i-bem-js-events/#События-при-изменении-модификаторов) нужно написать чуть подробнее и переименовать парамент `event` в, например `block`

> Для подписки на БЭМ-события при изменении модификатора блока или элемента используется метод экземпляра блока `on(block, [data], handler, [handlerCtx])`, который принимает аргументы:
> - block – объект свойств модификатора, на который производится подписка;
> - [data] — необязательные произвольные данные, передаваемые функции-обработчику.
> - handler – функцию-обработчик, выполняющуюся при установке соответствующего модификатора.
> - [handlerCtx] – необязательный контекст функции-обработчика события. Если отсутствует, функция-обработчик будет выполняться в контексте экземпляра блока, в котором произошло событие.

**Comment by tadatuta** [comment]
Про более подробное описание аргументов согласен, а про переименование `event` в `block` я бы поспорил — все-таки здесь `event` является названием события, на которое нужно подписаться, просто переданным в форме JS-объекта.

// cc @innabelaya

**Comment by veged** [comment]
close in favour of #1279
