### ISSUE TITLE
i-bem: afterSetMod helper suggestion

### ISSUE THREAD

**Issue by qfox** [bem/bem-core#1234]
afterSetMod = onSetMod + afterCurrentEvent

Pretty often I see code like:

```
    onSetMod: {
        modifier: function() {
            this.afterCurrentEvent(function() {
                someAnotherBlock.etc(); // ...
```

And this can be simplified to:

```
    afterSetMod: {
        modifier: function() {
            someAnotherBlock.etc(); // ...
```

Seems pretty legit, isn't it?

**Comment by tadatuta** [comment]
Are you sure? `afterCurrentEvent()` was removed in honour of `next-tick` in [2.0.0](https://en.bem.info/libs/bem-core/v2.8.0/changelog/#200) and since `onSetMod` was splitted on actually `onSetMod` and `onBeforeSetMod` it doesn't look like a common case ;)

**Comment by qfox** [comment]
Okay, afterSetMod = onSetMod + nextTick.

Did you mean `onSetMod` already works like `afterSetMod`? Or I can't change modifier in their onSetMod? Looks like inconsistency ;-(

**Comment by narqo** [comment]
@zxqfox the code from issue's description was relevant before bem-core=2.0 and the most usecase (AFAIR it was the only usecase) was to fire event after the modifiers was actually set. Regardless the fact of it's frequency the asynchronous brought a lot of issues to the end-users.

> Did you mean onSetMod already works like afterSetMod? [..]

To say "`onSetMod` from previous version worked most like current `beforeSetMod`" would be more fair, as you could prevent modifier from being set by returning `false` from the handler.

**Comment by qfox** [comment]
My bad, all is fine here.

Thanks for attention!
