### ISSUE TITLE
Update jscs to 2.x

### ISSUE THREAD

**Issue by veged** [bem/bem-core#1235]

**Comment by qfox** [comment]
Emh, can we merge this? https://github.com/bem/bem-core/pull/1115

**Comment by qfox** [comment]
Builds failing because of peer deps of enb. Guess we need to update it first to be sure.

**Comment by narqo** [comment]
Looks like must be closed with #1284

**Comment by qfox** [comment]
Yeah, jscs@2.x in v4. Do we need it for v2? Not sure.

**Comment by narqo** [comment]
@zxqfox we need in v3 as it's going to become our "main" branch soon.
