### ISSUE TITLE
Get an infinite timeouts loop while using bem

### ISSUE THREAD

**Issue by just-boris** [bem/bem-core#1236]
Found that my code with bem-components never hangs up. The reason of this behavior is `tick` module.

Dist-bundle of bem-components has [`start_auto`](https://github.com/bem/bem-core/blob/v2/common.blocks%2Ftick%2F_start%2Ftick_start_auto.vanilla.js#L7) enabled by default. Is there a way to disable this without need to rebuild my own dist?

It is make sense for me, since I am trying to run tests in node.js with jsdom, but that infinite ticks do not allow to finish my test process

**Comment by dfilatov** [comment]
``` js

modules.require(['tick'], function(tick) {
    tick.stop();
});
```

**Comment by just-boris** [comment]
Well, this code stops tick for a while, but block `input` [starts them again](https://github.com/bem/bem-components/blob/v2/desktop.blocks/input/input.js#L13).

Is there a way to disable ticks forever? I guess it is used to poll input for values, that's ok to disable it for testing purposes.

**Comment by dfilatov** [comment]
I think if you call above code after all tests have been completed, it won't start again.

**Comment by just-boris** [comment]
It worked, thanks
