### ISSUE TITLE
[doc] dom: Typo in method description

### ISSUE THREAD

**Issue by RumyantsevMichael** [bem/bem-core#1237]
На странице https://ru.bem.info/libs/bem-core/v2.7.0/desktop/dom/
в разделе "Обзор - свойства и методы объекта" (https://ru.bem.info/libs/bem-core/v2.7.0/desktop/dom/#Свойства-и-методы-объекта-2)
и в "Описание - свойства и методы объекта" (https://ru.bem.info/libs/bem-core/v2.7.0/desktop/dom/#Свойства-и-методы-объекта-3)
различается порядок следование аргументов метода contains

**Comment by tadatuta** [comment]
@RumyantsevMichael Спасибо!
