### ISSUE TITLE
bem-core inherit | Документация: Ошибки в примере кода

### ISSUE THREAD

**Issue by RumyantsevMichael** [bem/bem-core#1238]
На странице https://ru.bem.info/libs/bem-core/v2.7.0/desktop/inherit
в разделе "Создание производного класса" (https://ru.bem.info/libs/bem-core/v2.7.0/desktop/inherit/#Создание-производного-класса)
в примере кода явно напутаны скобки.
Там же идёт вызов метода `instanceOfB.getType();`, вместо `instanceOfB.getAll();`

**Comment by tadatuta** [comment]
@RumyantsevMichael Спасибо!
