### ISSUE TITLE
Возможность доопределения jquery__event на уровне проекта

### ISSUE THREAD

**Issue by vitkarpov** [bem/bem-core#1247]
Для совместимости со старым кодом, бывает полезно иметь возможность доопределить некоторые модификаторы `jquery__event`.

Конкретно, нам в проекте потребовалось добраться до `FastClick`, который используется в `jquery__event_type_pointerevents`.

С текущей версией `bem-core` получить ссылку на него нельзя.

Что сделал в своем форке:
- определил элементы `jquery__event` как отдельные элементы с точки зрения модульной системы, чтобы была возможность доопределить реализацию модификаторов на уровне проекта
- из `jquery__event_type_pointerclick` экспортирую FastClick

Имеет ли смысл вносить это в мастер?

**Comment by vitkarpov** [comment]
https://github.com/vitkarpov/bem-core/commit/e572232cf7a95435e9c9da08548b2ed2d158878c

**Comment by dfilatov** [comment]
А что именно вы патчите в FastClick? Это не будет всем полезно?

**Comment by vitkarpov** [comment]
Не-а, вряд ли будет. Сейчас у нас есть старые компоненты, которые рассчитывают на mousedown на мобильных :(

FastClick на onTouchEnd (https://github.com/bem/bem-core/blob/v2/common.blocks/jquery/__event/_type/jquery__event_type_pointerclick.js#L514) делает preventDefault в некоторых случаях и mousedown теряется.

Честно говоря, не получится сделать как я хотел: есть jquery__event_type_pointerclick, который экспортирует FastClick, чтобы можно было доопределить на уровне проекта.

Не завелось потому что возникает циклическая зависимость: jquery -> jquery__event_type_pointerlclick -> jquery, потому в jquery__event_type_pointerclick нужна ссылка на jquery, нужно ж кастомные события определить.

Пока ничего лучше не придумал, кроме как положить FastClick в $, т.е. сделать ссылку $.FastClick, чтобы в итоге вытащить FastClick из замыкания модуля :(

**Comment by vitkarpov** [comment]
@dfilatov @veged @tadatuta коллеги, нет мыслей как это правильно сделать? понимаю, что в принципе такой ситуации быть не должно (что на мобильных mousedown нужен), но в реальности встречается

**Comment by narqo** [comment]
> [..] Сейчас у нас есть старые компоненты, которые рассчитывают на mousedown на мобильных :(

Нужно честное dom-событие? Не получится, к примеру, «эмулировать» его из `pointerdown`, который мы эмулируем через PEP?

**Comment by vitkarpov** [comment]
А поясни подробнее? Вот есть библиотека, где-то внутри $(...).on('mousedown', ...) — это трогать не получится. Каким образом заработает mousedown в итоге?

**Comment by qfox** [comment]
Не все могут использовать FastClick и патчить его в наше время. Мало кто может это делать.

**Comment by vitkarpov** [comment]
@zxqfox всмысле? не совсем понял :)

**Comment by qfox** [comment]
Это я так невнятно выражаю удивление факту использования FastClick ;-)

**Comment by narqo** [comment]
@vitkarpov я думал про «костыль» на уровне тач-устройств, который подменяет одно событие другим (через jquery special event). Примерно так же, как сейчас работает `pointerclick` https://github.com/bem/bem-core/blob/v2/common.blocks/jquery/__event/_type/jquery__event_type_pointerclick.js#L769-L785

@zxqfox 

> Это я так невнятно выражаю удивление факту использования FastClick

#1088 — label:v3 (ждем, пока само пройдет).

**Comment by vitkarpov** [comment]
Типа, на тачах определить `mousedown` через special event? Мысль понял. Спасибо. Подумаю.
В любом случае, ссылку на FastClick получить удалось, но не так «красиво» как я думал.

**Comment by veged** [comment]
раз удалось найти воркараунд предлагаю тикет про изменения в ядро закрыть

**Comment by vitkarpov** [comment]
Ага, спасибо!
