### ISSUE TITLE
i-bem__dom_init_auto: Explicit dependency from i-bem__dom_init

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#1248]
`i-bem__dom_init_auto` [requires](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/__dom/_init/i-bem__dom_init_auto.js#L6) `i-bem__dom_init` to be strictly before it in bundle but has no `mustDeps` dependency now.

**Comment by narqo** [comment]
Any comments / description for the issue?

**Comment by tadatuta** [comment]
@narqo added description

**Comment by dfilatov** [comment]
@tadatuta Why do you think that "`i-bem__dom_init_auto` requires `i-bem__dom_init` to be strictly before"? `modules.require` doesn't require that its dependencies to be strictly before.

**Comment by narqo** [comment]
@tadatuta isn't `modules.require` [asynchronous](https://github.com/ymaps/modules/blob/095f23a2f6cdc0066e4dceb0e58cda25dfa4bfac/modules.js#L73-L91)?

**Comment by tadatuta** [comment]
you are right, there was a bug in deps techs which was fist fixed with mustDeps for `i-bem__dom_init` but now there's a fix in module itself.
