### ISSUE TITLE
Feedback for "Справочное руководство по шаблонизатору BEMHTML"

### ISSUE THREAD

**Issue by dzenkiedo** [bem/bem-core#1252]
Здравствуйте.
Не могу понять, почему у меня  не работает пример из справочного руководства

https://ru.bem.info/technology/bemhtml/v2/reference/#Использование-позиции-БЭМ-сущности

скопировал один-в-один и решил проверить на странице online demo
http://bem.github.io/bem-xjst/

получил вот такой результат (скрин экрана)

https://yadi.sk/i/EgVlTuK8ndLc5

**Comment by tadatuta** [comment]
@dzenkiedo В документации опечатка, нужно заменить `elemMatch` на `elem`.
Исправил в https://github.com/bem/bem-core/commit/c8cfc09afd58efd55946984c8a82c16bbfadc7d7

Спасибо!

**Comment by dzenkiedo** [comment]
https://ru.bem.info/technology/bemhtml/v2/templating/#Декларативный-подход

Здесь получается то же самое наверное.

**Comment by tadatuta** [comment]
Да, исправил, спасибо еще раз!
