### ISSUE TITLE
Drop everything about BEMHTML/BEMTREE base templates

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#1258]
In newest versions of bem-xjst (#1283) basic templates are embedded — so we can drop everything about this in bem-core library.

**Comment by miripiruni** [comment]
:+1:

**Comment by tadatuta** [comment]
let's do it in `v3`?

cc @veged

**Comment by narqo** [comment]
@tadatuta we agree, could you do this and #1283?

**Comment by tadatuta** [comment]
ok, assigned to myself
