### ISSUE TITLE
Feedback for "Общие сведения о фреймворке"

### ISSUE THREAD

**Issue by Smolnikovp** [bem/bem-core#1266]
> Базовая реализация JS-блока i-bem, от которой наследуются все блоки в i-bem.js. Блок i-bem написан с расчетом на использование в любом JS-окружении: как на клиенте, так и на сервере например, в Node.js).

отсутствует открывающая скобка перед "например"

**Comment by tadatuta** [comment]
@Smolnikovp Спасибо, исправлено в https://github.com/bem/bem-core/commit/9decdc07fb66b11e02b4900a76722cf80391dcb4
