### ISSUE TITLE
Feedback for "Быстрый старт по BEMHTML"

### ISSUE THREAD

**Issue by 3ABAPKA** [bem/bem-core#1268]
Думается верным добавить строчку:

> ## Минимальные требования
> 
> Node.js 0.10+ или io.js;
> Git Bash – для пользователей операционной системы Windows.

без этого `npm install` выдает `bash: npm: command not found`

**Comment by tadatuta** [comment]
На самом деле пользователю нет необходимости устанавливать зависимости в библиотеке, если только он не хочет участвовать в ее разработке. Мы предполагаем, что для тех, кто готов контрибьютить в `bem-core`, требование про `node.js` для установки `npm-зависимостей` является очевидным.

А для использования `bem-core` на своем собственном проекте в документации рекомендуется использовать `project-stub`, где требования к `node.js` и `git bash` описаны.
