### ISSUE TITLE
page: Wrong user-scalable value in meta name=viewport on touch level

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#1294]
https://github.com/bem/bem-core/blob/v2.9.0/touch.blocks/page/page.bh.js#L14-L20

`page` adds `<meta name=viewport>` with `user-scalable=0` which is not a valid value. 

See https://drafts.csswg.org/css-device-adapt/#user-scalable

> The user-scalable property is translated into user-zoom with the following value translations.
> - yes and no are translated into zoom and fixed respectively.
> - Numbers ≥ 1, numbers ≤ -1, device-width and device-height are mapped to zoom
> - Numbers in the range (-1, 1), and unknown values, are mapped to fixed

The valid value is `no`.

/cc @doochik @tadatuta

**Comment by doochik** [comment]
This will fix https://github.com/bem/bem-components/issues/1738 because fast click will be disabled for chrome on pages with meta `user-scalable=no`
