### ISSUE TITLE
Release 4.0.0

### ISSUE THREAD

**Issue by veged** [bem/bem-core#1310]
- [x] Document changes:
  - [x] #967
- [x] Changelog #1417 
- [x] Translate migration guide and changelog to English

**Comment by narqo** [comment]
Also we need to add some notes about [`events__observable`](https://github.com/bem/bem-core/tree/v4/common.blocks/events/__observable), as a way to subscribe to bem-events from the outer world (see https://ru.bem.info/forum/1020/#comment-223608883).

**Comment by tadatuta** [comment]
Add notes about `.bem()` argument change with examples for complex cases like https://github.com/bem/bem-components/blob/v3/common.blocks/control/control.js#L121

**Comment by narqo** [comment]
Don't forget to add changes from #1376 to the migration guide.

**Comment by tadatuta** [comment]
Add note about `getDefaultParams` -> `_getDefaultParams` to https://github.com/bem/bem-core/blob/v4/MIGRATION.ru.md#Имена-protected-методов-начинаются-с-_

**Comment by tadatuta** [comment]
There are two methods `getName` and `getEntityName` returning the same result (https://github.com/bem/bem-core/blob/v4/common.blocks/i-bem/i-bem.vanilla.js#L485-L499).
Which to use and why?

**Comment by narqo** [comment]
`getEntityName` returns full BEM entity name, e.g. `button` or  `Input__clear` in case of elem instance. `getName` returns self name of the entity: `button` and `clear` for the same examples as above.

The former is primary used to build proper CSS class and to distinguish block instance from the elem.

**Comment by tadatuta** [comment]
@narqo take a look at the link I provided, the methods are implemented absolutely the same way (`return this._name;`).

**Comment by narqo** [comment]
Yes, but `getEntityName()` is overridden in `Elem` class. Check [L541](https://github.com/bem/bem-core/blob/f1fd1bd4fd224012e6fca481699bd4e760da3f53/common.blocks/i-bem/i-bem.vanilla.js#L514-L544).

**Comment by tadatuta** [comment]
Update migration guide about `_elems()` method (remove it from https://github.com/bem/bem-core/blob/v4/MIGRATION.ru.md#Имена-protected-методов-начинаются-с-_) and describe difference about `this.elem()` VS `this.elems().domElem` now.

**Comment by aristov** [comment]
This works in older versions:

``` js
Suggest.declMod({ modName : 'has-dataprovider' });
```

but doesn't work in `v4`. Works only with asteriks:

``` js
Suggest.declMod({ modName : 'has-dataprovider', modVal : '*' });
```

**Comment by dfilatov** [comment]
@aristov see #1374

**Comment by tadatuta** [comment]
Looks like https://github.com/bem/bem-core/issues/1310#issuecomment-227145103 was missed.
