### ISSUE TITLE
Move page to bem-components?

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-core#1323]
Page is an alone block with bemhtml. All visual components living in `bem-components`. Why `bem-core` can't be a clear library without any templates?

**Comment by qfox** [comment]
It can be a bem-page library, but not a block in bem-compontent. Page is not a component. Definitely.

**Comment by awinogradov** [comment]
Page is a block, right?) `bem-components` contains blocks, right?) Can you explain your expression?) Page can have js and css like other components. `bem-page` is a simple way, I'm agree. It can solve the problem in `package.js`. Ex: 

> npm i bem-components

``` js
require('node_modules/bem-core/common.blocks/page') // nobody knows what is it and where it from
```

**Comment by veged** [comment]
`page` is very «basic» block, you can't make almost any web-site without this — so that's why we call it «core»
