### ISSUE TITLE
Why page depends on i-bem?

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-core#1324]
https://github.com/bem/bem-core/blob/v3/common.blocks/page/page.deps.js#L3

Now bem-core free from base templates and page doesn't need i-bem for right work. I think it should be optional on the project's level because I want to build the project without i-bem.

**Comment by narqo** [comment]
99% of our projects need `i-bem__dom_init_auto` (see bem/bem-bl#298). This is the only reason [this deps](https://github.com/bem/bem-core/blob/e15aa9267aed8a088726cd20003bff9132915f6a/common.blocks/page/page.deps.js#L3) are there. Nobody, and I mean it, wants to have this tiny line in their project's deps. 

We've spent several years debating with our internal users about this thing. And, actually, this was the reason deps.js supports `noDeps`.

**Comment by tadatuta** [comment]
@awinogradov looks like the solution for your task is to copy/paste `page` template to `react-bl` and get rid of `bem-core` at all

**Comment by awinogradov** [comment]
Yeah, 99% projects. Ok. Why I need to write deps for input_has-clear if I want it and I need to write noDeps for i-bem?  I think we must use the same politic for the same things. If I want I should call deps. Am I wrong?

@tadatuta it's not about react-bl. It's the common question.

**Comment by Guria** [comment]
@awinogradov maybe `bem-page` as standalone package is pretty good solution in fact.

**Comment by veged** [comment]
`page` with `i-bem__dom_init_auto` is not the same as `input_has-clear` in terms of usage — so we use same politic witch produce different result for different cases

**Comment by qfox** [comment]
We shouldn't close questions instantly, I guess.
