### ISSUE TITLE
Feedback for "Взаимодействие блоков"

### ISSUE THREAD

**Issue by zakaratcha** [bem/bem-core#1344]
В статье приведен пример "Вызов статического метода close блока popup позволяет закрыть все попапы на странице".
Но у popup нет такого статического метода :(

А мне вот как раз понадобилось закрыть все попапы на странице и поиск выдает только эту статью.
Также из документации не могу понять, как достучаться до экземпляров блока из статических методов (пытаюсь реализовать этот самый метод close на своем уровне переопределения)

**Comment by tadatuta** [comment]
``` js
modules.define('popup', function(provide, Popup) {

var visiblePopupsStack = [];

provide(Popup.decl({ modName: 'autoclosable', modVal: true }, {
    onSetMod: {
        visible: {
            'true': function() {
                this.__base.apply(this, arguments);
                visiblePopupsStack.unshift(this);
            },
            '': function() {
                this.__base.apply(this, arguments);
                visiblePopupsStack.splice(visiblePopupsStack.indexOf(this), 1);
            }
        }
    }
}, {
    hideAll: function() {
        visiblePopupsStack.forEach(function(popup) {
            popup.delMod('visible');
        });
    }
}));

});
```

**Comment by zakaratcha** [comment]
Спасибо.
Правда в моем случае без { modName: 'autoclosable', modVal: true }
