### ISSUE TITLE
Add support for `modVal : '*'` in `declMod`

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#1374]
Used for example in https://github.com/bem/bem-components/blob/v3/common.blocks/button/_togglable/button_togglable.js#L12 or https://github.com/bem/bem-components/blob/v3/common.blocks/popup/_target/popup_target.js#L31

``` js
modules.define('b1', ['i-bem-dom'], function(provide, bemDom) {

provide(bemDom.declBlock(this.name, {
    m1: function() {
        console.log('initial m1');
    },
    m1_v1: function() {
        console.log('initial m1_v1');
    }
}));

});

modules.define('b1', function(provide, B1) {

provide(B1.declMod({ modName: 'm1' }, {
    m1: function() {
        console.log('overriden m1');
    }
}));

});

modules.define('b1', function(provide, B1) {

provide(B1.declMod({ modName: 'm1', modVal: 'v1' }, {
    onSetMod: {
        js: {
            inited: function() {
                this.m1();
                this.m1_v1();
            }
        }
    },
    m1_v1: function() {
        console.log('overriden m1_v1');
    }
}));

});
```

Expected: `overriden m1 overriden m1_v1`.
Actual result: `initial m1 overriden m1_v1`.

**Comment by veged** [comment]
`B1.declMod({ modName: 'm1' }` is shortcut for `B1.declMod({ modName: 'm1', modVal: true }` and we never have ability to declare wildcard modifier

**Comment by veged** [comment]
we change semantic of omitted `modVal` accordingly to `setMod` (if no `modVal` it's short cut for `modVal : true`)

so we need to add support for `B1.declMod({ modName: 'm1', modVal: '*' },` as in `onSetMod`
