### ISSUE TITLE
i-bem-dom: `domElem` -> `_domElem`

### ISSUE THREAD

**Issue by veged** [bem/bem-core#1377]
See https://ru.bem.info/forum/1020/

**Comment by narqo** [comment]
Do we really need this? We also have `this.params` that must be renamed as well.

/cc @dfilatov

**Comment by veged** [comment]
I think so — if you started to clean it's hard to stop ;-) we are hostages of consistency

**Comment by dfilatov** [comment]
@veged About `params`. You used to say that block params were used to store something that should be available for outside blocks.

**Comment by veged** [comment]
sounds possibly — so let's do `domElem` -> `_domElem` first ;-)

**Comment by narqo** [comment]
I can't realise why `domElem` must be protected. 

We use it as a public property in every block's spec, e.g. `button.domElem.click()` and this is the only way for users to write their own specs. It's totally lame to make people use protected / private properties as a public one just because "we were hostages".

**Comment by veged** [comment]
See https://ru.bem.info/forum/1020/ — there is a way to bind DOM-events bypass our API

**Comment by narqo** [comment]
I've read the thread but, how the issue solves it. It'd be possible to do it as `this._domElem.on('click')`. I can't catch your point.

**Comment by veged** [comment]
when you do `this._domElem.on('click')` you lost "warranty" because of private API

**Comment by narqo** [comment]
> when you do this._domElem.on('click') you lost "warranty" because of private API

I really think we've a kind of misunderstanding about what API and warranties are. 

1) What the difference from the API point of view in `this._elem()`, `this._emit()` and `this._domElem`. Am I lose any warranties when I use `this._elem()` too? 

2) [Almost all `domElem` usage](https://github.com/bem/bem-components/search?&q=domElem) in our own code is in a way `button.domElem.click()`. I don't understand why it's normal to suggest to use private APIs for users who want to write tests for their blocks.

3) We have

``` js
this._menu.domElem.css('min-width', this._buttonWidth = this._button.domElem.outerWidth());
```

and

``` js
this._button.domElem.attr('aria-activedescendant', item.domElem.attr('id'));
```

in https://github.com/bem/bem-components/blob/v3/common.blocks/select/select.js

If `domElem` is private now, blocks must introduce API methods to do crazy stuff like "calculate my dimensions" and "set weird HTML attributes to deal with a11y, but only if I'm a part of a complex block".

**Comment by narqo** [comment]
For me `domElem` is the same kind of API as `setMod` or `findChildElems`. I can do `this.findChildBlocks(Block).findChildElems(BlockElem).setMod('type', 'weird')` and it migth break things, but it's not the case.

> > About params. You used to say that block params were used to store something that should be available for outside blocks
> 
> sounds possibly

This is insane! We **do have tonnes of cases** where we use `domElem` as a public property as it must be available for outside blocks and we want to make it private. But have a **theoretical** case where `params` could be used as a public property so we leave it public o_O

**Comment by veged** [comment]
ok — "won't fix" for now
