### ISSUE TITLE
Инициализация блока без имени

### ISSUE THREAD

**Issue by RumyantsevMichael** [bem/bem-core#1380]
bem-core@2.8
Обнаружил вот какую особенность. Если на дом-элемент повесить класс i-bem и в data-bem добавить хеш с параметрами некоего блока, а в список классов имя блока не добавлять, то блок  этот инициализируется и работает, но не ищется другими блоками через `findBlockXXX()`

**Comment by dfilatov** [comment]
Инициализируются блоки по data-bem параметрам, а ищутся по css-селекторам.
