### ISSUE TITLE
_emit('event', 'data')  _events().on('event', cb) bug?

### ISSUE THREAD

**Issue by belozer** [bem/bem-core#1392]
Всем привет. Ней пойму, баг ли это.
Как правильно передать данные по событию?

Делаю подписку

`this._events().on('submit', function(data) { console.log('form', data) });`

делаю в блоке _emit

`this._emit('submit', 'data test');`

И вот результат из браузера
![2016-07-26 10-07-45](https://cloud.githubusercontent.com/assets/1655916/17129480/0e048d54-531c-11e6-8630-c5c59712e6d8.png)

**Comment by dfilatov** [comment]
``` js
this._events().on('submit', function(e, data) { console.log('form', data) });
```

**Comment by belozer** [comment]
@dfilatov спасибо! Всё получилось. Закрываю issue.
