### ISSUE TITLE
Why there is the difference between mod vals '*' and true?

### ISSUE THREAD

**Issue by qfox** [bem/bem-core#1403]
What's the point of differentiating `modVal: '*'` and `modVal: true`?

Boolean modifiers has no any values except `true` value.
Non-boolean modifiers don't need `true` value (only string values).

Are there any real life cases when we need `true` and string-typed values for the same modifier?

**Comment by narqo** [comment]
I'm not sure I caught the point. Do you mean we should cast string `'true'` to Boolean `true`?

**Comment by qfox** [comment]
No, I mean we don't need special `'*'` value because there are no modifiers with combined `true` and `'normal'` values.

**Comment by narqo** [comment]
We use `*` in event handlers 

``` js
this._bemEvents().on({ modName : 'focused', modVal : '*' }, this._onFocusChange)
```

It matches the empty value, e.g. `modVal : ''` as well.

Could you be more specific, in what cases do you think it's redundant?

**Comment by qfox** [comment]
Sorry, my mistake.
