### ISSUE TITLE
BEMHTML: Support escaped mode

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#1406]
In `.enb/make.js` for BEMHTML:

``` js
{
    engineOptions: { escapeContent: true }
}
```

It fails at least for doctype in `page` template.

**Comment by qfox** [comment]
You should check for html-entities (and replace them with utf-8 characters in common), BEMHTML.reapply & BH.apply & manually written scripts in ua block (replace with `{tag: false, html: ...}`). Maybe something more.
