### ISSUE TITLE
querystring.stringify does not support arrays

### ISSUE THREAD

**Issue by JiLiZART** [bem/bem-core#1418]
Передаю объект с массивом параметров

`querystring.stringify({param: [1, 2, 3, 4, {adasd : 'adasd'}]})` 
получаю
`param=1&param=2&param=3&param=4`

`jQuery.param({param: [1, 2, 3, 4, {adasd : 'adasd'}]})` 
получаю 
`param[]=1&param[]=2&param[]=3&param[]=4&param[4][adasd]=adasd`

Может тогда имеет смысл использовать валидную версию от jquery?

**Comment by narqo** [comment]
Поведение соответсвует [`querystring` в Node.js](https://nodejs.org/dist/latest-v6.x/docs/api/querystring.html#querystring_querystring_stringify_obj_sep_eq_options):

```
› node -p "require('querystring').stringify({param: [1, 2, 3, 4, {adasd : 'adasd'}]})"

param=1&param=2&param=3&param=4&param=
```

Насколько я помню, строку `param[]=1&param[]=2` невозможно адекватно десериализовать нигде, кроме PHP.
