### ISSUE TITLE
I-bem static field declaration/ live section in modifiers work for block without it.

### ISSUE THREAD

**Issue by L0stSoul** [bem/bem-core#1433]
I think it's very counter intuitive behaviour, and it's need to be changed. For me it's looks like  source of error's and nothing more.

I think better to forbid static field declaration in modifiers, it's work exactly like static field declaration in block itself and must be written in block declaration.

**Comment by L0stSoul** [comment]
Кажется что оно делает ровно то что статик секция в самом блоке но находится в не очевидном месте(это как положить в блок с модификатором .css который афектит вообще все блоки даже без модификаторов, технически можно, но идеологически кажется неправильно)

Судя по тому что об это раз за разом спотыкаются, такое поведение лучше просто запретить инструментально. Техническая возможность кидать исключение  если лайв секция находится в декле модификатора кажется должна быть.

**Comment by qfox** [comment]
> технически можно, но идеологически кажется неправильно
> 
> Техническая возможность кидать исключение если лайв секция находится в декле модификатора кажется должна быть.

Можно кидать исключение, но кажется, что достаточно линтеров и их подсказок. Были бы линтеры)

**Comment by L0stSoul** [comment]
Ну это уже вкусовщина, но если не смотреть на legacy я был бы за более жесткий вариант :)

**Comment by veged** [comment]
> Важно: Свойство live относится к статическим методам класса блока. Поэтому даже если оно задано в декларации блока с определённым модификатором, live будет применено ко всем блокам данного класса вне зависимости от модификаторов.
> https://ru.bem.info/platform/i-bem/init/

**Comment by L0stSoul** [comment]
Veged, если задокументировать нелогичное поведение, оно от этого менее нелогичным не становится.  И как мы на этом спотыкались, так и будем спотыкаться.

**Comment by dfilatov** [comment]
@L0stSoul Пример, когда live-секцию нужно писать в модификаторе, а не в основном блоке:

``` js
Action.decl({ modName : 'type', modVal : 'icon' }, {
        ...
}, {    
    live : function() {
        this.liveBindTo({ modName : 'type', modVal : 'icon' }, 'pointerclick', function() {
            this._onAction();
        });
    }
});
```

**Comment by L0stSoul** [comment]
Имхо это потрясающая возможность накосячить, и с этим нужно что то делать, но один я спорить не буду так что смотрите сами :)
