### ISSUE TITLE
The modal__autocloseable closes immediately after opening in touch browsers (touch events)

### ISSUE THREAD

**Issue by vsesh** [bem/bem-core#1442]
Button opens modal with autocloseable modifier. After click modal shows a one moment. It's happens because modal catches 'click' event. The 'click' event is a program event after 'touchend'.

I can reproduce in iOS (bem-core#v4), AndroidBrowser (bem-core#v4, bem-core#v3), Chrome for Android (bem-core#v4, bem-core#v3), Chromium on Windows 10 with touchscreen (bem-core#v4, bem-core#v3).

@dfilatov

**Comment by veged** [comment]
moved to https://github.com/bem/bem-components/issues/1958
