### ISSUE TITLE
`modules.define` recursion problem

### ISSUE THREAD

**Issue by doochik** [bem/bem-core#1446]
Наткнулся на проблему из-за вот этого места https://github.com/bem/bem-core/blob/v3/common.blocks/i-bem/__dom/i-bem__dom.js#L1563

Каждый блок делает define `i-bem__dom_init`, соответственно при резолве получается большая рекурсия и большой стек. В моем проекте от этого пострадал живой пользователь и ферма автотестов. Firefox'ы в определенном окружении (win/linux) падают с 'too much recursion'

Хочется отсюда рекурсию убрать. Пока запатчил вот так (да, storedDeps некрасиво передается по ссылке)
```js
(function() {

var origDefine = modules.define;
var storedDeps = [];
var iBemDomInitDefined = false;

modules.define = function(name, deps, decl) {
    origDefine.apply(modules, arguments);

    if (name !== 'i-bem__dom_init' && arguments.length > 2 && ~deps.indexOf('i-bem__dom')) {
        storedDeps.push(name);
        if (!iBemDomInitDefined) {
            iBemDomInitDefined = true;
            modules.define('i-bem__dom_init', storedDeps, function(provide, _, prev) {
                provide(prev);
            });
        }

    }
};

})();
```

Есть идеи как это исправить? @narqo @dfilatov

**Comment by doochik** [comment]
Сделал пока форк, в проекте все починилось
https://github.com/doochik/bem-core/commit/2a2af552b8ea30b289b6dd12c45a8d37ca5f9092

**Comment by dfilatov** [comment]
@doochik А на какой глубине рекурсии это проявляется?

**Comment by doochik** [comment]
Из-за лимита отдаваемого стека не могу нормально посчитать. Пока получилось так.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <script src="https://yastatic.net/bem-components/latest/desktop/bem-components.js"></script>
</head>
<body>
<script>
    // stack 124 lines

    // 129
    modules.define('test', ['i-bem__dom'], function(provide) {
        provide({});
    });

    // 134
    modules.define('test2', ['i-bem__dom'], function(provide) {
        provide({});
    });

    // 139
    modules.define('test3', ['i-bem__dom'], function(provide) {
        provide({});
    });

    modules.define('i-bem__dom_init', function(provide, prev) {
        console.trace('i-bem__dom_init');
        provide(prev);
    });
</script>
</body>
</html>
```

Получается, каждый блок добавляет 5 вызовов.
У нас 200+ блоков, т.е. стек будет в районе 1000 вызовов.

Погоняли http://adamrich.name/recursion.html, у пострадавшего лимит 5к, у меня 100к. Но тест тоже странный, потому что цифры постоянно скачут (для меня 70к-120к).
Кажется, все сильно зависит от окружения.

**Comment by narqo** [comment]
Есть гипотиза, что проблема конкртено с реализацией `function.call()` в Firefox под linux (у них есть старый тикет https://bugzilla.mozilla.org/show_bug.cgi?id=966173). Надо найти линукс машину посмотреть.

**Comment by dfilatov** [comment]
@doochik Чтобы твой воркэраунд заработал с дозагрузкой бандлов в рантайм, надо еще сбрасывать `iBemDomInitDefined` и очищать `storedDeps`.

**Comment by doochik** [comment]
Нет, при дозагрузке бандлов bem-dom-init уже не участвует в процессе. И надо делать `modules.require('my-pack')` со всеми deps. Тут схема не должна поменяться.

**Comment by dfilatov** [comment]
@doochik see https://github.com/bem/bem-core/blob/v3/common.blocks/loader/_type/loader_type_bundle.js#L111

**Comment by doochik** [comment]
Ага, можно вот так сделать 
https://github.com/doochik/bem-core/commit/8663f554c4f82c9adce4cd7091c70779b86ae483

**Comment by doochik** [comment]
3.1.1 выпустите?

**Comment by tadatuta** [comment]
@doochik да, только будет `3.2.0`, т.к. войдет новая фича про атрибут `lang` для `<html>` (https://github.com/bem/bem-core/commit/41534bb79bfc75a26584c1ff03ae545e989ed066).

**Comment by doochik** [comment]
Вов, маякни, плиз, как будет. Я с форком не хочу жить :)

**Comment by tadatuta** [comment]
@doochik done: https://github.com/bem/bem-core/releases/tag/v3.2.0
