### ISSUE TITLE
На https://ru.bem.info/platform/i-bem/interaction/ все ссылки в тексте битые

### ISSUE THREAD

**Issue by fual** [bem/bem-core#1473]
На https://ru.bem.info/platform/i-bem/interaction/ все ссылки в тексте битые
Например, первая ссылка
https://ru.bem.info/platform/i-bem/interaction/i-bem-js-events.ru.md/#bem-events
и последняя
https://ru.bem.info/platform/i-bem/interaction/i-bem-js-events.ru.md/

**Comment by innabelaya** [comment]
@tadatuta @vithar

**Comment by innabelaya** [comment]
@fual спасибо за отчет! Ссылки починили.
