### ISSUE TITLE
Загрузка зависимых от jquery библиотек.

### ISSUE THREAD

**Issue by AR1ES** [bem/bem-core#1484]
Есть ряд библиотек, которые должны грузиться строго после загрузки jQuery (например jQuery PowerTip), иначе возникает множество ошибок. Каким образом это может быть корректно реализовано средствами БЭМ и YM?

Все что выполняется в теле функции определения (в функции, которая передается в modules.define), т.е. до вызова `provide`, как я понимаю, исполняется до учета зависимостей, т.е. ни о каком порядке речи тут не идет. 

Понятно, что в provide можно вернуть какую-нибудь функцию или объект с функцией `load`, которую вызывать уже при инициализации нужных мне блоков. 

Но может быть есть какие-то более "стандартные" подходы?

**Comment by tadatuta** [comment]
```js
modules.define('my-plugin', ['i-bem-dom', 'jquery'], function(provide, bemDom, $) {

// здесь готовность модуля jquery гарантируется, можно смело его использовать

});
```

Часто при подключении внешних js-библиотек используется такая схема:
1. Ставим библиотеку через `bower` или `npm`
2. Создаем одноименный блок, где подключаем код из библиотеки с помощью `borschik`. Примерно так:
```js
modules.define('jquery', function(provide, jQuery) {
    /*borschik:include:../../libs/fullpage.js/vendors/jquery.easings.min.js*/
    provide(jQuery);
});
```

**Comment by AR1ES** [comment]
Спасибо за информацию.
Изначально пробовал такой способ, однако не заработало. Только сейчас увидел, что jQuery в БЭМ грузится с noConflict и именно по этой причине у меня плагины не инициализировались корректно.

Вопрос снят
