### ISSUE TITLE
Use the classes to search for blocks (v3)

### ISSUE THREAD

**Issue by belozer** [bem/bem-core#1524]
v4 решает проблему с инитом экземпляров блоков при поиске (т.к. в YM явно указана зависимость).
в v3 это не явно из-за чего могут появляться случайные баги, т.к. в YM не всегда указываются зависимости.

В добавок к этому, код становится немного понятней.
`findBlockOn('button', 'button')` vs `findBlockOn('button', Button)`.

У нас на проекте сделал такую возможность через переопределение методов. Кажется хорошим тоном внедрить эту возможность в сам v3, как переходный этап, т.к. не все проекты на тройке могут перейти на четвёрку.

Могу заняться реализацией, если это интересно.

//cc @veged

**Comment by veged** [comment]
нам сильно интереснее, чтобы люди переходили на v4 — полноценно портировать всё в v3  и потом поддерживать в двух версиях очень затратно

**Comment by belozer** [comment]
Нам тоже, но есть продуктовые задачи и не маленькая кодовая база. В v4 много других плюшек. При переходе на v4 можно столкнуться, например, с `circle` зависимостями в ym или отсутствием js реализаций для простых блоков (типа `Icon`). Таким образом можно было бы постепенно адаптировать проект для менее болезненного перехода на v4.

**Comment by veged** [comment]
@belozer тогда вы можете на своём уровне переопределения положить адаптационные бэкпорты из v4 с нужной вам степенью гранулярности

**Comment by belozer** [comment]
@veged так сейчас и есть на проекте. Просто думал, что может кому-то тоже пригодится. Есть вариант вынести это в отдельную "библиотеку".

**Comment by belozer** [comment]
На всякий случай оставлю здесь. Сделали для себя, но может кому-то тоже пригодится.

Гибрид bem-core-3 и bem-core-4 (полный i-bem-dom), для постепенного перетаскивания проекта на 4-ку.
https://github.com/belozer/bem-core/tree/v3-franke
