### ISSUE TITLE
docs: Потеряны стили для класса .article__emphasis

### ISSUE THREAD

**Issue by mashafomasha** [bem/bem-core#1539]
Класс .article__emphasis отображается без стилей, что затрудняет восприятие информации. 
Пример https://ru.bem.info/platform/i-bem/states/#Триггеры-на-установку-модификаторов - в элементах списка строка содержит по 1 слову.

**Comment by godfreyd** [comment]
Спасибо, поправим.

**Comment by godfreyd** [comment]
Поставил задачу https://github.com/bem-site/bem.info/issues/230
