### ISSUE TITLE
Падение при подписке на события window, если на странице есть iframe

### ISSUE THREAD

**Issue by a-lexxx** [bem/bem-core#1542]
Версия bem-core [turbo-rc.1](https://github.com/bem/bem-core/releases/tag/turbo-rc.1)

На странице должно быть более одного **iframe**.

Пример кода
```js
onSetMod: {
    js: {
        inited: function() {
            this._domEvents(window).on('popstate', this._someFunc, this);
        }
    }
}
```
Происходит падение кода, стектрейс:
```text
_main.js:2982 Uncaught DOMException: Blocked a frame with origin "https://localhost" from accessing a cross-origin frame.
    at identify
    at 
    at Object._buildEventManagerParams
    at Object.getEventManager
    at Object._domEvents
    at Object.inited
    at Object.result [as __after__mod_js_inited]
    at Object._callModFn
    at Object.setMod
    at Object._setInitedMod
```

Происходит из-за того, что `window.length > 0` (количество iframe на странице), при построении идентификатора window рассматривается как массив и происходит обращение к iframe.

![photo5222047716853524539](https://user-images.githubusercontent.com/5994727/32945367-23661a26-cba4-11e7-8747-3af966d9a529.jpg)

 // сс @tadatuta

**Comment by boronchiev** [comment]
Тоже наступил на это
