### ISSUE TITLE
https://ru.bem.info/platform/i-bem/events/

### ISSUE THREAD

**Issue by foreheadSniffer** [bem/bem-core#1548]
Куски с кодом поехали
https://ru.bem.info/platform/i-bem/events/

**Comment by qfox** [comment]
Выглядит как включенная опция escapeContent с незавёрнутыми в `{html: ...}` кусками

Вероятно здесь лишний xmlEscape: https://github.com/bem-site/bem.info/blob/ff5390a3d72bdbf5e307c6c8711c5cb3877fb1b9/lib/article.bemhtml.js#L138
Ну или чуть выше не хватает `{html...}`

**Comment by qfox** [comment]
@innabelaya @tadatuta кажется, что изи фикс, если уметь собирать сайт.

**Comment by a-lexxx** [comment]
@tadatuta, я временно откатил на предыдущую версию и там все нормально. Битую я собирал вчера.
