### ISSUE TITLE
Строгий режим для _events()

### ISSUE THREAD

**Issue by belozer** [bem/bem-core#1563]
Сейчас вполне рабочее такое использование

```js
const btn = this.findChildBlock(Button)._events()
    .on('click', this._onBtnClick, this);
```
Что не совсем валидно в плане задуманного использования `_events()`.

Как на счёт того, чтобы добавить предупреждение (или вообще сыпать ошибку) если не задан контекст? Чтобы не порождалось кейсов описанных выше.

Там где эти кейсы явно нужны - делать явное указание аргумента.

```js
this._events(this).on(...);
```

или так

```js
this._events(null).on(...);
```

@veged

**Comment by veged** [comment]
то, что `_events` можно использовать только из самого блока отражено в документации и подчёркивании в названии метода (это приватный метод)

приведённый кусок кода должен выглядеть вот так:
```js
this._events(Button).on('click', this._onBtnClick);
```

**Comment by belozer** [comment]
По этой причине и предложил "строгий режим"

чтобы код выглядел вот так:
```js
this._events(Button).on('click', this._onBtnClick);
```

а не так:
```js
this.findChildBlock(Button)._events().on('click', this._onBtnClick, this);
```

:)

Чтобы не возникало аргументов типо  "ведь и так работает".

**Comment by belozer** [comment]
Но согласен, с тем что во многом виноват сам разработчик.
