### ISSUE TITLE
function: Incorrect `isFunction` behaviour for async functions

### ISSUE THREAD

**Issue by sbmaxx** [bem/bem-core#1575]
```js
modules.define('functions', function(provide) {
var toStr = Object.prototype.toString;
provide({
    isFunction : function(obj) {
        return toStr.call(obj) === '[object Function]';
    },
    noop : function() {}
});
});
```

Для асинхронных функций значение будет — `[object AsyncFunction]`. Это ломает все подписки на события, и наверняка что-то ещё

**Comment by gwer** [comment]
Есть ещё `[object GeneratorFunction]` и `[object Proxy]`. Но проксироваться может не только функция, но и объект.

А `typeof` отдаёт `function` для обычных функций, для асинхронных, для генераторов и для прокси над функцией.
