### ISSUE TITLE
i-bem__dom: Консистентность методов find*

### ISSUE THREAD

**Issue by L0stSoul** [bem/bem-core#158]
В i-bem есть методы вида:

``` js
findBlocksInside : function(elem, block)
findBlockInside : function(elem, block)
```

etc.

вызываются они обычно как-то так: `findBlockInside ('blockName')`
или если нужно найти блок с модификатором: `findBlockInside({ block: 'name', modName: 'mod', modVal: 'val' })`
на выходе получаем первый найденный блок.

Еще есть метод: `findElem : function(ctx, names, modName, modVal, strictMode)`

Который при схожем назначении обладает совсем другой сигнатурой:

`findElem('elemName')` — в ответ получим объект содержащий в себе все элементы такого типа, тоесть казалось бы метод должен называться `findElems`

`findElem('elemName', 'modName', 'modVal')` - при очень схожем назначении  в случае `findBlocks*` передаем объект,  а в этом параметры просто через запятую.

Кажется хороше было бы каким либо образом это унифицировать. 

---

Как вариант было бы удобно если бы все такие методы принимали объект вида `{
b: 'blockName' e: 'elemName', m: { modName: modVal } }` или что то такое, кажется было бы круто подумать в этом направлении.

**Comment by chayn1k** [comment]
:+1:

**Comment by qfox** [comment]
@L0stSoul тогда и одного (или двух-трех) методов будет достаточно.

Например:

``` js
/**
 * find
 * @param {Object|String} search
 * @param {Object} opts
 */
function find (search, opts) {
  if (typeof search === 'string') {
    search = bemNaming.parse(search);
  }

  var outside = Number(opts.scope === 'outside');
  var one = Number(opts.one);

  switch (true) {
    case !search.elem:
      var method = [findBlockInside, findBlockOutside, findBlocksInside, findBlocksOutside][scopeInside * 2 + one];
      result = method(search);
      break;
// etc...
  }

  return result;
}
```

Можно отдельно сделать метод `findOne`.
А вообще, есть еще `elem` кешируемый. Его тоже не стоит забывать.

**Comment by L0stSoul** [comment]
@zxqfox Да мен тоже кажется что пары методов хватит,
но только нужно сделать так чтобы часто используемые кейсы было просто написать

Если пофантазировать как бы это могло бы быть, то я бы предпочел какой нибудь такой синтаксис:

для элементов:

```
this.elems('ololo') // найти элементы взять из кеша - самый частый случай
this.elems('ololo', true) // найти элементы и обновить кэш, из за лени разработчика будет дергаться только когда реально надо.
this.elems('ololo', { smart: 'yes'} ) // найти элементы с таким то модификатором из кэша
this.elems('ololo', { smart: 'yes'}, true) // same но роигнорировать кэш
```

один элемент мне кажется что ненужен - потому что если это осбенный какойто элемент то у него должен быть соответсвующий модификатор

```
block('ololo') // findBlockInside
block('ololo', { smart: 'yes' }) // понятно же ?
block(this.elems('ololo'), 'ololo', { smart: 'yes' }) // и тут тоже понятно
```

соответсвенно тоже самое но для нескольких блоков.:

```
blocks('ololo') // остальное тоже самое
...
```

А  findBlockOutside кажется лучше переименовать во что-нибудь типа:- 

```
parentBlock(ololo) // остальное тоже самое
```

потому что он всеравно ищет вверх только по дереву соотвественно парентов.

**Comment by qfox** [comment]
@L0stSoul в целом, ок.
подозреваю, что с parent/parents можно взять опыт jq:

``` js
closest(filter); // ближайший из парентов, проходящий фильтр
parent(); // непосредственный родитель, врядли нужно
parents(); // все родительские блоки (?)
```

**Comment by qfox** [comment]
Актуально? #581

**Comment by L0stSoul** [comment]
Думаю что нет :) крутяк!
