### ISSUE TITLE
magic: command not found

### ISSUE THREAD

**Issue by Realetive** [bem/bem-core#1598]
Any commands of `npm run *` with `magic` return fail.

**Comment by qfox** [comment]
it's enb magic platform

**Comment by Realetive** [comment]
@zxqfox and how to resolve it? Need additional devDeps?

**Comment by qfox** [comment]
yes probably

**Comment by Realetive** [comment]
@zxqfox but where I can find source of this package?

**Comment by tadatuta** [comment]
@Realetive just checked it on clean installation of `v4`.
`npm run test-tmpl` works fine for me:

```
npm run test-tmpl

> bem-core@4.3.1 test-tmpl /Users/tadatuta/projects/bem/bem-core
> magic run tmpl-specs

13:53:14.472 - build started
13:53:14.543 - [rebuild] [desktop.tmpl-specs/i18n/i18n.base.bemdecl.js] file-provider
...
```

**Comment by Realetive** [comment]
Hm. Yes, now it's all right. (may be reason is that I used `pnpm` instead `npm`).
