### ISSUE TITLE
i-bem: Консистентность методов *Mod и find*

### ISSUE THREAD

**Issue by L0stSoul** [bem/bem-core#160]
Есть пачка методов:
setMod : function(elem, modName, modVal),
delMod : function(elem, modName),
toggleMod : function(elem, modName, modVal1, modVal2, condition)
etc.

и другая пачка:
findBlocksInside : function(elem, block)
findBlockInside : function(elem, block)
etc.

Первые в аргумент elem, принимают только jquery, вторым можно передовать туда и имя, и jquery. Кажется что лучше привести это к единому виду.

+методы вида *Mod лежат https://github.com/bem/bem-core/blob/v1/common.blocks/i-bem/i-bem.vanilla.js, который заявлен как vanilla. И странно что они ожидают jquery объект. Де-юро кажется все в порядке, но де-факто это странно :)

**Comment by dfilatov** [comment]
А где в i-bem.vanilla.js написано, что  *Mod в аргументе elem принимает jquery?

**Comment by L0stSoul** [comment]
мне показалось что используется он в таком контексте,  elem[0] в коде как бы намекает, я не прав?

**Comment by dfilatov** [comment]
Ну это костыль небольшой. Но это внутренняя вещь, наружу оно никак не торчит.

**Comment by L0stSoul** [comment]
Просто кажется от него можно избавиться примерно так же как это сделанно в _extractModVal, тоесть доопределить уже в i-bem__dom. 

> Пока искал это нашел еще одну странность - без i-bem__dom setMod работает, а getMod кажется работать не будет потому что в любом случае он использует _extractModVal который в i-bem определенн вот так     _extractModVal : function(modName, elem) { return ''; }

А нет ошибся сори, через modCache все работает.

а вообще в любом случае основной посыл issue несовсем про это :)

**Comment by qfox** [comment]
Не правильнее `*mod` унести в `Block`/`Elem`?
Про `find*` — можно тоже в `Block`/`Elem` определить и пробрасывать их до `i-bem-dom` с установкой ctx.

Btw. Актуально? #581

**Comment by veged** [comment]
в v3 проблема больше не актуальна
