### ISSUE TITLE
i-bem__dom bindTo и jquery  on

### ISSUE THREAD

**Issue by L0stSoul** [bem/bem-core#161]
Кажется что было бы курто, если бы внутри bindTo, и соответственно bindToDomElem заменили бы $.bind на $.on

Преимущество on  в том что он будет работать даже для пока не созданных элементов, что, при все чаще встречающейся шаблонизации на клиенте, очень удобно.

У нас конечно есть live события, но их минус в том, что они собранны в отдельной секции, и я не могу их использовать также просто как bindTo, тоесть просто заменить по коду bindTo на liveBindTo не получится (а возможно и не сработает).

**Comment by L0stSoul** [comment]
ping ping.

**Comment by dfilatov** [comment]
@L0stSoul we're on way to the new event system in v3, see #394

**Comment by L0stSoul** [comment]
thx, i check it out
