### ISSUE TITLE
BEMHTML: Support for modifiers with boolean values

### ISSUE THREAD

**Issue by veged** [bem/bem-core#169]
We already can use `block_mod` everywhere except i-bem.js (#168) and BEMHTML (#169).

**Comment by narqo** [comment]
@veged @dfilatov 

А в `deps.js`, запись для таких модификаторов будет 

```
{ bloc: 'b1', elem: 'e1', mod: 'm1' }
```

?

**Comment by veged** [comment]
äà, ýòî âñåãäà áûëî âîçìîæíûì
