### ISSUE TITLE
BEMHTML: Support for subpredicates about modifiers with boolean values

### ISSUE THREAD

**Issue by veged** [bem/bem-core#179]
Right now if we write `block my-block, mod my-mod true` it's treated as `this.mods['my-mod'] === 'true'`. In case of modifiers with boolean values (#169) we need special cases for `true`/`false` values of modifiers in subpredicates `mod`/`elemMod`:
- `block my-block, mod my-mod true` -> `this.mods['my-mod'] === true`
- `block my-block, elem my-elem, elemMod my-mod false` -> `this.elemMods['my-mod'] === false`
- and so on

**Comment by indutny** [comment]
Fixed in https://github.com/bem/bemhtml-compat/commit/30c1ff62f0068336adcda13e32215c71ab8c815b.
