### ISSUE TITLE
Технология deps с расширением на основе технологии *js

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-core#18]

**Comment by arikon** [comment]
О чём эта задача?

**Comment by dfilatov** [comment]
О склеивании зависимостей из dep.js и modules, чтобы не было необходимости дублировать одно и тоже в js и в deps.js

**Comment by arikon** [comment]
О, это хорошая идея!

**Comment by veged** [comment]
в текущей реальности в такой постановке — wontfix
