### ISSUE TITLE
Migration guide from `bem-bl` to `bem-core@1.0.0`

### ISSUE THREAD

**Issue by veged** [bem/bem-core#25]

**Comment by arikon** [comment]
Дима @dfilatov описал миграцию для js. Нужно написать, как в целом смигрировать с `bem-bl` на `bem-core`.
Кто это может описать?

**Comment by veged** [comment]
можно использовать https://github.com/bem/project-stub/compare/master...bem-core как план

**Comment by dfilatov** [comment]
there are no such users who really "migrate" and have necessity in those docs
