### ISSUE TITLE
page__css: rethink about bemjson API in case of IE

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-core#281]
Right now:

``` js
{ elem : 'css', url : '_30-css-ie.css', ie : false },
{ elem : 'css', url : '_30-css-ie', ie : true }
```

**Comment by tadatuta** [comment]
I think we don't need `ie : true` shortcut anymore as there's almost no IE6 and IE7, IE9 will disappear soon and newer IEs don't understand conditional comments.

so there will be just one common `ie.css` or `ie8.css` + `ie9.css` which is easy to handle manually.
