### ISSUE TITLE
Rethink about techdocs

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#287]
There was an idea of having documentation to each tech of each block inside of `block-name.techdoc/tech-name/article-name/article-name.md`

**Comment by tadatuta** [comment]
// cc @veged if it's ok for you I'll move articles from `common.docs`

**Comment by veged** [comment]
what about docs that not fit in terms/context of one particular block (bem-item)?

**Comment by veged** [comment]
also, I want to remember, `*.techdocS` should be configured as layer with special naming

**Comment by veged** [comment]
@tadatuta do we still need it?

**Comment by tadatuta** [comment]
@veged would be nice to have but seems like we'll never find the time to implement
