### ISSUE TITLE
Documentation about js-syntax for BEMHTML

### ISSUE THREAD

**Issue by veged** [bem/bem-core#30]

**Comment by arikon** [comment]
See issues bem/bem-bl#333, veged/xjst#18

**Comment by arikon** [comment]
https://github.yandex-team.ru/gist/569

**Comment by arikon** [comment]
Много примеров в тестах на `bem-xjst`
https://github.com/bem/bem-xjst/blob/master/test/api-test.js

**Comment by narqo** [comment]
@arikon gh.yt?

**Comment by veged** [comment]
Т.к. технология bemhtml обратносовместима со старым синтаксисом, считаю, что эта задача не обязательна к версии 1.0.

**Comment by tadatuta** [comment]
Russian is ready: https://github.com/bem/bem-core/blob/v1/common.docs/bemhtml-js-syntax/bemhtml-js-syntax.ru.md

Translation required.
