### ISSUE TITLE
i-bem__dom: get rid of $.proxy

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#302]

**Comment by dfilatov** [comment]
Why?

**Comment by tadatuta** [comment]
There's just one use case of `$.proxy` in https://github.com/bem/bem-core/blob/v1/common.blocks/i-bem/__dom/i-bem__dom.js#L374 and as some users in the club ask about the way to switch from JQuery to some other libraries I decided that we can use `bind` from `ecma__function` instead of it.

But feel free to close the issue if it makes some potential harm.

**Comment by dfilatov** [comment]
The `$.proxy` is not the same thing as `bind`. You can't later unbind original function in case of `bind`.
