### ISSUE TITLE
Remove `clearfix` block

### ISSUE THREAD

**Issue by mishanga** [bem/bem-core#304]

**Comment by dfilatov** [comment]
Why do we need remove it? Where should this block be?

**Comment by mishanga** [comment]
`clearfix` is just simple and trivial css-hack which is not needed in core library.
It's also not used in `bem-components` and already placed in `islands-page`.

**Comment by mishanga** [comment]
And yes, it's only about view.

**Comment by tadatuta** [comment]
It's not used in `bem-components` but you can hardly build any project without `clearfix`.
And as `islands-page` is internal library we need to have it somewhere outside.

**Comment by mishanga** [comment]
OK, let's create yet another library — `bem-stuff`.

**Comment by mishanga** [comment]
@veged @dfilatov are we all agree to move `clearfix` to `bem-components`?

**Comment by dfilatov** [comment]
I don't want to make from `bem-components` a "trash box" for all blocks which we don't know to put to.

**Comment by mishanga** [comment]
OK :)

**Comment by dfilatov** [comment]
But also i think `bem-core` isn't suitable place for this block too )

**Comment by veged** [comment]
@mishanga @dfilatov guys, we three already considered this as "temporary" state, as long we have't enough blocks for other library (between bem-core and bem-componentn)
