### ISSUE TITLE
IE10 pointerevent problem 

### ISSUE THREAD

**Issue by fi11** [bem/bem-core#313]
IE 10 при каждом движении мышки ругается вот на эту строчку https://github.com/bem/bem-core/blob/v1/common.blocks/jquery/__event/_type/jquery__event_type_pointer.js#L226

SCRIPT5007: Не удалось получить свойство "clientX" ссылки, значение которой не определено или является NULL

**Comment by dfilatov** [comment]
@deepsweet, посмотришь?

**Comment by deepsweet** [comment]
я завтра как раз перепроверю новую версию в IE10 перед вливанием, там
многое переписано.

**Comment by dfilatov** [comment]
Кир, ну как там?

**Comment by deepsweet** [comment]
разработку я уже давно веду в отдельном репозитории https://github.com/deepsweet/jquery-pointerevents
конкретно эта проблема уже решена, но есть новая.
в текущем виде прямо сегодня сделать PR нельзя.

**Comment by veged** [comment]
close in favour of #354
