### ISSUE TITLE
Концепт асинхронного API для bem-xjst

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#314]
cc @indutny @veged @dfilatov 

Насмотревшись на всякие [генераторы](https://medium.com/code-adventures/174f1fe66127), [tamejs](https://github.com/maxtaco/tamejs), [IcedCoffeeScript](http://maxtaco.github.io/coffee-script/) и пр. [asjs](https://github.com/omgtehlion/asjs) появилась идея попробовать поддержать всю эту асинхронщину на уровне компилятора и добавить к уже имеющимся `block()`, `elem()`, `mod()` и пр. `apply()` две функции 
- `async(cb)` — эдакай [co](https://github.com/visionmedia/co) (generator-based control-flow coroutines? :D);
- `await(val)` — аналог `yield` в генераторах.

Гипотетический пример такого API: https://gist.github.com/narqo/bf7debec89a760e6b007

Все это могло бы на уровне компиллятора генерироваться в обычный промис или цепочку колбеков.

**Comment by veged** [comment]
практика показывает, что это не особо актуально
