### ISSUE TITLE
i-bem.js, i-bem__dom.js: Remove all deprecated methods

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-core#318]
cc @veged 

When will we can remove them?
What is our policy about?

**Comment by veged** [comment]
we have no policy yet — here is an issue https://github.com/bem/bem-core/issues/45

**Comment by apsavin** [comment]
I don't know, what will be in the policy, but I think, difference between bem-core and bem-bl is big enough to just remove all deprecated methods right now)

**Comment by veged** [comment]
@apsavin we can't do it right now, because we already release current state as 1.0.0 version and must follow what-any intuitive compatibility policy — so we can do it in 2.0.0 (which can come soon, as we discussed with @dfilatov)
