### ISSUE TITLE
Что насчёт возможности узнать, что dom-элемент блока удалён?

### ISSUE THREAD

**Issue by apsavin** [bem/bem-core#331]
Раньше был метод `destruct`. Можно было вызвать `block.destruct()` - и блок удалялся вместе со своим элементом. Этот метод можно было доопределить и добавить какие-то действия после вызова `this.__base()`, то есть уже после того, как блок удалён. Это было удобно.

Сейчас есть деструктор (callback на удаление модификатора `js`), который вызывается при удалении блока. Это не так удобно, потому что нет возможности что-то сделать, когда удалён dom-элемент.

Разумеется, ожидаются возражения, что можно использовать `next-tick` в деструкторе, чтобы совершать действия после того, как dom-элемент будет удалён. Однако, мне кажется, что если мы можем точно узнать, когда совершать какое-либо действие (а это именно такой случай), не стоит использовать `next-tick`.

Попробую привести пример использования. Предположим, у нас есть блок `А`, в него вложены блоки `Б`. Высота блока `А` меняется при удалении или добавлении блоков `Б`, блоки `Б` разной высоты. Сейчас мы не сможем бросить из блока `Б` событие при удалении, чтобы блок `А`  вывел свою новую высоту в консоль, не используя `next-tick`.

Может быть, я не прав и не вижу чего-то очевидного?

**Comment by dfilatov** [comment]
Ну, конкретно в приведенном примере, в колбэке на удаление модификатора у блока `B` можно кидать событие, которое будет слушать `A`. Причем будет слушать все события вложенных блоков `B` (их же может и несколько за раз удалятся, а пересчитать итоговую высоту лучше один раз) и, потом, уже в каком-нибудь `requestAnimationFrame` что-нибудь сделать (перерисоваться?) с новой высотой.

**Comment by apsavin** [comment]
Ок, `next-tick`, согласен. Ладно, реалистичного примера у меня нет, наверное, всё в порядке.
