### ISSUE TITLE
Release bem-core@1.1.0

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#334]
\cc @dfilatov @veged 

It seems that there are enough changes was made [since 1.0 release](https://github.com/bem/bem-core/compare/v1.0.0...v1). Guess we could move to next minor version.

Plan:
- [x] Update CHANGELOG
- [ ] <del>Write the migration guide</del>

**Comment by veged** [comment]
"yes, we can" ©

we need to found proper sections in changelog and other docs
