### ISSUE TITLE
bem-core roadmap

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#35]
\cc @veged @arikon 

Нужно набросать примерный roadmap на проект (отдельным документом), чтобы было понятно, когда планируется отрывать **DEPRECATED**-методы и на который потом, можно будет ссылаться для обоснования тех или иных решений.

**Comment by veged** [comment]
в каких терминах описывать планы? время тяжело предугадать, а номера версий малополезны

**Comment by narqo** [comment]
Как раз на оборот: какой смысл начинать что-то переделывать в своем коде, если deprecated-методы продолжают работать и скорее всего будут работать неопределенное время?

**Comment by narqo** [comment]
Немного раскрою мысль: под roadmap'ом я понимаю хотя бы примерное описание того, куда планируется расти библиотеке. Что означает, что часть методов объявлена как DEPRECATED? Как это аффектит сферического разработчика? Если ли вообще какие-то планы или это «еще один БЭМ-выкидыш, который заморозится через пол года»?

Пример правильного подхода, IMHO: https://docs.djangoproject.com/en/1.5/internals/deprecation/

**Comment by veged** [comment]
понял

но я бы тогда отдельно рассматривал тикет на deprecation policy (тут всё понятно, да можно в терминах версий сформулировать сколько минорных/мажёрных что живёт) и тикет на описание каких-то планов (тут сложнее, как обычно с планами, но общую идею, что мы не хотим "выкидышей" донести можно)

**Comment by qfox** [comment]
Планы не сложно — создаем майлстоуны, и вяжем туда issue. Если что-то сдвигается — ничего страшного, все эти путевые столбы очень условны и относительны. Но хотя бы будет понятно что за чем следует — этого достаточно, чтобы понять планы. profit.

> еще один БЭМ-выкидыш

ой ли. а че сразу выкидыш? просто недоношенный.

**Comment by narqo** [comment]
Вроде, за 9 месяцев, тема с milestone'ами вполе работает.
