### ISSUE TITLE
i-bem: Use boolean modifiers for `i-bem_elem-instances_yes` and `i-bem__dom_elem-instances_yes`

### ISSUE THREAD

**Issue by veged** [bem/bem-core#352]
cc @aristov

**Comment by narqo** [comment]
@aristov ping!

**Comment by aristov** [comment]
Что именно нужно сделать?

**Comment by veged** [comment]
по сути, только переименовать файлы и внутри вместо `'yes'` использовать `true`

**Comment by aristov** [comment]
https://github.com/bem/bem-core/pull/430

**Comment by veged** [comment]
смёржил в v1 — осталось отребейзить v2 по v1 (сделаем как-нить махом для всего)

**Comment by mishanga** [comment]
> смёржил в v1 — осталось отребейзить v2 по v1

@veged Ты правда собираешься ребейзить публичную ветку? :)
Наверное, лучше  подмержить v1 в v2, чтобы приехали недостающие коммиты.

**Comment by veged** [comment]
она ещё не публичная, а "в разработке"

**Comment by mishanga** [comment]
@veged публичная не с точки зрения пользователей, а с точки зрения разработчиков. Если больше одного человека коммитят в одну ветку — она публичная. Кроме того, пул-реквесты "поедут", будут ссылаться на несуществующие коммиты.
