### ISSUE TITLE
Модуль data-provider

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#37]
\cc @dfilatov @veged 

Хочу портировать `i-request` (и соответственно, его `_type_ajax`)  в bem-core. Но меня смущает название. `request` неоднозначно описывает, зачем этот блок (по крайней мере в технологии `node.js`). 

Предлагаю назвать блок `data-provider` и реализовать там базовый интерфейс. Потом от него наследовать `http-provider` (для AJAX и HTTP -запросов в `browser.js` и `node.js` соответственно).

Потом можно реализовывать `file-provider` и пр. 

Что скажите?

**Comment by dfilatov** [comment]
С помощью этого блока ведь делаются не только запросы за данными, но и, например, POST каких-то данных. Тогда название data-provider звучит еще страннее i-request.

**Comment by narqo** [comment]
Может назвать базовый блок `io-provider` (провайдит API для работы с input/output)? А POST и пр. CRUD реализовывать в `http-provider`е

**Comment by veged** [comment]
@narqo почему не нравится `request`? ;-)

**Comment by dfilatov** [comment]
А точно нам нужен этот суперабстрактный `io`, `request` и т.п.?
Я к тому, что именно провайдер данных может иметь абстрактный интерфейс, а вот input-output в целом хз.

**Comment by narqo** [comment]
@veged мне не нравится, что на сервер-сайде, под реквестом можно подразумевать (в зависимости от контекста): объект пришедший от «пользователя» на сервер, либо метод для отправки (HTTP-)запросов.

@dfilatov кажется, можно обойтись http/fs -provider'ами, просто реализовав в них примерно одинаковое API, ты об этом?

**Comment by dfilatov** [comment]
Я имел ввиду что провайдеры данных и низкоуровневные апи для работы с http, file, ... -- это, на мой взгяд разные вещи.

**Comment by fi11** [comment]
Умоляю оставьте название request :)

**Comment by varya** [comment]
Мои 5 копеек: мне `request` (или как вы его назовете) нужен, чтобы заниматься кешированием.

**Comment by qfox** [comment]
@narqo Если сделать API, описывающее запрос/ответ — то нет проблем реализовать его в browser.js и node.js отдельно.
