### ISSUE TITLE
Rethink the way to include external libs

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#387]
Right now we have some external libs in `bem-core`, e.g. `vow`.

I think we could use `bower` to get them into `libs` folder and then `borschik` or simple symlinks to put them into `blocks`.

// сс @veged @narqo

**Comment by narqo** [comment]
But were this (sym/borschik)-link will point after `bem-core` will become someone's dependence?

```
my-lib/
  libs/
    bem-core/
      blocks/
        vow  →  ../libs/vow  // ☚ Ooops! bem-core's libs aren't there anymore. They're my-lib's dependencies now
    vow/
```

**Comment by tadatuta** [comment]
@narqo We should have possibility for custom build of libraries on post install.
For example for `roo` to `css` conversion, apply `autoprefixer` and so on.
And install dependencies as a part of such post installation process.

**Comment by narqo** [comment]
> We should have possibility for custom build of libraries on post install [..]

@tadatuta How does it connect with issue's description about `Vow` block and `bower`?

**Comment by veged** [comment]
there is not so many externals libs and seems like the problem is not that relevant
