### ISSUE TITLE
i-bem-js.*.md: Add docs about `baseMix`

### ISSUE THREAD

**Issue by veged** [bem/bem-core#389]
Some details in issue https://github.com/bem/bem-bl/issues/255

**Comment by dfilatov** [comment]
@maslinych ping

**Comment by innabelaya** [comment]
The `baseMix` described in https://github.com/bem/bem-core/blob/v2/common.docs/i-bem-js/i-bem-js.ru.md#%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0-%D0%BC%D0%B8%D0%BA%D1%81%D0%B0-%D0%B2-%D0%B4%D0%B5%D0%BA%D0%BB%D0%B0%D1%80%D0%B0%D1%86%D0%B8%D0%B8.
I will update the examples.

**Comment by innabelaya** [comment]
существующий пример обновлен: https://github.com/bem/bem-core/pull/972
