### ISSUE TITLE
Fix browser-js+bemhtml tech

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#392]
`browser.js+bemhtml` has three suffixes to build: `js` + `vanilla.js` + `browser.js` and when any of declared blocks are changed but none of `bemhtml` blocks changed the result for `bemhtml`-tech created inside of `browser.js+bemhtml` will be empty and so bundleName.js will consist of just concatenated *.{vanilla.js, js, browser.js} and no bemhtml code at all.

**Comment by dfilatov** [comment]
could you describe this fix?

**Comment by tadatuta** [comment]
@dfilatov updated description

**Comment by veged** [comment]
doesn't it gonna rebuild `bemhtml` always, even if it's not actually needed?

**Comment by veged** [comment]
considering as ugly hack for https://github.com/bem/bem-core/issues/392
