### ISSUE TITLE
i-bem-js.ru.md: Update for v2

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-core#395]
- [x] #382
- [x] #357

**Comment by dfilatov** [comment]
@maslinych ping

**Comment by maslinych** [comment]
@Murdalay Сергей, задокументируй это, пожалуйста.

**Comment by veged** [comment]
ping! anybody gonna do this? ;-) we already have users who write outdated code by current docs :-(

**Comment by tadatuta** [comment]
@veged, we'll plan it right after cleanup on `bem-components` documentation.
