### ISSUE TITLE
Split responsibility i-bem, i-bem__dom

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-core#413]
I suggest to split current `i-bem` and `i-bem__dom` modules into following ones with clear responsibilities (instead of current mess with classes, declaration, constants and bulk operations): 
- `(i-)?bem` -- facade for operations with bem-blocks. It contains `decl` and `create` methods.
- `(i-)?bem__block` -- base bem-block. It shouldn't be used directly.
- `(i-)?bem-dom` -- facade for bemdom-blocks. It contains `decl`, `init`, `destruct`, `update`, `before`, `after`, etc. and some fields like `scope`, `win`, `doc`).
- `(i-)?bem-dom__block` -- base bemdom-block. It's inherited from `bem__block` and shouldn't be used directly as well.

**Comment by dfilatov** [comment]
@veged @narqo 
Could you provide your opinions about that?

**Comment by veged** [comment]
I pfrefer discuss offline about such complex things ;-)

**Comment by qfox** [comment]
Seems like it should be closed since #580 was merged to v3
