### ISSUE TITLE
Keyboard helpers

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#431]
Think about separate module with common key codes, like enter, arrow keys, etc

**Comment by tadatuta** [comment]
duplicate for https://github.com/bem/bem-core/issues/360 ?

**Comment by narqo** [comment]
@tadatuta we decided that this modules should has a little bit different usage. 

This one is about constants like `KB_ENTER`, that we've already copy-pasted in some of bem-componet's modules. #360 is about custom events (behaviour) for common keyboard shortcuts.
