### ISSUE TITLE
Deprecation policy

### ISSUE THREAD

**Issue by arikon** [bem/bem-core#45]
Add deprecation policy document that will describe how features are maintained, deprecated and deleted.

Start of the discussion #35

**Comment by arikon** [comment]
/cc @veged @narqo 

Кто сформулирует deprecation policy?

**Comment by narqo** [comment]
@arikon @veged 
я могу выступить секретарем и записать со слов

**Comment by veged** [comment]
be honest — we can't find time for this :-(

**Comment by arikon** [comment]
@veged So how you decide what to deprecate and when to delete?

**Comment by qfox** [comment]
@arikon @veged why not to use semver? deprecation in minor version, removing in major. simple.
