### ISSUE TITLE
 define BEMDOM-blocks as ym in v2.0.0

### ISSUE THREAD

**Issue by fi11** [bem/bem-core#451]
Возможность определять блоки как модули не попала в v2.0.0  https://github.com/bem/bem-core/blob/v2.0.0/common.blocks/i-bem/__dom/i-bem__dom.js#L1418

**Comment by narqo** [comment]
Уточни, что значит «не попала»? С bem-core@2.0.0 можно писать так

``` js
modules.define('block', ['i-bem__dom'], function(provide, BEMDOM) {

provide(BEMDOM.decl(this.name, {
    onSetMod : {
        // ...
    }
});

});
```

Пример: https://github.com/narqo/bem-game-go/blob/master/blocks/board/board.js (в проекте стоит явная зависимость от `v2.0.0`)

**Comment by fi11** [comment]
Я вот про это https://github.com/bem/bem-core/issues/382 или от такого способа отказались ? Тогда, по чейнджлогу не совсем понятно, как именно теперь можно декларировать блоки.

**Comment by narqo** [comment]
В #382 обновили описание — добавили ссылку на PR, в котором делали финальный вариант. Там есть описание как правильно.
