### ISSUE TITLE
page.bemhtml head after styles

### ISSUE THREAD

**Issue by 4ok** [bem/bem-core#458]
Сейчас в page.bemhtml есть код отвечающий за отрисовку данных в элементе head:

{
    elem : 'head',
    content : [
        { tag : 'meta', attrs : { charset : 'utf-8' } },
        { tag : 'title', content : ctx.title },
        { block : 'ua' },
        ctx.styles,
        ctx.head,
        ctx.favicon? { elem : 'favicon', url : ctx.favicon } : ''
    ]
}

тут ctx.styles стоят перед ctx.head и если я в массив head добавляю новый элемент < base url="..." /> то стили игнорируют базовый урл и соответственно не подгружаются, я думаю ctx.head и ctx.styles надо поменять тут местами

**Comment by 4ok** [comment]
Может что-то непонятно из описанного?

**Comment by narqo** [comment]
Можно пример BEMJSON с которым не работает и пример того, что должно получиться? Пока не очень понятно

**Comment by tadatuta** [comment]
@narqo если я правильно понял, то речь о том, что при

``` javascript
head: [
        { tag: 'base', attrs: { href: 'http://mysite.ru' } }
    ],
    styles: [
        { elem: 'css', url: '_index.css' }
    ]
```

путь до `_index.css` проигнорирует `base`.

**Comment by tadatuta** [comment]
https://github.com/bem/bem-core/pull/465
