### ISSUE TITLE
Feedback for "Миграция"

### ISSUE THREAD

**Issue by steve-reichbach** [bem/bem-core#462]
_unbindFromTick : function() {
        tick.un('tick', this._onTick, this);
    }, .....

должно быть наверное так 
 _unbindFromTick : function() {
        tick.on('tick', this._onTick, this);
    },

**Comment by narqo** [comment]
В `_unbindFromTick` мы **отписываемся** от событий модуля `tick`. Вроде все правильно.

**Comment by steve-reichbach** [comment]
сорри, все корректно :)
Не нашел документации про то, как тригерить события в каналах - только то, как их по-новому подключать.

Запись вида 

```
channels('state').trigger('change', { state: 'static' }); 
```

выдает 

```
Object [object Object] has no method 'trigger' .
```

Вывел канал, а там и правда есть другие методы 

```
on, emit, once un
```

Может я не так понимаю, но как быть с кастомными событиями?

**Comment by dfilatov** [comment]
``` js
channels('state').emit('change', { state: 'static' }); 
```
