### ISSUE TITLE
Нельзя указать для js элемента блока page условные комментарии для IE

### ISSUE THREAD

**Issue by 4ok** [bem/bem-core#463]
Для css это можно сделать, а как быть когда нужно подключить скрипт только для IE  - например html5.js

**Comment by narqo** [comment]
Всегда можно написать «руками», как описано в таске https://github.com/bem/bem-core/issues/230 ;)

**Comment by 4ok** [comment]
Конечно можно, но зачем тогда добавлено для css, ведь "руками можно", по мне это всеже не доработка или тогда убирайте для css и советуйте писать условные комментарии руками

**Comment by narqo** [comment]
> по мне это всеже не доработка или тогда убирайте для css и советуйте писать условные комментарии руками

Мы уже решили отрывать поддержку ie_cc из BEMHTML-шаблона, но это будет делаться в рамках работы над `v3` в будущем. См. #379 + #437

**Comment by qfox** [comment]
Since we have #511...

Can we close this?

**Comment by veged** [comment]
@zxqfox yeah, looks like
@4ok reopen if any
