### ISSUE TITLE
i-bem.bemtree: position field in context

### ISSUE THREAD

**Issue by Murdalay** [bem/bem-core#470]
Вегед попросил повесить ишу про `position` в BEMTREE. 

Сейчас такого поля контекста нет. 

Нужно впилить, или объяснить почему оно там не нужно))

**Comment by dfilatov** [comment]
Let's move all discussion about BEMTREE and BEMHTML to https://github.com/bem/bem-xjst/issues

**Comment by dfilatov** [comment]
Moved to https://github.com/bem/bem-xjst/issues/140
