### ISSUE TITLE
Publish generated jsdocs after main branches were updated

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#477]

**Comment by tadatuta** [comment]
@narqo а точно нужно коммитить автогенеренные файлы в ветку с сорцами?

**Comment by tadatuta** [comment]
увидел, что коммитится в отдельную ветку. тогда заголовок не соответствует?

**Comment by narqo** [comment]
@tadatuta имелось ввиду делать «publish» генерированных jsdoc'ов по пушу в основных ветка: влили что-то в `v2` — запустить сборку jsdoc и опубликовать.
