### ISSUE TITLE
i-bem.bemhtml: Add ability to modify context prototype

### ISSUE THREAD

**Issue by veged** [bem/bem-core#483]
We need possibility to modify `BEMContext` in user templates `oninit`. Looks like we can just add `exports.BEMContext = BEMContext` to https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L257.

**Comment by indutny** [comment]
I think it'd be better to export it to `oninit`'s context instead of public-for-all `exports`, see https://github.com/bem/bem-core/pull/485

**Comment by veged** [comment]
ok
close in favour #485
