### ISSUE TITLE
i-bem__dom_init_auto: Make async call because of rendering performance

### ISSUE THREAD

**Issue by veged** [bem/bem-core#486]
Client-side performance research in of our `web3` (in compare to `web1`) revealed interesting issues. In some browsers (at least webkit-based) binding of some heavy js-functionality to dom-ready event cause decelerations of rendering process. We compare `$(function() { init() })` with `$(function() { setTimeout(function() { init() }, 0)` and catch ~30% difference in rendering time.

Need port to `bem-bl`.

**Comment by dfilatov** [comment]
Could you provide detailed information about that?

**Comment by veged** [comment]
@dfilatov I slightly update description. Still need to discuss offline.

**Comment by L0stSoul** [comment]
I'm interested in this too. how do you measured this? may be it's just mask rendering problem?
it's sounds quite strange>

**Comment by veged** [comment]
@L0stSoul you can talk with @gfranco for more details

**Comment by L0stSoul** [comment]
yeah already talked, thank you! it's really interesting issue.
