### ISSUE TITLE
Magic undocumented param in i-bem__dom

### ISSUE THREAD

**Issue by delfrrr** [bem/bem-core#487]
if you add `id` in js params

```
[
    {
        block: 'example',
        js: {
            id: 'zzz',
            info: 'instance-1'
        } 
    },
    {
        block: 'example',
        js: {
            id: 'zzz',
            info: 'instance-2'
        } 
    }
]
```

only one(!) block instance will be inited
https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/__dom/i-bem__dom.js#L141
# спасибозапотеряныйвечер

**Comment by narqo** [comment]
этонебагафича™

[Один JS-блок на нескольких HTML-элементах](http://ru.bem.info/libs/bem-core/1.0.0/i-bem-js/i-bem-js/#один-js-блок-на-нескольких-html-элементах)

**Comment by delfrrr** [comment]
![image](https://cloud.githubusercontent.com/assets/495642/2608337/74683de0-bb69-11e3-9b85-8577f1324e2f.png)

**Comment by delfrrr** [comment]
Как минимум это полохо потому что это замусоривает неймспейс в котором хранятся параметры блока.
Еще я думаю что ооочень мало кто об этом знает, так ранее фича все таки была недокументирована.

**Comment by delfrrr** [comment]
А где написано что аналогичные последствия будут от параметра `uniqId`?

**Comment by narqo** [comment]
В Лего за счет этого работает `b-tabbed-pane` где-то с версии 2.6. Про это даже на мастер-классе на YaC'е рассказывали несколько лет назад (и еще много где) — это к вопросу, что мало кто знает. Скорее мало кто пользуется :)

> А где написано что аналогичные последствия будут от параметра uniqId?

`uniqId` — это как раз недокументированная внутренняя штука. Кое где используется как «хак», чтобы связать куски DOM'а, появившиеся в разных «волнах инициализации». 

Но использовать это, @dfilatov очень не рекомендовал. Оно может привести (как показывает опыт) к неожиданному поведению. Например, не всегда однозначно понятно как синхронизировать модификаторы или как удалять такие «куски DOM'а» при destruct'е.

**Comment by delfrrr** [comment]
Итого две проблемы
- замусоривает неймспейс в котором хранятся параметры блока
- недокументированое поведение при параметре `uniqId`

**Comment by dfilatov** [comment]
- Параметр `id` был всегда зарезервирован, это было написано во всех мануалах
- Этого больше не будет

**Comment by qfox** [comment]
@veged @dfilatov Guys, это же docs, да?

**Comment by veged** [comment]
уже задокументировано http://ru.bem.info/libs/bem-core/v2.5.1/desktop/i-bem/docs/#Один-js-блок-на-нескольких-html-элементах
