### ISSUE TITLE
dom: Add isDisablable method

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#488]
As like `dom.isFocusable`, `isDisablable` should return whether given object could have `disabled` attribute

**Comment by narqo** [comment]
According to [(some) specs](http://msdn.microsoft.com/en-us/library/ie/ms533732%28v=vs.85%29.aspx) there is no a concrete set of elements on which "disabled" attribute could be applied. 

IMHO this kind of API is useless for bem/bem-components#308. We could set/unset "disabled" attribute for **every** `__control` whether it is `<input>` or `<span>`.

@dfilatov what do you think about it?

**Comment by dfilatov** [comment]
I think if we can safely add that attribute to any controls we should do it.
