### ISSUE TITLE
Update bem-xjst to 0.8.x

### ISSUE THREAD

**Issue by veged** [bem/bem-core#491]
At least need to fix `applyNext` problems.

**Comment by narqo** [comment]
It introduces some backwards incapable features, so some of our own templates from `bem-components` breaks. In my opinion this must be a part of **major** update, not `v2`.

**Comment by veged** [comment]
what features are you talking about? which templates are broken?

**Comment by narqo** [comment]
At least icon's template is broken: https://github.com/bem/bem-components/blob/v2/common.blocks/icon/icon.bemhtml

P.S. I know that this kind of declaration is forbidden since 0.6.x now. But I don't think that we could make this kind of changes in the minor release

**Comment by veged** [comment]
hmm... we need this version bump for better examples in new-coming documentation... maybe we can release v3? ;-)

**Comment by tadatuta** [comment]
I asked @Murdalay to leave documentation as is for current version 'cos we need to publish it on bem.info before BEMup (which is tomorrow).

We can make update and announce it with new version of `bem-core` later. But of course I'll be happy to have this improvement as soon as possible.

**Comment by ilyar** [comment]
Update bem-xjst to ^0.7.0 in v2 really?

**Comment by veged** [comment]
@ilyar what's the problem?

**Comment by ilyar** [comment]
https://github.com/bem/bem-xjst/pull/15
no problem. I want to use the library instead of writing new ones.

**Comment by tadatuta** [comment]
@ilyar yes, we decided to update it in `v2`

**Comment by ilyar** [comment]
great! 
fix Labels

**Comment by narqo** [comment]
@tadatuta is it fixed already?

**Comment by tadatuta** [comment]
@narqo it should also be ported to `v3`. i'll do it soon.

**Comment by tadatuta** [comment]
there's yet another bug in the change I made in `bem-xjst`. sent a PR: https://github.com/bem/bem-xjst/pull/17

**Comment by tadatuta** [comment]
https://github.com/bem/bem-core/issues/625
