### ISSUE TITLE
Implement some of ES6 features as polyfills 

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#494]
As we build a future-aimed library with out strict deadlines, why not to think about implementing some things from, well,.. ~~"future"~~, ES6 standard :)

For things like [`Array.prototype.find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) ([polyfill](https://github.com/paulmillr/Array.prototype.find)) and [`Array.prototype.findIndex`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex) ([polyfill](https://github.com/paulmillr/Array.prototype.findIndex)) we commonly use `Array.prototype.some` or plain `while`-loop, which "could look not very clear in some cases" (© @dfilatov).

Firefox supports both of them starting from version 25. I believe Chrome would support them natively to autumn.

**Comment by narqo** [comment]
See comments in #495

**Comment by dfilatov** [comment]
The main problem is the same as we had when we used to use `ecma__array` -- which block should have deps from shim? Do we have to add `ecma__array` in each block which uses `Array.prototype.find`?
