### ISSUE TITLE
BEMTREE: Possibility to separate browser and private server templates

### ISSUE THREAD

**Issue by veged** [bem/bem-core#50]
By analogy with JS (`*.browser.js`, `*.node.js`, `*.vanilla.js`) we can make `*.browser.bemtree.xjst`, `*.node.bemtree.xjst`, `*.vanilla.bemtree.xjst`.

**Comment by narqo** [comment]
@veged why there no `vanilla.bemhtml`?

**Comment by veged** [comment]
BEMHTML suppose to be "the one", but for BEMTREE we already have both cases

**Comment by narqo** [comment]
Couldn't we use `depsByTech` for those cases?

**Comment by veged** [comment]
Nope. It's not exactly the same. We need possibility to write absolutely private bemtree code (analog of `priv.js`). That's not the same with just declaration `depsByTechs` between `node.js` and `bemtree` techs.

**Comment by veged** [comment]
should belong to bem-xjst or enb-\* now
