### ISSUE TITLE
BEMTREE: Drop `.xjst` from `.bemtree.xjst` file extension

### ISSUE THREAD

**Issue by veged** [bem/bem-core#51]

**Comment by narqo** [comment]
:+1: 

@veged 
Какая сейчас политика именования? Когда `.xjst` нужен, когда нет?

**Comment by veged** [comment]
кажется, что никакой особенной необходимости в `.xjst`, с новым js-синтаксисом, нет -- всё равно нужно настраивать в редакторе, чтобы использовался js-плагин синтаксиса для каждого нового расширения

**Comment by narqo** [comment]
Я видел в [коде технологии](https://github.com/bem/bem-core/blob/dev/.bem/techs/bemhtml.js#L22) такое `suffix !== 'bemhtml.xjst' ...` — поэтому и спрашиваю, в чем отличия теперь?

**Comment by veged** [comment]
`bemhtml.xjst` явно сразу парсится как js-синтаксис -- но т.к. вполне работает совместимость (через попытаться спарсить как js, если не получилось, использовать bemhtml-compat), а для bemtree это вообще не актуально, то на это можно не смотреть
