### ISSUE TITLE
Feedback for "BEMHTML: описание шаблонизатора и его преимуществ"

### ISSUE THREAD

**Issue by pavelpower** [bem/bem-core#563]
Добре!

В статье устарели ссылки на шаблонизаторы. Как не переходишь так 404

**Comment by innabelaya** [comment]
Спасибо! поправим обязательно

**Comment by tormozz48** [comment]
Спасибо за ваши отзыв. Эта проблема была связана с переопределением ссылок для сайта. В скором времени будет исправлена.
