### ISSUE TITLE
Add jshint-groups, jscs and pre-commit hooks

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-core#57]

**Comment by narqo** [comment]
@dfilatov а не проще было принять `{ a : 'c' }` за код-стай??? — у нас оно вроде везде использовалось

**Comment by dfilatov** [comment]
Мне надоело бесконечно спорить со всеми, все пишут по-другому. Я смирился, хоть и не разделяю.

**Comment by mishanga** [comment]
Сам код-стайл не важен, важно его наличие и соблюдение.

**Comment by narqo** [comment]
@mishanga если в каждой bem-\* и каждой islands-\* будет свой код-стайл (именно _будет_, на уровне jshintrc, jscs и пр.), он тоже не будет важен? А если он будет отличаться в мажорных ветках? — Тоже, главное чтобы был?
