### ISSUE TITLE
BEM.I18N: Use modules

### ISSUE THREAD

**Issue by veged** [bem/bem-core#59]
Depend on #58.

cc @dfilatov

**Comment by veged** [comment]
Возникает ряд нюансов, связанных с объединением разных технологий (например `browser.js+bemhtml`) и дублированием подключения ядра ymodules.

**Comment by dfilatov** [comment]
Вроде, похожие нюансы мы учли в технологии test.js+browser.js+bemhtml в bem-core, можно ее взять как пример.

**Comment by dfilatov** [comment]
Сейчас работает для клиентского js, необходимо сделать для BEMHTML

**Comment by veged** [comment]
close in favour of #576
