### ISSUE TITLE
BEMTREE error handling

### ISSUE THREAD

**Issue by apsavin** [bem/bem-core#594]
I think, we should stop use

``` javascript
Vow
        .allResolved(ctx.__queue)
        .always(function() {
            return ctx._buf;
        });
```

[here](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemtree#L98)
and start use something like

``` javascript
Vow
        .all(ctx.__queue)
        .then(function() {
            return ctx._buf;
        });
```

instead.
It seems to me, that it's impossible to do error handling now in BEMTREE, because it always behaves like all is ok.
What do you think about it?

**Comment by tadatuta** [comment]
+1
// cc @narqo

**Comment by narqo** [comment]
I don't mind

**Comment by veged** [comment]
### Meeting results:
- fix `apply` (https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemtree#L100) to return result AND promises (so we need to use `spread` after, need issue for document it)
- add 3 more optional parameters to `doAsync` (`onFulfilled`, `onRejected`, `context`) — like in `when` (need issue for document it, maybe same as in prev point)
