### ISSUE TITLE
More arguments for doAsync bemtree method

### ISSUE THREAD

**Issue by apsavin** [bem/bem-core#596]
Right now only one argument can be passed into [doAsync](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemtree#L70) inside [bemtree](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemtree) tech files and this argument is function to invoke. I think, we should implement possibility to pass any number of arguments. It will not very hard, because doAsync [uses](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemtree#L77) Vow.invoke internally, which [can](https://github.com/dfilatov/vow/blob/master/lib/vow.js#L892) behaves like this.

I need it, for example, for things like this:

``` javascript
this.doAsync(function(_this){
    return request.get(route)
        .then(function () {/*ok*/}, function() {/*error*/}, _this);
}, this);
```

Of course, I can do right now like this:

``` javascript
this.doAsync(function(){
    return request.get(route);
}).then(function () {/*ok*/}, function() {/*error*/}, this);
```

But it's not the same, especially if [pull-request](https://github.com/bem/bem-core/pull/595) about error handling will be merged.

**Comment by tadatuta** [comment]
sounds reasonable, can you please suggest PR as well?

**Comment by apsavin** [comment]
We decided to use doAsync arguments in the different manner #594
