### ISSUE TITLE
Destructor and Constructor incosistency

### ISSUE THREAD

**Issue by L0stSoul** [bem/bem-core#599]
Generally we use code like this as constructor:

```
onSetMod: {
    'js': function() {
         ...
    }
}
```

And we have this as destructor:

```
destruct: function() {
}
```

So it's the part of very similiar init/deinit process, why we have soooo diferent syntax for this tasks?

I think it will be more simple/consistent if we have something like 

```
construct: function() { ... }
destruct: function() { ... }
```

**Comment by dfilatov** [comment]
In bem-core there is no more `destruct` method.

``` js
onSetMod: {
    'js': {
        'inited' :  function() {
             // constructor
        },
        '' : function() {
             // destructor
        }
    }
}
```

**Comment by L0stSoul** [comment]
oh thank you!
