### ISSUE TITLE
Блок `Promise` в core

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#6]
Я думал вносить `i-bem.bemtree.xjst` из [bem-yana-stub](https://github.com/narqo/bem-yana-stub/) в bem-core, но осознал, что результат вызовава `BEMTREE.applyAsync()` возвращает Vow-промис.

Внимание, вопрос, в bem-core, все это нужно? Или куда это девать?

\cc @veged @arikon @dfilatov

**Comment by dfilatov** [comment]
vow внесен в bem-core
