### ISSUE TITLE
i-bem. enb+bh (setMod('js', 'inited') is not called).

### ISSUE THREAD

**Issue by pahaz** [bem/bem-core#606]
I have problem with i-bem block. 

https://github.com/pahaz/bem-project-stub-with-bh-and-enb/blob/master/desktop.bundles/index/index.includes.all.js#L191

`_init` is not call.

And js.inited callback is not call https://github.com/pahaz/bem-project-stub-with-bh-and-enb/blob/master/common.blocks/my-block/my-block.js#L8 

I use enb+bh for make.

My solution - https://github.com/pahaz/bem-project-stub-with-bh-and-enb

**Comment by pahaz** [comment]
`DOM.init();` is not call;

Calling is not solve problem. Problem in storing block data.

https://github.com/bem/bem-core/blob/v3/common.blocks/i-bem-dom/i-bem-dom.js#L207-L210
use `data-bem` attr for data store but now data in `onclick` attr.

```
<div class="my-block i-bem" onclick="return {&quot;my-block&quot;:{}};">aaa</div>
```

**Comment by pahaz** [comment]
Reson of problem find:
-  `bh` store data in `onclick` attr https://github.com/enb-make/bh/blob/2482e77e96a3273d98853df764711573df89c8c3/lib/bh.js#L48
- `i-bem-dom` use `data-bem` attr for store data https://github.com/bem/bem-core/blob/40c7e47669bef76833332994feff0b1aa1928ae9/common.blocks/i-bem/__dom/i-bem__dom.js#L190-L193

related issuse https://github.com/enb-make/bh/issues/63

**Comment by pahaz** [comment]
Problem may be solved by using `jsAttrName` and `jsAttrScheme` `enb` config.

```
nodeConfig.addTech([require('enb-bh/techs/bh-server'), { jsAttrName : 'data-bem', jsAttrScheme : 'json' }]);
```

**Comment by tadatuta** [comment]
isn't it already there: https://github.com/bem/bem-core/blob/v2/.enb/make.js#L204 ?

**Comment by pahaz** [comment]
Yes, thanks. Now I understand where find examples. 

I wrot config for themself by using enb-make.info and enb source code.

I think this is the last strange issues.

Thanks, again.
