### ISSUE TITLE
`pointerpress`/`pointerrelease` event should be fired if only left mouse button is pressed

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-core#607]

**Comment by narqo** [comment]
@dfilatov I can't reproduce it, at least with my touchpad. Actually we even have [tests](https://github.com/bem/bem-core/blob/1d1b607cff47d1530791c8b7ab0df2ecf27c3d6c/common.blocks/jquery/__event/_type/jquery__event_type_pointerclick.spec.js#L7-L22) for this case, which work. 

Could you add some more details?

**Comment by dfilatov** [comment]
@narqo my case is desktop FF

**Comment by narqo** [comment]
`pointerclick` seems work fine, should check `pointerpress/pointerrelease` events
