### ISSUE TITLE
Add browser.js+bemhtml+bemtree tech

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#621]

**Comment by tadatuta** [comment]
done in https://github.com/bem/bem-core/commit/5c5d88a3c4ed243fb4f8ad04dacbb2e993b5112b

**Comment by deeonis** [comment]
need port to v3

**Comment by narqo** [comment]
Must be ported to v4.

**Comment by tadatuta** [comment]
@narqo I'd better get rid of any support for `bem-tools` in v3. Let's close all such issues?
