### ISSUE TITLE
BEMHTML reference: Need to document order of modes call in `default` mode

### ISSUE THREAD

**Issue by alexbaumgertner** [bem/bem-core#643]
Порядок обхода стандартных мод задается в моде `default` – не указан сам порядок.

Предположительно, судя по https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L322 должно быть так:
1. [tag](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L332)
2. [js](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L339)
3. [bem](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L346)
4. [cls](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L350)
5. [mix](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L359)
6. [attrs](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L432)
7. [content](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L432)

Вот скомпилированный файл (правда, из bem-bl) https://github.com/alexbaumgertner/bare-bemhtml/blob/master/bare-bemhtml.js#L388

**Comment by alexbaumgertner** [comment]
И еще, можно в этом же списке мод указать [значения по-умолчанию](https://github.com/bem/bem-core/blob/v2.4.0/common.blocks/i-bem/i-bem.bemhtml#L475):
1. tag : `<div>`
2. js: `false` (аттрибут `data-bem` и class DOM-узла `i-bem` отсутствует)
3. bem:  `undefined` (к DOM-узлу блока `block-name` добавляется `class="block-name"`)
4. cls: `undefined`  (у DOM-узла блока `block-name` нет дополнительных css-классов)
5. mix: `undefined` (у блока нет микса)
6. jsAttr: `undefined` (у блока нет `onclick` параметров)
7. attrs: `undefined` (у DOM-узла блока нет атрибутов)
8. content: `content` блока.

**Comment by alexbaumgertner** [comment]
@veged подскажи, это файл с документацией – https://github.com/bem/bem-core/blob/v2/common.docs/reference/reference.ru.md?

**Comment by veged** [comment]
да, вся документация тут https://github.com/bem/bem-core/tree/v2/common.docs — там есть ещё

**Comment by Murdalay** [comment]
https://github.com/bem/bem-core/pull/680
