### ISSUE TITLE
depsByTech not so well documented

### ISSUE THREAD

**Issue by qfox** [bem/bem-core#649]
https://encrypted.google.com/search?q=site%3Abem.info+depsByTech
nothing ;-(

**Comment by tadatuta** [comment]
https://yandex.com/sitesearch?searchid=1944806&l10n=ru&reqenc=&text=depsbytech&redircnt=1408433515.1 :)

**Comment by tadatuta** [comment]
но на самом деле по существу всего один абзац: http://ru.bem.info/tools/bem/bem-tools/depsjs/#Подключение-зависимостей-по-технологии

нужно расширить описание.

// cc @innabelaya @Murdalay

**Comment by qfox** [comment]
Спасибо ;-)

**Comment by veged** [comment]
как именно нужно расширить описание? по моему оно «goto enough»
