### ISSUE TITLE
tech field in deps files is redundant

### ISSUE THREAD

**Issue by floatdrop** [bem/bem-core#652]
We are investigating in structure of bem-core and bem-components. For know tech field in deps files is used only for spec.js and tmpl-spec.js technologies in any blocks (besides attach in bem-components - which seems to be broken for bh).

This usage of tech property tells us, that it can be removed without breaking build of BEM components for production.

**Comment by floatdrop** [comment]
This is not my issue. Do not edit contents of issues, that was not created by you. Close and reopen.

**Comment by veged** [comment]
sorry — I suppose we discuss that this way on Gitter and I also talk about rewriting

**Comment by veged** [comment]
@floatdrop restore your original text — sorry one more time
