### ISSUE TITLE
Think about CamelCase naming

### ISSUE THREAD

**Issue by veged** [bem/bem-core#657]
It can allow as to avoid regular manual translation of `dash-delim` to `CamelCase` in JS (i.e. `blocks['serp-item']` vs. `var SerpItem`). Also it's more useful for "word" operations such double-click text select, Ctrl/Option moves and so on. And looks much nicer (for my taste ;-)): `MyBlock`, `MyBlock__SomeElem` (or `MyBlock__someElem`), `MyBlock_modName_modVal`, `MyBlock__SomeElem_modName_modVal` (or `MyBlock__someElem_modName_modVal`).

**Comment by qfox** [comment]
In that case we can think also about delimiter between `blockName` and `elementName`:

```
BlockName__ElementName
BlockName-ElementName
```

an so on.

**Comment by qfox** [comment]
Btw, lowerCamelCase vs UpperCamelCase.

E.g.

```
blockName__elementName
BlockName__elementName
blockName__ElementName
blockName-elementName
BlockName-elementName
blockName-ElementName
```

**Comment by veged** [comment]
`UpperCamelCase` for blocks and `lowerCamelCase` for elements and modifiers.

I'm ok with underscore for delimiting. Also `dash-delimited` stuff doesn't treated as "one word".

**Comment by tadatuta** [comment]
I'd be much happier if we get rid of all places where we hardcode any particular naming scheme.
We already avoid them in JS or BEMHTML and have http://bem.info/tools/bem/bem-naming/ to stringify object notation to strings according to literary any config.

So if we manage to get rid of hardcode in CSS and BH there will be no need to decide about delimiters at all.

The first thing which comes to my mind is to use some placeholder like `%%block%%` and teach our tools to replace such placeholders in build time.
E.g. if we have `b1/b1.css` with

``` css
.%%block%%
{
    color: red;
}

.%%block%%__e1
{
    font-size: 12px;
}
```

we can treat it as

``` css
.b1
{
    color: red;
}

.b1__e1
{
    font-size: 12px;
}
```

just because of file name. And actually the same rule can be applied to any other tech including md-files, etc.

**Comment by qfox** [comment]
Why not to prepend some service variable in each tech for blockname/elemname/etc.?

upd: WITH separator. or just provide separator, or several methods to build all kind of names.

**Comment by veged** [comment]
@tadatuta I'm talking about places where we need names (for example filenames) — task about deriving context for file content from file name (for example as in deps) should be separate

**Comment by apsavin** [comment]
+1 for UpperCamelCase for blocks names, because "block name" = "class name".
But compatability is more important, I think.

**Comment by qfox** [comment]
@veged case-sensitivity can destroy your idea to use uppercase letters in filenames on different platforms.

**Comment by iamstarkov** [comment]
I don't like this idea

**Comment by veged** [comment]
@zxqfox I'm not gonna use any platforms with case-insensitivity in file name — it's insane o_0

**Comment by qfox** [comment]
@veged em. some users using windows and macos ;-) and I think filenames should be lowercased. Yes. It's insane.

**Comment by gruzzilkin** [comment]
+1 @matmuchrapna

**Comment by qfox** [comment]
There is a difference between case-sensitive file system and applications which can handle `FoO` and `fOo` as same. http://support.microsoft.com/kb/100625 http://apple.stackexchange.com/questions/22297/is-bash-in-osx-case-insensitive

Are you ready for these potential bugs? ;-D

**Comment by veged** [comment]
@zxqfox MacOSX is case-sensitive — if some versions of Windows doesn't support case-sensitive names it's hard problem at all (many other dev stuff just can't work), better use VM with normal dev OS

**Comment by veged** [comment]
@matmuchrapna @gruzzilkin could you please describe your opinion a little bit more? cause I'm mostly speaking not about prettiness (which is very subjective) or familiarity (which is of course for current state) but about usage convenience (necessity of converting dash-delim to CamelCase in code and "words" text operations)

**Comment by varya** [comment]
Although I generally like the idea of CamelCase, I am absolutely sure that possible user's inconvenience should be taken into account. The argument of which system and preferences are used by the BEM core team members is not very strong because the community is much more massive and must not be ignored.

**Comment by qfox** [comment]
@veged Em. As I said, there is a difference between FS and Apps. MacOSX as well as Windows have case-sensitive FS. But many apps on them haven't. You can test it. Both will have the same result (if you ignore decorations):

```
mkdir FoO
ls f*
ls fOo # or dir fOo
```

It preserve case but not insensitive.

> HFS+ (the Mac filesystem) is usually configured to be case insensitive but case preserving

And actually the same for `winnt` (2k, xp, win7, etc) with `ntfs`.

And it doesn't work on any version of linux, yes. Apps there is case-sensitive as well as FS.

**Comment by qfox** [comment]
So. Im not sure I can create 2 files with different letter cases. E.g. `LeMoore` and `Lemoore` will be the same file. Even if I can't find good example it's potential bug ;-\

**Comment by veged** [comment]
@zxqfox oh! now I see :-/ But it's not gonna inflict bugs since we doesn't need to create `myblock.ext` and `MyBlock.ext` in same directory.

**Comment by qfox** [comment]
@veged Ye, sure. Only for things like `SomeBlock.ext` and `SomebLock.ext`. With `-` there are no problems.

**Comment by Leonya** [comment]
@veged It will cause lots of pain if you'll have to rename lots of files, changing only case, e.g. git mv block.js Block.js

**Comment by varya** [comment]
Having `myBlockName` variables in JavaScript and `my-block-name` CSS classes refers to CSS properties. So this looks logical for the developers. You can add `myBlockName` alias to every `block['my-block-name']` automatically. This will help to make your JavaScript nicer but at the same time   is totally compatible.

**Comment by corpix** [comment]
Personally I like this idea, it adds a little bit of convenience for developers. 
**BUT**, think about current library users. They will be forced to update whole project codebase just to support this CamelCase naming. For small projects it will be easy, but not for projects, who has thousands of personal blocks. It's horrible!

Also, will this change affect projects that use old `bem-bl` library?

**Comment by mishanga** [comment]
Надо еще придумать, как использовать знаки препинания в именовании, и тогда названия БЭМ-сущностей можно будет использовать в качестве надежных паролей.

**Comment by qfox** [comment]
@veged Can we move that idea to v4+? I'm about label.

**Comment by veged** [comment]
в рамках ближайших мажорных версий bem-core мы не будем делать таких масштабных изменений — подумаем в рамках следующих "эпох" ;-)
