### ISSUE TITLE
Error on make sets

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-core#663]
``` bash
git clone git@github.com:bem/bem-core.git
cd bem-core
npm i
bower-npm-install
bem make sets
```

get this:

Error: Error while processing files:
common.blocks/jquery/__event/_type/jquery__event_type_pointernative.js

Error: Error: "Cannot read property '1' of null" while processing jsdoc comments started at line 34

**Comment by tadatuta** [comment]
works fine for me at the moment
