### ISSUE TITLE
i-bem: Отразить в документации причины появления onBeforeSetMod

### ISSUE THREAD

**Issue by Murdalay** [bem/bem-core#682]
Прошу помощи у старших товарищей. @tadatuta Каковы эти причины, вкратце? Может есть какая-то инфа?

**Comment by veged** [comment]
Основная суть в необходимости иметь возможность отменять установку модификатора. Раньше обработчики `onSetMod` могли вернуть `false` и это означало, что нужно отменить установку модификатора. Но это означает, что в момент выполнения `onSetMod` модификатор у блока ещё не стоит, что часто бывает логически неудобно когда пишутся обработчики.

С появлением `beforeSetMod` всё явным образом разделилось — есть обработчики для потенциальной отмены установки модификатора (`beforeSetMod`) и есть отдельно обработчики, которые запускаются уже когда модификатор полностью стоит (`onSetMod`)

Может @dfilatov добавит ещё примеров и описания.
