### ISSUE TITLE
i-bem.js: инициализация и модификаторы

### ISSUE THREAD

**Issue by escaton** [bem/bem-core#688]
Привет!
Есть блок с проставленными при шаблонизации модификаторами и js инициализаций (ленивой или нет — не важно) когда ему поставится js inited, отработает код задекларированный в onSetMod js inited. Вопрос: почему бы тут же не дергать обработчики других мод, которые уже стоят на блоке?
Сейчас это выглядит в некоторых случаях так:

```
onSetMod: {
   state1: function() {
       // тут куча логики1
   },
   state2: function() {
       // еще до фига логики2
   },
   js: function() {
       // обычная инициализация
       if (this.hasMod('state1')) {
           // копипаста логики1
       }
       if (this.hasMod('state2')) {
           // копипаста логики2
       }
   }
}
```

cc @an9eldust

**Comment by veged** [comment]
cc @dfilatov

**Comment by qfox** [comment]
Кстати, тоже об этом думал.

Как вариант, если прямая инициализация что-то будет ломать, можно вместо копипасты кода дать возможносьт генерировать событие проставление модификатора.

Например, так:

``` js
onSetMod: {
  js: function () {
    // ...
    if (this.hasMod('state1')) {
      this.emit('setMod', {mod: 'state1', val: this.getMod('state1')});
    }
  }
}
```

Либо пойти дальше и сделать хелпер `initMod`, реализующий эту логику.

Впрочем, даже если и все модификаторы будут инициализированы при js_inited, emit события проставления модификатора был бы полезен в некоторых особо сложных случаях.

**Comment by escaton** [comment]
Согласен, можно сделать либо модификатор, либо флаг как-то так:

```
BEM.DOM.decl('block', {
    ...
}, {
    initMods: true
})
```

**Comment by qfox** [comment]
@dfilatov Some solution here? Can we emit existent mods on initialize?

**Comment by dfilatov** [comment]
No we can't. Let's imagine that we append some dom nodes when modifier is set and remove them when modifier is unset. And we have the same logic in corresponding template. If we call handlers for this mod on js init, we either append nodes twice (first in templates, second in js) or we should do some additional checks in handlers to prevent.

**Comment by qfox** [comment]
Did you talking about troubles with current blocks realisation or about how it should works at all? What if we don't append dom nodes on mod set?

I'm already accustomed to the current business logic of initialisation (to the absence of the mods initialization except `js_inited`) and atm I'm agree that better to leave it as is. But anyway if we leaving it as is there must be a way to emit needed mods. It's pretty common problem.

Sure there is workaround with moving out all logic out of states if we talking about original case of this issue. But still it's just a workaround. Something like that:

``` js
onSetMod: {
  state1: function() {
    this._onState1();
   },
   state2: function() {
    this._onState2();
   },
   js: function() {
    if (this.hasMod('state1')) {
      this._onState1();
    }
    if (this.hasMod('state2')) {
      this._onState2();
    }
  }
},
_onState1: function () { ... },
_onState2: function () { ... }
```

**Comment by veged** [comment]
thnx @zxqfox, you just described the best and only known approach to deal with such cases

unfortunately, right now we can't suggest anything more in current architecture of i-bem.js :-(
