### ISSUE TITLE
bem.info: jquery-docs shows ua-docs

### ISSUE THREAD

**Issue by vaseker** [bem/bem-core#702]
На странице документации к блоку jQuery только одна строка о jQuery, остальное – об ua.
http://ru.bem.info/libs/bem-core/v2.3.0/desktop/jquery/docs/

UPD: En документации ко всем компонентам нет вообще. http://bem.info/libs/bem-core/v2.3.0/desktop/jquery/

**Comment by tadatuta** [comment]
Мы в процессе, уже сейчас можно найти несколько PR с документацией, ожидающих вычитки.

**Comment by veged** [comment]
@tadatuta прилинкуй другие тикеты
