### ISSUE TITLE
platform detection fail

### ISSUE THREAD

**Issue by aliosv** [bem/bem-core#703]
в ua нет полей ios, android, iphone

яузер на андроиде ![image](https://cloud.githubusercontent.com/assets/2275425/4715096/f695dcb2-58fa-11e4-830f-23bf4289f20e.png)
ua содержит поля chrome, version, webkit
iphone ![image](https://cloud.githubusercontent.com/assets/2275425/4715127/552594e8-58fb-11e4-9c52-0268014af742.png)
в ua: webkit, version, safari

ревизия bem-core https://github.com/bem/bem-core/tree/82f4d4899ab3ad3d38b2c69c052f1d60c6e8d19b

**Comment by veged** [comment]
а чем дело кончилось? почему "Closed"?

**Comment by aliosv** [comment]
невнимательность: забыл тачевый уровень подключить...
