### ISSUE TITLE
Add support for mixes as strings

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#717]
I often find myself trying to write something like

``` js
block('blah').mix()('clearfix');
```

@veged @mishanga what do you think about such possibility?

**Comment by veged** [comment]
I can agree with such sugar. It's simple to add here https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L374 and should not damage performance.

@mishanga what do you think?

**Comment by mishanga** [comment]
:+1:

**Comment by veged** [comment]
@tadatuta ok — go ahead then!

**Comment by aristov** [comment]
@mishanga is it already supported in `bh`?

**Comment by mishanga** [comment]
В BH это пока не сделано. И мне хотелось бы иметь полноценную возможность миксовать таким образом любые БЭМ-сущности, а не только блоки.

**Comment by veged** [comment]
про любые БЭМ-сущности у нас тут расходится идеология:
- мы нигде не используем "языки" в js-строках (разметка через _ это тоже считай наноязык) — это касается всего кода во всех местах (общий принцип), иногда кажется, что хочется его нарушить, но если быть последовательными, то это дорога в... в общем не хочется ;-)
- но в BH изначально матчинг сделан нарушая этот принцип

Но! кажется, что если сделать "в лоб" и все `typeof mixItem === 'string'` трактовать как `{ block : mixItem }`, то CSS-классы будут проставляться ожидаемые для любых кейсов, когда `mixItem ===  'b1__e1'

**Comment by blond** [comment]
> про любые БЭМ-сущности у нас тут расходится идеология:

Достаточно просто передавать опцию `naming: { elem: '__', mod: '_' }`, которая будет говорить о том как следует интерпретировать строки.

**Comment by qfox** [comment]
@blond В BH не все так просто.
https://github.com/bem/bh/blob/master/lib/bh.js#L731-L760
https://github.com/bem/bh/blob/master/lib/bh.js#L1104-L1121

toBemCss — более менее, а fromBemCss — прохардкожен.

Я вынес это дело в bh-php так: https://github.com/bem/bh-php/blob/master/src/BH.php#L690-L704

**Comment by veged** [comment]
дело не в том, как сложно реализовать парсинг кастомного языка из js-строк, а в том, что это в принципе нужно делать — это всё "затуманивает"

**Comment by blond** [comment]
> это всё "затуманивает"

Расшифруешь? :)

Желание то понятно откуда берётся — писать меньше буковок.

**Comment by qfox** [comment]
Пара мыслей:

```
// из первой библиотеки:
bh.match('строка, которую надо парсить, в формате 1', function...)
bh.match('строка, которую надо парсить, в формате 1', function...)
// из второй библиотеки
bh.match('строка, которую надо парсить, в формате 2', function...)
bh.match('строка, которую надо парсить, в формате 2', function...)
```

Если мы будем такое поддерживать (bem-naming, и все такое, да?), в жизни получится так:

```
bh.match('block__elem--mod', function...) // из 2
bh.match('block__elem_mod', function...) // из 1
bh.match('block--mod', function...); // из 2
bh.match('block_mod', function...); // из 1
```

Можно было бы предложить переключать:

```
bh.useNaming(namingWithMinuses);
bh.match('block__elem--mod', function...);
bh.useNaming(classicNaming);
bh.match('block__elem_mod', function...);
```

Но как-то грязно все.

Есть еще вариант делать это на уровне сборки — при парсинге пересобирать первый параметр match в другой формат, или сразу объект туда писать (что более логично — меньше в рантайме делать, но в bh надо будет патч).

**Comment by qfox** [comment]
В общем, я согласен с @veged.

**Comment by veged** [comment]
@blond "язык" внутри js-строк — нет хайлайтинга, нет синтаксической валидации и т.д. и т.п., а сам синтаксис языка отдельно учить надо

**Comment by blond** [comment]
@veged всё так, но мы же в `js` и `css` так не делаем, почему для шаблонов это важнее?

**Comment by qfox** [comment]
@blond Как это не делаем, когда у нас либо less, либо stylus, либо еще что-то? Равно как и this.name мы тоже используем, и `{block: 'b', elem: 'e'}` пишем.

**Comment by blond** [comment]
Открываем код `button`.

JavaScript:

``` js
modules.define(
    'button',
    ['i-bem__dom', 'control', 'jquery', 'dom', 'functions', 'keyboard__codes'],
    /* ... */
```

Стили:

``` styl
ctx = '.button_theme_islands'
{ctx} {
    .button__text {}

    &.button_type_link {}
}
```

**Comment by veged** [comment]
@blond как раз это из js правило (в css просто выразительность языка маленькая и там могут быть какие-то условности) — а имена модулей в модульной системе это просто от ограничения ymodules (именами модулей могут быть только строки), в `BEMDOM.decl` нет никаких строк
