### ISSUE TITLE
bh.php templates for bem-core?

### ISSUE THREAD

**Issue by qfox** [bem/bem-core#732]
Is it possible?

**Comment by tadatuta** [comment]
here's [project-stub branch](https://github.com/bem/project-stub/tree/php-bem-bh) with `bem-tools` tech to build `bh.php` and all the instructions to run it

**Comment by veged** [comment]
unfortunately, right now we aren't ready to include bh.php into `bem-core` :-(

**Comment by qfox** [comment]
@veged Some troubles?

**Comment by veged** [comment]
yep... we need to broad our minds, seriously extend tools set (for support tests of php templates and so on) and also we have no enough php-experts here to proper support :-(

**Comment by qfox** [comment]
@veged Tests already exists inside the PR if you didn't noticed. PHP experts — ok, hire them!

**upd**: Sorry, tests were added in bem-components. But it's easy to repeat them here. https://github.com/bem/bem-components/pull/1113/files#diff-94d5989e964d9e6be8bea46eb8da6cc0R341

**Comment by veged** [comment]
@zxqfox most of us just don't want to setup PHP for run those tests ;-) also the new tests will take more time to run (every time!)

haven't you already created a separate library for these templates? may be we can try to live with bh.php in separate lib for a while

**Comment by qfox** [comment]
@veged We already thinking about it ;-) The main problem in library configs synchronization. It will be very hard to support.

If we solve these problems it definitely would be in separate package with bem-components dependency. But for now I can't even imagine how to do it right.

Maybe @andrewblond and @tadatuta will help with that.
