### ISSUE TITLE
dom.js: Replace `document.activeElement` to `document.documentElement.activeElement`

### ISSUE THREAD

**Issue by artems** [bem/bem-core#744]
About this line https://github.com/bem/bem-core/blob/v2/common.blocks/dom/dom.js#L36

To get rid of the error  in IE9 using `document.activeElement` you can replace `document.activeElement` to `document.documentElement.activeElement`

Also check this JQuery issue http://bugs.jquery.com/ticket/13378

**Comment by veged** [comment]
@tadatuta need to investigate some standards, specifications or MSDN page about this and use `document.documentElement.activeElement` without `try`/`catch` if it really works fine

**Comment by dfilatov** [comment]
Since it's not a big problem and nobody hasn't investigated it yet — won't fix.
