### ISSUE TITLE
i-bem.bemhtml: get rid of boolean check for `extend` arguments

### ISSUE THREAD

**Issue by aristov** [bem/bem-core#747]
``` javascript
this.extend(ctx.js, js === true? {} : js)
```

It seems, that check for second argument is redundant, because:

``` javascript
this.extend({}, {}) // => {}
this.extend(true, {}) // => {}
this.extend({}, true) // => {}
this.extend(true, true) // => {}
```

**Comment by aristov** [comment]
cc @narqo

**Comment by narqo** [comment]
Let's add some tests here https://github.com/bem/bem-core/tree/df8d92269d4c27a7e16750a92315cc6497b41f42/common.blocks/i-bem/i-bem.test.bemhtml/files/i-bem

**Comment by aristov** [comment]
It seems that we can't do so, because:

``` js
this.extend(undefined, true) // => true
this.extend(true, undefined) // => true
```

So if we drop boolean check:

``` js
this.extend(ctx.js, js === true? {} : js)
=>
this.extend(ctx.js, js)
```

then we get something like this:

``` js
{ block: 'b1' }
+
block('b1').js(true)
=
<div class="b1 i-bem" data-bem='{"b1":true}'>
```

I've checked it.

**Comment by aristov** [comment]
check with `objects:extend` and fix.

**Comment by deeonis** [comment]
@aristov ping

**Comment by veged** [comment]
not relevant for bem-core, since we have bem-xjst with base templates inside

see also #1258
