### ISSUE TITLE
page: <html lang="lang">

### ISSUE THREAD

**Issue by vaseker** [bem/bem-core#751]
В `page.bh.js` не предусмотрена установка аттрибута `lang` для тега `html`.

Приходится указывать язык в meta: `<meta http-equiv="content-language" content="ru"/>`

W3 validator по этому поводу говорит:

> Using the meta element to specify the document-wide default language is obsolete. Consider specifying the language on the root element instead.

Логично ли для решения этой проблемы создать PR с изменением: 

``` js
tag : 'html',
attrs: { lang: json.lang }
```

или есть аргументы "против"?

**Comment by gorbenko** [comment]
Костыльное решение может быть таким:

bemjson:

``` js
{
 block: 'b-page',
 lang: '%lang%'
}
```

b-page.bh.js на уровне проекта:

``` js
module.exports = function (bh) {
    bh.match('b-page', function (ctx) {
        ctx.tParam('lang', ctx.param('lang'));
    });

    bh.match('b-page__html', function (ctx) {
        ctx.attr('lang', ctx.tParam('lang'));
    });
};
```

Но думается, что такая реализация должна быть на уровне вендора.

**Comment by steve-reichbach** [comment]
+1

**Comment by qfox** [comment]
Если уж в одном файле, то...

``` js
module.exports = function (bh) {
    var lang;
    bh.match('b-page', function (ctx) {
        lang = ctx.param('lang');
    });
    bh.match('b-page__html', function (ctx) {
        ctx.attr('lang', lang);
    });
};
```

**Comment by gorbenko** [comment]
@zxqfox 
Когда bh-шаблоны выгружаются на клиент, все `module.exports` режутся и ваш `lang` улетает в `window`. Но pull не об этом.

**Comment by tadatuta** [comment]
для `<html>` потенциально могут понадобится еще атрибуты `manifest` и `xmlns`.

**Comment by qfox** [comment]
@gorbenko А разве оно не заворачивается в `module.exports = function` или `modules.define('BH', function` ? Впрочем, согласен, что tParam лучше. В т.ч. это лучше, если преобразовывать в bh.{notJs}.

@tadatuta @vaseker А в bemhtml это есть? Имхо, надо тоже добавить, если нет.

**Comment by vaseker** [comment]
@zxqfox в bemhtml тоже нет.

**Comment by qfox** [comment]
@vaseker Спасибо.

@tadatuta В общем, надо и туда, и суда добавлять? Или надо подумать?

**Comment by tadatuta** [comment]
@gorbenko я правильно понимаю, что пример про костыльную реализацию — не про `bem-core`, а про какую-то кастомную реализацию обвязки?

@zxqfox похоже, что нужно.
@veged, нет возражений против добавления опционального ключа `htmlParams` в BEMJSON API  `page`?

**Comment by gorbenko** [comment]
@tadatuta да, в нашем случае это [bem-bl](https://github.com/bem/bem-bl/blob/dev/blocks-desktop/b-page/b-page.bemhtml#L57).

**Comment by veged** [comment]
@tadatuta почему `htmlParams` а не просто `lang`? какие-то ещё нужны будут параметры? по умолчанию мы против абстрактных коллекций на любые параметры, лучше точечно решать

**Comment by tadatuta** [comment]
@veged если следовать принципу минимализма, то, вроде, нужно оставлять только `lang`.
Но, например, для rtl-языков потребуется `dir`, для оффлайн-приложений — `manifest`. И в отличии от кейса с контролами, чтобы на своем уровне их добавить, придется копипаститить чуть ли не весь `page`.

**Comment by veged** [comment]
@tadatuta предлагаю "on demand" по прецедентам добавлять то, что действительно нужно нам и нашим пользователям
