### ISSUE TITLE
Should we describe in docs about autorequire if 'i-bem__dom' in deps?

### ISSUE THREAD

**Issue by qfox** [bem/bem-core#784]
I'm talking about #429 and https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/__dom/i-bem__dom.js#L1502

Unclear and not documented ;-(

**Comment by veged** [comment]
Why it should be documented if it's completely internal details? We discussed with @dfilatov and decided  that it's doesn't need to be documented since it should not affect any external usage.

**Comment by qfox** [comment]
@veged It affected me. I'm external. ;-) It should not but it does. That's why I've opened this issue.

**Comment by veged** [comment]
how it affect you?

**Comment by qfox** [comment]
I was confused why my module with elemInstance wasn't loaded as well as block. 

**upd**:
And that's because it doesn't depend directly on `i-bem__dom` but on block with that dependency.

**Comment by veged** [comment]
it's just a bug with elem instances :-( and honestly they don't stand well right now in v2 — we are looking forward to full support of them in v3

**Comment by qfox** [comment]
@veged Should we make an issue about that bug? ;-)

**Comment by veged** [comment]
no, we don't have plans to support elemInstances in v2 but we will make everything shiny and pretty in v3

**Comment by qfox** [comment]
@veged Can I help you with v3?

**Comment by veged** [comment]
sure https://github.com/bem/bem-core/labels/v3 ;-)
