### ISSUE TITLE
BEMTREE throws an error, but should return promise

### ISSUE THREAD

**Issue by apsavin** [bem/bem-core#785]
The following code:

``` js
block('my-block').content(function () {
    throw new Error('the error');
});
```

if we run `BEMTREE.apply()` it throws an error, but should return an error promise, so I need to write code like this:

``` js
try {
   promise = BEMTREE.apply(someData);
} catch(e) {
   promise = Vow.reject(e);
}
```

instead of just

``` js
promise = BEMTREE.apply(someData);
```

Can we do something with that?

P.S. Happy New Year, by the way!

**Comment by qfox** [comment]
:christmas_tree:

https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemtree#L99 here?

**Comment by veged** [comment]
it's should be done as part of #594

here https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemtree#L99 we can use

``` js
Vow.invoke(function() { return ctx.apply(); })
```

with proper handling of promise after
