### ISSUE TITLE
Get rid of `bem-tools`

### ISSUE THREAD

**Issue by blond** [bem/bem-core#790]
- Инструмент не развивается уже очень долго.
- В `bem-tools` не хватает инфраструктурных решений: `tmpl-specs`, `bh` и т.д.
- Нет никакой возможности проверять есть ли рассинхрон в конкретных технологиях между ENB и `bem-tools`, и тем более чинить этот рассинхрон.
- Хочется, чтобы пользователи библиотеки собирали её на тех же инструментах, тогда можно выявлять баги как в библиотеке, так и в инструментах.
- Появится больше возможностей поддерживать пользователей в вопросах сборки.

**Comment by qfox** [comment]
На чужой каравай ты рта не разевай!
А пораньше вставай и свой затевай ;-)

**Comment by blond** [comment]
@zxqfox, а теперь аргументы ;)

**Comment by qfox** [comment]
@andrewblond я про «модульную сборку». Мало аргументов? ;-)

**Comment by veged** [comment]
я против

**Comment by blond** [comment]
@veged, хорошо бы получить более развёрнутый ответ )

И, можно ещё рассматривать промежуточный вариант: объявить `bem-tools` **deprecated** и на все вопросы и реквесты отвечать, что она **deprecated**.

**Comment by qfox** [comment]
@andrewblond Думаю, сначала нужно иметь какую-то альтернативу для пользователей `bem-tools`, на которую им можно будет мигрировать. Не потому, что enb «не очень», а потому, что есть пользователи bem-tools, которые не хотят enb. Это я тебе и сказал про модульную сборку ;-)

**Comment by blond** [comment]
@zxqfox меня печалит не наличие пользователей который сидят на `bem-tools`, потому что сидели на `bem-tools` и их всё устраивало. А те, кто приходят и пытаются пользоватся `bem-tools` просто из-за названия, думая что это единственно верная тулза.

**Comment by qfox** [comment]
@andrewblond Есть хороший вариант — запилить модульный bem-tools с блекджеком.

**Comment by blond** [comment]
@zxqfox, ну и плюс то, что `bemhtml` и `bemtree` собираются время от времени по разному в ENB и `bem-tools` для одних и тех же версий `bem-core` из-за рассинхрона. Да и с другими технологиями тоже такое бывает.

> Есть хороший вариант — запилить модульный bem-tools с блекджеком.

Ни ктож не против, но на это нужно время. А рассинхрон в технологиях и пользователи, которые задают вопросы про `bem-tools` есть сейчас.

**Comment by qfox** [comment]
@andrewblond А совсем никак нельзя собирать какой-то полный бандл со всеми блоками в `bemthml`/`bemtree` двумя инструментами и сравнивать, чтобы рассинхрона не было?

**upd** Появится реализация на `gulp`/`shmulp` — еще больше рассинхрона будет. Имхо, лучше придумать, как автоматически синхронизировать, чем отказываться совсем. Потому что задача все равно встанет рано или поздно.

**Comment by tadatuta** [comment]
will support `ENB make` in https://github.com/bem/bem-tools/pull/569 and as so we can keep `bem-tools` support
