### ISSUE TITLE
Pointer(press/release) don't work in IE8

### ISSUE THREAD

**Issue by sipayRT** [bem/bem-core#792]
You can check it on https://github.com/bem/bem-core/tree/v2/common.blocks/jquery/__event/_type/jquery__event_type_pointerpressrelease.tests (don't forget to add es5-shim for IE8). In normal browsers you will see messages in console after clicking on the button, but not in IE8.

**Comment by sipayRT** [comment]
@tadatuta

**Comment by sipayRT** [comment]
@narqo

**Comment by hcodes** [comment]
Fix #797, #798
