### ISSUE TITLE
page.bemhtml: x-ua-compatible is broken

### ISSUE THREAD

**Issue by Murdalay** [bem/bem-core#794]
New <meta> is created instead of updating the existed one when changing `x-ua-compatible` field to arbitrary string. 
head: { elem: 'head', 'x-ua-compatible': false } just do nothing.

Is that a bug or something wrong with BEMJSON examples?

**Comment by narqo** [comment]
@tadatuta shouldn't it be fixed in v3 as well?

**Comment by tadatuta** [comment]
It should but I'm not sure it's a good idea to do so until https://github.com/bem/bem-core/pull/841
Otherwise we'll get quite a lot of conflicts.

**Comment by qfox** [comment]
@tadatuta Please, take a look and gimme further instructions.
