### ISSUE TITLE
i-bem.bemhtml: Nested mixes work inconsistent for mods of same block

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#807]
bemjson:

``` js
{
    block: 'b1',
    mix: { block: 'b2' }
}
```

**Case 1**
bemhtml:

``` js
block('b2').mix()({ block: 'b3', mods: { m1: 'v1' } });
```

the result will have `b3_m1_v1`.

**Case 2**
bemhtml:

``` js
block('b2').mix()({ block: 'b1', mods: { m1: 'v1' } });
```

the result won't have `b1_m1_v1`.

**Comment by veged** [comment]
are you sure about your test cases? seems like any `block('b2').mix()...` doesn't work for `{ block: 'b1', mix: { block: 'b2' } }`

**Comment by tadatuta** [comment]
@veged that's another issue which is filed [here](https://github.com/bem/bem-core/issues/806).

I wanted to show that when you try to mix **same** block with modifier in BEMHTML, the result is different from modifier of any other block.

**Comment by veged** [comment]
I just try to reproduce and fail with it. Could you please add tests to https://github.com/bem/bem-core/tree/v2/common.blocks/i-bem/i-bem.test.bemhtml ?

**Comment by tadatuta** [comment]
@veged I think you weren't able to reproduce because of this bug https://github.com/bem/bem-core/issues/873

**Comment by veged** [comment]
is it still relevant and not fixed in bem-xjst?

**Comment by tadatuta** [comment]
Closing in favour of https://github.com/bem/bem-xjst/issues/241
