### ISSUE TITLE
jquery__event_type_pointerpressrelease: Doesn't work in touch environments

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#819]
It seems that #797 has broken `pointerpress` and `pointerrelease` events on touch devices. 

`e.which` is the source of the problem :( It isn't defined in native touch events (e.g. `touchstart`), that are used inside pointer events polyfill. So no `pointerpress` / `pointerrelease` events are fired currently. 

Checked with XCode's iOS Emulator and Device Emulator in Chrome.

/cc @dfilatov

**Comment by dfilatov** [comment]
@hcodes could you fix the problem? It's a blocker issue for touch devices.

**Comment by hcodes** [comment]
Fixes #823 (v2), #824 (v3)
