### ISSUE TITLE
i-bem.bemhtml: Add helpers `addToArray` and `addMixTo`

### ISSUE THREAD

**Issue by veged** [bem/bem-core#820]
For avoid copy-paste of `[{ block: 'b1' }].concat(this.ctx.mix)` we can introduce two new helpers: for construct or convert to array with adding argument after and for inplace modification of `mix` field.

``` js
function addToArray(arr, item) {
    if(typeof arr === 'undefined') arr = [];
    else if(!Array.isArray(arr)) arr = [arr];
    var i = 1;
    while(item = arguments[i++]) arr.push(item);
    return arr
}

function addMixTo(obj, item) {
    var args = Array.prototype.slice.call(arguments, 1);
    args.unshift(obj.mix);
    obj.mix = addToArray(null, args);
    return obj;
}
```

Also need to think about similar helpers for other fields (like `js`, `attrs` and so on).

cc @dfilatov @narqo @mishanga 

**Update:** Discussed with @dfilatov and @narqo — decide to rename `addToArray` -> `addTo`

**Comment by qfox** [comment]
@veged addToArray → [push](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push)/[concat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat)?

**Comment by mishanga** [comment]
Не вижу смысла увеличивать размер базовых шаблонов.
Кроме того, задача выглядит более общей, она бы решилась, например, применением шаблонов к миксам.

**Comment by veged** [comment]
@zxqfox it's not exactly `push` even `concat`, so I prefer more independent name

**Comment by veged** [comment]
@mishanga это увеличение базовых шаблонов (не такое уж большое) с лихвой компенсируется на проектах за счёт избавления от копипаста

применение шаблонов к миксам это хорошо, но это же не снимет частой задачи "добавить микс"

**Comment by qfox** [comment]
@veged А не правильнее это реализовать в bh/bemhtml в виде хелперов?

**upd**: Спрашиваю, потому что https://github.com/bem/bh/blob/master/lib/bh.js#L51-L93 — примерно про то же.

**Comment by mishanga** [comment]
@zxqfox речь как раз про добавление хелперов. Ни в bemhtml, ни в bh сейчас такого нет. А опыт показывает, что пригодилось бы. Задача отрисовки элементов блока через другой блок оказалось довольно частой.

**Comment by qfox** [comment]
@mishanga Извините за глупый вопрос, но `i-bem.bemhtml` означает, что хелперы предлагается на уровне библиотеки? Если так, то не правильнее ли это сделать на уровне библиотек `bemhtml` (т.е. [`bem-xjst`](https://github.com/bem/bem-xjst)) и [`bh`](https://github.com/bem/bh)?

Честно говоря, вообще не понимаю, почему это обсуждается в рамках `i-bem.bemhtml`. Хотя [начинаю понимать](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L193).

**Comment by feugenix** [comment]
Кстати, а не будет ли логичней реализовать `addMixTo` так, чтобы она:
1. не меняла первый аргумент
2. возвращала новые миксы, а не obj? Я бы, например, использовал `addMixTo` как-то так:

```
block test, mix: this.addtoMix(this.ctx, { block: 'mixed' })
```

и не важно, есть ли в `this.ctx` миксы или нет.

**Comment by veged** [comment]
@zxqfox нюанс в том, что в BH нет такого понятия как "базовые шаблоны" (они зашиты в ядре, твоя ссылка про это), а вот для BEMHTML это всё как раз хранится не в ядре (https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L205)

**Comment by veged** [comment]
@feugenix 
я писал на основе реального кода из Серпа, мне показалось, что чаще используется именно примешивание к объекту

а для твоего кейса я подразумевал как раз `addToArray`:

``` js
block test, mix: this.addToArray(this.ctx.mix, { block: 'mixed' })
```

**Comment by qfox** [comment]
@veged Да я, как бы, не совсем дурак ;-) Код читать умею. Меня больше интересует, правильно ли это. Может быть лучше в BH реализовать расширения и перенести этот код хелперов в базовые шаблоны? По ощущениям подставлять в [this.utils](https://github.com/bem/bh/blob/master/lib/bh.js#L51) нужный prototype c хелперами не так уж и сложно.

**Comment by narqo** [comment]
@veged мне больше нраивится `this.push()` (вместо `this.addToArray`), потому что есть `this.extend()` (или `this.reapply()`) — хочется сохранить консистентность именований.

``` js
// TODO: arr может быть `undefined` или не массив
this.push = (arr, ...items) => Array.prototype.push.apply(arr, items)
```

`addToMix` выглядит слишком частным костылем, IMHO.

**Comment by qfox** [comment]
Предлагаю суффикс `To` для всех методов, которые первым аргументом принимают контекст (массив/объект), т.е.: `pushTo` или `arrayAddTo`, и `addMixTo` (как и было предложено). `concatTo`, на мой взгляд, более понятно, чем `push`/`pushTo`, потому что у `[].push` другой интерфейс, когда `concat` не меняет исходный объект и возвращает массив.

``` js
block test, mix: this.concatTo(this.ctx.mix, { block: 'mixed' })
block test, mix: this.union(this.ctx.mix, [{ block: 'mixed' }]) // lo-dash style
```

Можно попробовать разложить эти хелперы на более мелкие. Например,

``` js
block test, mix: this.toArray(this.ctx.mix).concat({ block: 'mixed' })
```

**Comment by veged** [comment]
@zxqfox про BH надо обсуждать с @mishanga ;-)

**Comment by mishanga** [comment]
В BH такой проблемы нет.

**Comment by veged** [comment]
Discussed with @dfilatov and @narqo — decide to rename `addToArray` -> `addTo`

**Comment by veged** [comment]
@mishanga как нет такой проблемы, если BEMJSON везде одинаковый? есть кейсы когда приходит неизвестный кусок и в него надо добавить миксы

**Comment by mishanga** [comment]
@veged в BH метод mix уже умеет резолвить такое: https://github.com/bem/bh/blob/master/lib/bh.js#L345

**Comment by veged** [comment]
@mishanga этот метод только про текущий контекст — он не поможет при построении bemjson (например при генерации вложенного контента)

**Comment by qfox** [comment]
@mishanga 

``` js
if (mix === undefined) {
    return this.ctx.mix;
}

if (force || !this.ctx.mix) {
    this.ctx.mix = mix;
} else {
    this.ctx.mix = Array.isArray(this.ctx.mix) ?
        this.ctx.mix.concat(mix) :
        [this.ctx.mix].concat(mix);
}
return this;
```

;-(

**Comment by tadatuta** [comment]
Closing in favour of https://github.com/bem/bem-xjst/issues/242
