### ISSUE TITLE
Add helper for getManyMod(elements, modName) 

### ISSUE THREAD

**Issue by mangin** [bem/bem-core#821]
Для получения значения модификатора документация предлагает использовать метод getMod.
Но если в функцию getMod возвращает значение модификатора, только первого элемента.

Для решения этой проблемы я написал( под вдохновением функции setMod) следующий хелпер:

``` javascript
function getManyMod(elements, modName) {
    var block = this,
        result = [];
    elements.each(function () {
        var elem = $(this);
        elem.__bemElemName = block.__bemElemName;
        var mod = block.getMod(elem, modName);
        result.push(mod);
    });

    return result;
}
```

http://jsfiddle.net/sjycs2gL/
Мне бы хотелось узнать: на сколько законно так делать?

**Comment by veged** [comment]
название не очень понятное, скорее в нём должно присутствовать что-то про `elems`

а вообще не очень понятен кейс применения такой функции в реальной жизни — можешь привести пример?

**Comment by mangin** [comment]
С названием согласен.

Кейс:
У меня есть следующий bem-json:

``` json
{
    "block": "layout",
    "content": [
        {"block": "layout", "elem": "col", "mods": {"id": "tiles"}},
        {"block": "layout", "elem": "col", "mods": {"id": "content"}},
        {"block": "layout", "elem": "col", "mods": {"id": "..."}}
    ]
}
```

Мне хотелось в декларации построить отображение:
id -> elem

А затем уже для каждого элемента в декларации блока назначать специфические модификаторы, причем эти модификаторы изменяются динамически.

P.S. Я понимаю, что этот метод весьма специфичен и скорее всего не нужен всем. Мне просто хочется узнать на сколько законно до определять поле __bemElemName у jquery коллекции.

**Comment by mangin** [comment]
На самом деле мне хотелось метод что-то вроде GroupElementsByMod

**Comment by veged** [comment]
я очень боюсь, что так и не понял пример до конца :-/ что именно нужно потом делать с колонками лейаута?

пока мне кажется, что всё это должно решаться кастомным предметноориентированным кодом (причём как можно ближе к реальной задаче, возможно ещё выше чем GroupElementsByMod), а не добавками в базовый блок

трогать `__bemElemName` кажется пока очень грубым залезанием в кишки

**Comment by mangin** [comment]
У меня есть общий много-колоночный layout для нескольких сайтов и single page application. 

В декларации блока layout я создал метод позволяющий по конфигурации вида id -> pos&width устанавливать модификаторы
grid__block_pos_Number и grid__block_width_number на колонку с определенным модификатором.

Затем код layout я поместил в базовую сборку блоков, а пользователи блока должны будут унаследоваться от layout и до определить у него более красивые функции вида:
1) Скрыть колонки с навигацией
2) Показать колонки с навигацией
и тд.

Какие колонки будут в лайауте мне не известно. Мне известно что структура html будет описываться следующим json:

``` json
{
    "block": "layout",
    "mix": [{
        "block": "grid",
        "mods": "grid_size_24"
    }],
    "content": [{
        "elem": "col",
        "mods": {
            "id": "tiles"
        },
        "mix": [{
            "mods": [{
                "block": "grid",
                "elem": "block"
            }]
        }]
    }, {
        "elem": "col",
        "mods": {
            "id": "content"
        },
        "mix": [{
            "mods": [{
                "block": "grid",
                "elem": "block"
            }]
        }]
    }, {
        "elem": "col",
        "mods": {
            "id": "..."
        },
        "mix": [{
            "mods": [{
                "block": "grid",
                "elem": "block"
            }]
        }]
    }]
}
```

Проблему можно было бы решить просто перетиранием колонок и перерисовки всего лайута, но мне такой подход не нравиться, так как придется повторно заполнять содержимое колонок.

Для решение поставленной задачи мне необходимо запомнить элементы grid__block и соответствие grid__block <-> layout_col_type_*.

**Comment by mangin** [comment]
Так же можно было сказать что каждая колонка это элемент вида layout_id, но тут засоряется namespace модификаторов, поэтому такой подход мне тоже не сильно по душе.

**Comment by veged** [comment]
какой-то странный bemjson:

``` js
        "mix": [{
            "mods": [{
                "block": "grid",
                "elem": "block"
            }]
        }]
```

**Comment by veged** [comment]
кажется, что всё должно описываться просто кастомным кодом через какой-нить `map` от набора элементов

**Comment by mangin** [comment]
Ой извиняюсь, за ошибку в бэм-json(у нас к сожалению, в команде пишут все на nunjucks)

``` json
"mix": [{
            {
                "block": "grid",
                "elem": "block"
            }
        }]
```

Я задачу и решил, через each(почти-тоже самое что и map), но:
1) map - возвращает в колбеке dom-element
2) При оборачивании $ естественно свойство .__bemElemName теряется, поэтому я его сам дописывал.

Было бы круто, если операции, которые возвращали не jquery коллекцию, а некоторую bem-jquery коллекцию с методами map or forEach, которые поддерживали свойство __bemElemName
