### ISSUE TITLE
Make jsdoc comments more strict with jscs-jsdoc

### ISSUE THREAD

**Issue by qfox** [bem/bem-core#828]
Partially based on #749 

It's possible to check many aspects of jsdoc content: available tags, methods accessibility (visibility), types format (validation), param names, redundant returns, etc.

I think we should use it to check jsdoc as well as code in lint task.

One little question: Is types format used in jsdoc notation based on standards?

v2+v3, or v3 only?

/cc @dfilatov

**Comment by veged** [comment]
we use some own treatment of types format based on jsdoc-toolkit

which standard of types do you mean? is it any good one that can be named "real standard"? in principle we could change our jsdoc

**Comment by qfox** [comment]
@veged At first `jsdoc-toolkit` is very old standard that should we changed to `jsdoc3` or something else. I'm not against `jsdoc-toolkit` or something, just noticing that. It's more about doc-generating tools than the pursuit of truth so if `jsd` uses `jsdoc-toolkit` — let's use what we use, no need to make monkey work ;-).

I'm just talking about checking that data automatically. We can do it easily with `jscs-jsdoc` without any changes. And for these purposes we need to know what we can describe in jsdoc, what we can't, how we should do it, how we shouldn't, etc.

So `jsdoc-toolkit` is a documented thing but the current set of tags is different. I can investigate which tags are really used (and how) if you can't provide it.

Also we can collect all that data and document each `jsdoc` tag affects.

At second some words about types.

I very like that type parser: http://kuniwak.github.io/jsdoctypeparser/ It's simple and powerful. Supports jsdoc3 and closure compiler format (the most common atm). So here I'm totally for it. `jscs-jsdoc` uses this library and checks type validity in jsdoc block comments.

p.s. I'm not against changing `jsdoc-toolkit` to `jsdoc3` (atm widely used WITH `closure compiler` tag set) but what it worth? `jsdoc3` tag set already exists in `jsdoc` so the cost of migration shouldn't be big.

**Comment by veged** [comment]
we don't use jsdoc-toolkit, just have legacy format for type from it ;-)

could you show any good documentation for types format? can't find any on http://kuniwak.github.io/jsdoctypeparser/

**Comment by qfox** [comment]
1. http://usejsdoc.org/tags-type.html
2. https://developers.google.com/closure/compiler/docs/js-for-compiler#types
3. https://github.com/hegemonic/catharsis/blob/master/test/specs/jsdoc/jsdoc.js#L83

And also https://github.com/Kuniwak/jsdoctypeparser/issues/6 about `{module: file}` format.

**Comment by qfox** [comment]
I can try to fix them all later. Do we need it for v3 or just for v2?

**Comment by veged** [comment]
@zxqfox wait ;-) we need to discuss and select one of those standards before and ensure that https://github.com/bem/jsd/ and https://github.com/bem/jsd-plugins-bem/ support them

**Comment by qfox** [comment]
@veged Pro tip: use free stable open source library for parsing jsdoc-types ;-)

Np. Sure you need time.

**Comment by veged** [comment]
@zxqfox yep... **write** and use ;-)

**Comment by qfox** [comment]
@veged Why you don't like [jsdoctypeparser](https://github.com/Kuniwak/jsdoctypeparser)? Almost [Battle hardened](https://www.npmjs.com/package/jsdoctypeparser) ;-)

**Comment by qfox** [comment]
@veged I see some of jsdoc-blocks uses exclamation-star `/*!` while the most of them uses standard double star `/**` as opener.

```
$ grep '\/\*\*' ./common.blocks/ -r | wc -l
400
$ grep '\/\*!' ./common.blocks/ -r | wc -l
15
```

Should we replace `/*!` to `/**` or it's a special jsdocs?

**Comment by qfox** [comment]
Oh. It was `v2`.

For `v3` it looks like:

```
$ grep '\/\*\*' ./common.blocks/ -r | wc -l
375
$ grep '\/\*!' ./common.blocks/ -r | wc -l
2
```

So the answer will be to replace. ;-) Correct me if I'm wrong.

**Comment by sipayRT** [comment]
@zxqfox it was made to ignore parsing of these jsDoc because we can't parse such file-structure with jsd

**Comment by qfox** [comment]
@sipayRT That makes sense. Thanks a lot!
