### ISSUE TITLE
bem-tools: Build bemtree with Vow inlined

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#832]

**Comment by apsavin** [comment]
I hope, there will be an option for users to avoid such inlining.

**Comment by tadatuta** [comment]
@apsavin can you describe cases when you don't need `Vow` with `BEMTREE`?

**Comment by apsavin** [comment]
I always need Vow with BEMTREE, but why we need to inline it? I just `require` BEMTREE file and Vow inside BEMTREE is the same Vow that all other blocks use, from `ym` modules system.

**Comment by tadatuta** [comment]
Example of current state

``` js
bemtreeTemplate = fs.readFileSync(path.join(pathToBundle, bundle + '.bemtree.js'), 'utf-8'),
        context = vm.createContext({
            console: console,
            Vow: Vow,
            qs: Querystring,
            require: require
        });

    vm.runInContext(bemtreeTemplate, context);
```

**Comment by tadatuta** [comment]
TODO: find some more examples to summarise

**Comment by apsavin** [comment]
@tadatuta should I give you an example of how I use it?
I just build a node.js + bemtree so I have a file like this

``` js
require('path/to/ym');
require('path/to/some/block');
// ...
require('./bundleName.bemtree.js');
```

and then I'm able to use bemtree:

``` js
modules.define('some-block', ['BEMTREE'], func...)
```

so I don't use `vm` and don't use global variables into BEMTREE.

**Comment by tadatuta** [comment]
@apsavin how do you handle cache? when node.js file is changed won't it trigger BEMTREE templates recompilation?

**Comment by narqo** [comment]
@tadatuta we use [luster-guard](https://github.com/nodules/luster-guard) for such tasks (but of course, this is not the only solution)

**Comment by tadatuta** [comment]
@narqo I don't understand how can it help when bemtree and node.js code is in the same bundle.

**Comment by apsavin** [comment]
@tadatuta I use bem-tools + gulp + gulp-watch and I see no problem with templates' recompilation.

**Comment by dfilatov** [comment]
All issues about bem-tools are obsolete now.
