### ISSUE TITLE
circular dependences if using both desktop and touch layers

### ISSUE THREAD

**Issue by Guria** [bem/bem-core#835]
```
Circular dependence has been detected: "i-bem__dom_init -> app-header -> i-bem__dom -> jquery -> jquery -> jquery -> jquery -> jquery__config -> ua -> i-bem__dom"
```

**Comment by veged** [comment]
You can't use both desktop and touch layers. It's just not supposed to work.

**Comment by veged** [comment]
If you need to adapt your runtime for any platform you should build both desktop and touch bundles and include to html just one of them (based on some server-side or browser-side checks).

**Comment by Guria** [comment]
By the way, I have made some research tonight and found cause of circular dependencies. The reason so miserable in my opinion, I don't know why you don't want to fix it.
- on desktop level `jquery__config` depends on `ua` block for `msie` version detection to override right version of jquery to be loaded
- on touch level `ua` block depends on `jquery` directly and through `i-bem__dom` dependency because of reach detection parameters and providing a way to get some feature detection by setting mods classes on `body` tag

I was able to solve an issue on project level, by redefining deps in `jquery` block and putting `jquery__config` definition inside `jquery.js`:

``` js
// prevent using `jquery__config` from library
({ noDeps : { elem : 'config' } })
```

``` js
// provide `jquery__config` inside jquery.js on project level
modules.define('jquery__config', function(provide) {
var msie = /(msie) ([\w.]+)/.exec(navigator.userAgent.toLowerCase());
provide(/** @exports */{
    /**
     * URL for loading jQuery if it does not exist
     */
    url : (msie && (parseInt(msie[2], 10) < 9))?
      '//yastatic.net/jquery/1.11.2/jquery.min.js' :
      '//yastatic.net/jquery/2.1.3/jquery.min.js'
});
});
```

For library I suppose to discard usage of `ua` block in `jquery__config` on desktop level and replace it with inline check of msie version like in my example.

**Comment by veged** [comment]
we wan't to fix it not because its big and hard, but because it about unplanned way of usage — we doesn't suppose build desktop and touch levels in one runtime and it may bring any other unpredictable problems, furthermore, we even don't test it anyway

**Comment by Guria** [comment]
What you can say about suggested solution? I think it is pretty unobtrusive. You wouldn't have to declare support of building both levels in one runtime if you implement it. At the same time this particular issue would be solved.
I have checked current state of both layers. Touch level works fine on top of desktop. Let developer decide whether to use unsupported but working way or stick to only declared use cases.

**Comment by veged** [comment]
also — replace `ua` block with inline regexp check of UserAgent is too hacky — the purpose of `ua` block is incapsulating all this details

**Comment by veged** [comment]
I advise you to stop until it's too late — what you calling "unsupported but working way" in reality is "unsupported and scrap-in-the-most-unexpected-moment way"

I do not want put as in situation in future when we discuss again about some cases when it will be broken

**Comment by Guria** [comment]
I see your point about support and even agree with it. I am also worried about inconsistency in dependencies in layers despite the fact that it doesn't supposed to be used together. I have a feeling that having opposite dependencies is not right, moreover in layers within one library.

It can lead to inconsistency in libraries built on top of `bem-core` which blocks would have more complex dependencies. Developer would have a headache to  support block which should work equal on top of desktop and touch layers.

Sorry, if I wasting your time, but I feel that I should say it anyway.

Another suggestion is to move out `jquery__config` outside of `jquery` block if inline check is too hacky for you. It base on some considerations:
- `jquery` block doesn't need `ua` block. It is only needed for it's `__config` element only on `desktop` level
- semantically `jquery` block is not a jquery but it is loader of jquery.

Full solution would be:
- `common.blocks/jquery-loader/jquery-loader.js` - loads jquery if it absent and provides it into ymodules
- `common.blocks/jquery-loader/__config/jquery-loader__config.js` - sets default uri to load
- `common.blocks/jquery/jquery.deps.js` - depends on `jquery-loader` and its `__config` element. it wouldn't lead to circular dependencies in ymodules
- `common.blocks/jquery/__event/_type` - leave pointer events polyfills in `jquery` block
- `desktop.blocks/jquery-loader/__config/jquery-loader.js` - now could have save dependency on `ua` block. redefines uri to load jquery for old IE
- `desktop.blocks/jquery/__event/_type` - leave `winresize` event for IE in `jquery` block
- `project.level/jquery/jquery.js` - here developer could place local jquery version

Pros:
- for developers depending on jquery stays simple as `shouldDeps: 'jquery'`
- consistent js dependencies for blocks across the library
- shouldn't affect existing projects

Cons:
- sensible changes in library: one new block, removed element from existing block
- could affect existing projects

Since that I suggest:
- for `v2` use inline version check or leave it as is
- for `v3` introduce solution described above

I want to emphasise another time: I am worry not about using both layers together, but about consistency in js dependencies for future easier support.
