### ISSUE TITLE
i-bem-dom: Think about more predictable naming for find* methods

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#846]
Currently we have:
- `Block#findBlocksOutside()` which returns all ancestor blocks
- `Block#findBlocksInside()` which returns all descendant blocks and self
- `Block#findBlocksOn()` which returns all sibling blocks

The is an opinion that the behaviour of `findBlocksOutside` confuses users. 

We can think about new naming notation for `find`-methods.

**Comment by narqo** [comment]
After a small discussion \w @veged and @dfilatov possible names might be: `findParentsBlocks`, `findChildBlocks`, `findMixedBlocks`

**Comment by tadatuta** [comment]
if there's `s` in findParent**s**Blocks, it should be `findChildrenBlocks` or otherwise `findParentBlocks`.

and don't you want to strip `Blocks` part at all?

**Comment by dfilatov** [comment]
We can't strip `Blocks` part because we have `findElem*` methods as well.

**Comment by qfox** [comment]
@narqo @veged @dfilatov Guys, please don't. Think — ok. Just stop renaming methods each major release.

These changes are not really necessary to make library more user-friendly.

Anyone who want these naming can easily create 100b file with assigning Block.protytype.findBlockInside to .findChildren or .findAncestors, or find42, whatever he like. And there's no problem with that. Can you think once about of UX of 90% users?

**Comment by narqo** [comment]
While we were working on #581 we decided that these changes are necessary.
