### ISSUE TITLE
npm install doesn't work on clean checkout

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-core#851]
I get an error while I'm trying to run `npm i` on clean checkout:
`npm ERR! peerinvalid Peer mocha-phantomjs@3.5.0 wants phantomjs@~1.9.1`

npm version: 2.1.2

cc @tadatuta

**Comment by qfox** [comment]
npm version: 1.4.28 works fine.
Need to fix `~`

**Comment by qfox** [comment]
Something tells me that it will be fixed with #847

**Comment by qfox** [comment]
https://github.com/enb-bem/enb-bem-specs/blob/v0.2.3/package.json#L35 — that's a trouble in old version of enb-bem-specs that causes this with npm 2.x.

cc @andrewblond Your turn!

**Comment by blond** [comment]
> https://github.com/enb-bem/enb-bem-specs/blob/v0.2.3/package.json#L35 — that's a trouble in old version of enb-bem-specs that causes this with npm 2.x.

This problem was fixed in newer versions of `enb-bem-specs`.

**Comment by qfox** [comment]
@andrewblond In common, I suggest to drop this line since you're using package with peer-dependency that already contain right version of `phantomjs`. You have no real profit explicitly declaring version twice.

**Comment by dfilatov** [comment]
@andrewblond If the problem is fixed, could you update `enb-bem-specs` to a corresponding version?

**Comment by blond** [comment]
Fixed in https://github.com/bem/bem-core/pull/863
