### ISSUE TITLE
i-bem__dom: append, prepend, etc won't work with string content

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#852]
All i-bem__dom helpers for adding some content to DOM have such signature:

``` js
/**
     * @param {jQuery} ctx Root DOM node
     * @param {jQuery|String} content Content to be added
     * @returns {jQuery} New content
     */
```

but it turned out that it's impossible to provide string as content because there's `$(content)` under the hood. E.g.:

``` js
    append : function(ctx, content) {
        return this.init($(content).appendTo(ctx));
    }
```

// cc @dfilatov

**Comment by tadatuta** [comment]
@dfilatov Dima, will it be ok if I'll fix it with

``` js
append : function(ctx, content) {
    return this.init($(content[0] === '<' ? content : [content]).appendTo(ctx));
}
```

or is it better to always use

``` js
$.parseHTML(content, null, true)
```

instead?

**Comment by qfox** [comment]
Html can be "yolo&lt;swag&gt;" so probably you need to search for '<', but still it's strange case.

**Comment by tadatuta** [comment]
@zxqfox the reason is exactly to find cases like `yolo<swag>` and looks like `$.parseHTML()` was implemented just for it.

**Comment by dfilatov** [comment]
@tadatuta `$.parseHTML` looks perfect. But don't forget to check for `string` before apply it.

**Comment by dfilatov** [comment]
@tadatuta Hmm. I've thought about perfomance for `$.parsetHTML` for big trees. Isn't there a reason why jQuery doesn't apply it?

**Comment by tadatuta** [comment]
@dfilatov I think we can check not just for `typeof content === 'string'` but also for `content[0] !== '<'` and in such cases we don't need to worry about performance, do we?

**Comment by qfox** [comment]
@tadatuta `content[0] !== '<'` vs `content.indexOf('<') !== -1`?

**Comment by tadatuta** [comment]
@zxqfox as we discussed above, we still need to call `$.parsetHTML()` in case of `yolo<swag>` so just `content[0] !== '<'`.

**Comment by qfox** [comment]
@tadatuta I don't understand how you can cover all cases with `content[0] !== '<'`:
- `String`
- `<swag>yolo</swag>`
- `<swag /><yolo />`
- `String<swag />`
- `<swag />String`
  etc.

**Comment by tadatuta** [comment]
@zxqfox Oh, I thought that if anything starting with an HTML element is passed, jQuery will do the rest by itself. But that's not so. That means check for `<` is useless :(

**Comment by tadatuta** [comment]
@dfilatov 

``` js
var html = $('body').html();

console.time('parse');
$.parseHTML(html);
console.timeEnd('parse');
// parse: 43.054ms 
```

VS.

``` js
var html = $('body').html();

console.time('parse');
$('<fake>' + html + '</fake>');
console.timeEnd('parse');
// parse: 51.610ms 
```

**Comment by qfox** [comment]
@tadatuta Ehm? Why not:

```
$($.parseHTML(html));
```

?

**Comment by dfilatov** [comment]
@tadatuta ok, let's use `$.parseHTML`

**Comment by tadatuta** [comment]
@zxqfox you are right, but looks like that doesn't matter:

``` js
var html = $('body').html();

console.time('parse');
$($.parseHTML(html));
console.timeEnd('parse');

console.time('fake');
$('<fake>' + html + '</fake>');
console.timeEnd('fake');

// parse: 25.955ms VM105:6
// fake: 34.319ms VM105:10

var html = $('body').html();

console.time('parse');
$($.parseHTML(html));
console.timeEnd('parse');

console.time('fake');
$('<fake>' + html + '</fake>');
console.timeEnd('fake');

// parse: 48.992ms VM106:6
// fake: 56.978ms VM106:10

var html = $('body').html();

console.time('parse');
$($.parseHTML(html));
console.timeEnd('parse');

console.time('fake');
$('<fake>' + html + '</fake>');
console.timeEnd('fake');

// parse: 22.828ms VM107:6
// fake: 30.578ms 
```

still not sure that such kind of test is good enough.

**Comment by qfox** [comment]
:+1:

**Comment by tadatuta** [comment]
#889

**Comment by deeonis** [comment]
Need port to v3
