### ISSUE TITLE
events.Emitter.emit() method ignores data field

### ISSUE THREAD

**Issue by Murdalay** [bem/bem-core#855]
If the second argument is provided to `events.Emitter.emit()` it just do nothing instead of supplying it value to e.data field.

**Comment by dfilatov** [comment]
The second argument passed to `emit` is available as the second argument within a callback.

``` js
var data1 = { a : 1 };
emitter.on('click', function(e, data) {
   data === data1; // true
});
emitter.emit('click', data1);
```

But `e.data` is the data passed while `on` method is called:

``` js
var data1 = { a : 1 };
emitter.on('click', data1, function(e) {
   e.data === data1; // true
});
emitter.emit('click');
```

This behaviour was taken from jquery event system.
