### ISSUE TITLE
jquery__event_type_winresize: Fix typo

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#862]
@dfilatov Dima, we have https://github.com/bem/bem-core/blob/v2/desktop.blocks/jquery/__event/_type/jquery__event_type_winresize.js in `bem-core` but it looks like it's not used anyway. Can't we just remove it?

**Comment by dfilatov** [comment]
It's used on projects which want to have proper resize in IE.

**Comment by tadatuta** [comment]
@dfilatov in this case should we replace 'ie' [here](https://github.com/bem/bem-core/blob/v2/desktop.blocks/jquery/__event/_type/jquery__event_type_winresize.js#L7) with 'msie' as it's used in [ua](https://github.com/bem/bem-core/blob/v2/desktop.blocks/ua/ua.js#L13)?

**Comment by dfilatov** [comment]
@tadatuta yep, definitely

**Comment by hcodes** [comment]
Потестировал:
Нужно для IE8 и ниже, хотя проблемы могут быть и в IE9 и выше, если выбрать `Document Mode` - `Internet Explorer 8 standarts`.

Можно добавить условие (про `IE=Edge` знаю):

```
if(ua.msie && document.documentMode <= 8) {
}
```

и поправить TODO-комментарий.

 https://msdn.microsoft.com/en-us/library/ie/ms536959%28v=vs.85%29.aspx

**Comment by narqo** [comment]
> [..] и поправить TODO-комментарий

@hcodes можете с @tadatuta доделать #864 и #865?

**Comment by hcodes** [comment]
@narqo доделал.
