### ISSUE TITLE
Move jscs rules to preset @v2

### ISSUE THREAD

**Issue by qfox** [bem/bem-core#875]
Refs: https://github.com/bem/bem-components/issues/1220, https://github.com/bem/bem-components/pull/1221

**Comment by qfox** [comment]
@tadatuta Since bem/bem-components#1221 was merged probably we should do it here too.

**Comment by qfox** [comment]
cc @veged @narqo @dfilatov

**Comment by tadatuta** [comment]
sounds rather reasonable ;)
