### ISSUE TITLE
Wrong promises handling in bemhtml

### ISSUE THREAD

**Issue by apsavin** [bem/bem-core#884]
### How to reproduce:
1. Create new project with project-stub and `bem make`
2. Create `desktop.bundles/index/index.node.js` with the following content:

``` js
var Vow = require('../../libs/bem-core/common.blocks/vow/vow.vanilla.js'),
    BEMHTML = require('./index.bemhtml.js').BEMHTML;

var bemjson = {
    block: 'footer',
    content: 'footer content goes here'
};

console.log(BEMHTML.apply(bemjson));

bemjson = {
    block: 'footer',
    content: Vow.resolve('footer content goes here')
};

console.log(BEMHTML.apply(bemjson));

bemjson = {
    block: 'footer',
    content: Vow.resolve({
        block: 'footer',
        content: 'footer content goes here'
    })
};

console.log(BEMHTML.apply(bemjson));

bemjson = {
    block: 'footer',
    content: Vow.resolve({
        block: 'footer',
        content: Vow.resolve('footer content goes here')
    })
};

console.log(BEMHTML.apply(bemjson));
```
1. Run `node desktop.bundles/index/index.node.js`
### Actual result:

```
<div class="footer">footer content goes here</div>
<div class="footer">footer content goes here</div>
<div class="footer"><div class="footer">footer content goes here</div></div>
<div class="footer"><div class="footer"><div></div></div></div>
```
### Expected result:

```
<div class="footer">footer content goes here</div>
<div class="footer">footer content goes here</div>
<div class="footer"><div class="footer">footer content goes here</div></div>
<div class="footer"><div class="footer">footer content goes here</div></div>
```

**Comment by tadatuta** [comment]
cc @dfilatov

**Comment by dfilatov** [comment]
How long has BEMHTML been supporting promises? I know nothing about that.

**Comment by apsavin** [comment]
@dfilatov see [here](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L316)
More than a [year](https://github.com/bem/bem-core/commit/be08164f91f503f81389a3f55ea0cb4a33bfc4b8) at least.
cc @veged

**Comment by narqo** [comment]
~~@apsavin what version of `vow` do you use?~~

Ok, it seems that this is a bug in new `applyNext` internal mechanics. Looks like internal guards don't reset in such cases.

**Comment by apsavin** [comment]
I'm glad that you've found the cause. Hope to see it fixed soon, the bug is really very nasty. Sorry, I'm without pull request today.

**Comment by apsavin** [comment]
Can somebody set the "bug" label?

**Comment by veged** [comment]
@apsavin sorry, it's more complicated than I suppose — we need to integrate this https://github.com/veged/xjst/pull/41

**Comment by apsavin** [comment]
Oh, I see... Thanks!

**Comment by apsavin** [comment]
Any news here?

**Comment by veged** [comment]
yep — we wait for https://github.com/bem/bem-core/pull/899

**Comment by apsavin** [comment]
Guys, I really need this fix. Can I do something to speed up it?

**Comment by veged** [comment]
should be fixed — reopen in case of problems, pls
