### ISSUE TITLE
Missed applyCtx for doAsync result (bemtree)

### ISSUE THREAD

**Issue by apsavin** [bem/bem-core#885]
### Steps to reproduce:
1. Create a project based on project-stub
2. Add `bemtree` technology into the build process
3. Add `desktop.blocks/footer/footer.bemtree` and `desktop.blocks/content/content.bemtree`:
   
   ``` js
   block('content')(
       content()(function () {
           return 'bla';
       })
   );
   
   block('footer')(
       content()(function () {
           return this.doAsync(function () {
               return {
                   block: 'content'
               };
           })
       })
   );
   ```
4. Add `desktop.bundles/index/index.node.js`
   
   ``` js
   Vow = require('../../libs/bem-core/common.blocks/vow/vow.vanilla.js');
   var BEMTREE = require('./index.bemtree.js').BEMTREE;
   
   BEMTREE.apply({
       block: 'footer'
   }).then(function (res) {
       console.log(res);
   });
   ```
5. `bem make` and run `node desktop.bundles/index/index.node.js`
### Actual result:

``` js
{ block: 'footer',
  mods: {},
  content: 
   { _value: { block: 'content' },
     _status: 1,
     _fulfilledCallbacks: undefined,
     _rejectedCallbacks: undefined,
     _progressCallbacks: undefined } }
```
### Expected result:

``` js
{ block: 'footer',
  mods: {},
  content: 
   { _value: { block: 'content', mods: {}, content: 'bla' },
     _status: 1,
     _fulfilledCallbacks: undefined,
     _rejectedCallbacks: undefined,
     _progressCallbacks: undefined } }
```

**Comment by apsavin** [comment]
Am I wrong?
Do I need to always write like this:

``` js
block('footer')(
    content()(function () {
        return this.doAsync(function () {
            return applyCtx({
                block: 'content'
            });
        })
    })
);
```

If so, why?

**Comment by narqo** [comment]
> [..] If so, why?

Because you just can't auto call `apply` on any value that is fulfilled (or rejected) from `doAsync` promise. It's up to you to know how to handle this value. 

Some common usecase that we had was: get some `data` with `doAsync` call; then call `apply('specific-custom-mode', { data : data })` if promise was fulfilled, or `apply('error', { err : e })` in other case.

**Comment by apsavin** [comment]
Well, my example is not 100% correct. You're right, we can't do this with doAsync method. 

I have extended bemtree with method `get`, it works like this:

``` js
block('footer')(
    content()(function () {
        return this.get('some-route', successCallback, errBack);
    })
);
```

So it would be useful for me to call applyCtx for everything that come from successCallback. That's why I need a way to understand, was ctx applied already or not (#886).
Now I need to write:

``` js
block('footer')(
    content()(function () {
        var someBlock = applyCtx({
                block: 'some-block'
        });
        return this.get('some-route', function (data) {
                return [applyCtx({
                        block: 'x',
                        data: data
                }), someBlock];
        }, errBack);
    })
);
```

or, in another case:

``` js
block('footer')(
    content()(function () {
        return this.get('some-route', function (data) {
                return applyCtx([{
                        block: 'x',
                        data: data
                }), {block: 'some-block'}]);
        }, errBack);
    })
);
```

That's how I will be able to write with a way to understand that ctx already applied:

``` js
block('footer')(
    content()(function () {
        var someBlock = applyCtx({
                block: 'some-block'
        });
        return this.get('some-route', function (data) {
                return [{
                        block: 'x',
                        data: data
                }, someBlock];
        }, errBack);
    })
);
```

second case:

``` js
block('footer')(
    content()(function () {
        return this.get('some-route', function (data) {
                return [{
                        block: 'x',
                        data: data
                }, {block: 'some-block'}];
        }, errBack);
    })
);
```

I don't want to force BEMTREE users to think too much when to use `applyCtx`. I want to say: "guys, if you need to get the result of a block template before some async manipulations - use `applyCtx`. It's all that you need to know".

**Comment by veged** [comment]
@apsavin we have no idea how to implements something that fulfilled your case :-( can you provide any PR?

**Comment by apsavin** [comment]
Well, as @narqo mentioned above, I was not correct in my examples, so we can continue discussion in #886.
