### ISSUE TITLE
We need some flag to understand was a block rendered already or not (bemtree)

### ISSUE THREAD

**Issue by apsavin** [bem/bem-core#886]
### Steps to reproduce:
1. Create a project based on project-stub
2. Add `bemtree` technology into the build process
3. Add `desktop.blocks/footer/footer.bemtree` and `desktop.blocks/content/content.bemtree`:
   
   ``` js
   block('content')(
       content()(function () {
           console.log('content bemtree template called');
           return 'bla';
       })
   );
   
   block('footer')(
       content()(function () {
           var contentBlock = applyCtx({
               block: 'content'
           });
           return [
               contentBlock,
               'asdasd'
           ];
       })
   );
   
   ```
4. Add `desktop.bundles/index/index.node.js`
   
   ``` js
   Vow = require('../../libs/bem-core/common.blocks/vow/vow.vanilla.js');
   var BEMTREE = require('./index.bemtree.js').BEMTREE;
   
   BEMTREE.apply({
       block: 'footer'
   }).then(function (res) {
       console.log(res);
   });
   ```
5. `bem make` and run `node desktop.bundles/index/index.node.js`
### Actual result:

content template called twice:

``` js
content bemtree template called
content bemtree template called
{ block: 'footer',
  mods: {},
  content: [ { block: 'content', mods: {}, content: 'bla' }, 'asdasd' ] }
```
### Expected result:

content template called once:

``` js
content bemtree template called
{ block: 'footer',
  mods: {},
  content: [ { block: 'content', mods: {}, content: 'bla' }, 'asdasd' ] }
```

**Comment by narqo** [comment]
Why can't you use `block('content').match(!this._wasRendered)` guard here?

**Comment by apsavin** [comment]
Of course, I can. But I don't want to use it for every block on one hand and don't want to think was the guard used for particular block (when I use it), on another hand.
This issue is related to #885. We can't auto-apply ctx to the result of doAsync while we have not such auto-guard.

**Comment by narqo** [comment]
I'm not sure I understand, how this relate to "autoapplying" in asynchronous calls. 

In your particular example above calling `applyCtx({ block : 'content' })`, and returning `{ block : 'content' }` within content mode of block `footer` may lead to different results in general, as 

~~~
block('content')(
    content()(function () {
        console.log('content bemtree template called');
        return 'bla';
    })
);

block('footer')(
    content()(function () {
        var contentBlock = applyCtx({
            block: 'content'
        });
        return [
            contentBlock,
            'asdasd'
        ];
    })
);
~~~

**Comment by narqo** [comment]
Oops, wrong issue. Removed my wrong comment

**Comment by veged** [comment]
@apsavin looks like completely logical behaviour since you call applying twice (directly and indirectly) — can you provide any PR with possible ways to handle it?

**Comment by apsavin** [comment]
@veged let's discuss the issue before anybody will write any code.

There is a problem in BEMTREE: it's hard to distinguish input from output. I think, the only way to distinguish is to add some reserved parameter into ctx during templating.

for example, now:

``` js
// input
{block: 'bla'}
// output
{block: 'bla', content: [{block: 'bla', elem: 'item', content: 'x'}]}
```

with reserved parameter:

``` js
// input
{block: 'bla'}
// output
{block: 'bla', content: [{block: 'bla', elem: 'item', content: 'x'}], _applied: true}
```

pros:
- we can auto-apply ctx in cases like discussed in #885 

cons:
- we have reserved parameter. I think, it's obvious why it's bad.

What do you think about it?

**Comment by veged** [comment]
I think that @narqo says about right way — `block('content').match(!this._wasRendered)` will do exactly what needed and doesn't produce any "magic" underhood behaviour

**Comment by apsavin** [comment]
It's strange to write `block('content').match(!this._wasRendered)` for _all_ blocks, but I see, that it's better to handle this on my part.
