### ISSUE TITLE
page, ua: some templates defined in touch level would be useful for desktop services opened on mobile device

### ISSUE THREAD

**Issue by Guria** [bem/bem-core#887]
@veged in #835 supposed:

> If you need to adapt your runtime for any platform you should build both desktop and touch bundles and include to html just one of them (based on some server-side or browser-side checks).

Server-side option not easy and sometimes not able for project that involves only static html. For client-side solution developer have to get deeper knowledge about how to achieve getting static page based on different bundles. Also it appliable only for assets and not for html.

Therefore, we couldn't generate html page which will have corresponding entries in `<head>` for both `touch` and `desktop` platforms from library. See also [forum post](https://github.com/bem/bem-forum-content-ru/issues/263) for referrence.

**Comment by veged** [comment]
sorry, but it's just completely impossible with current architecture to build both levels touch and desktop together in same runtime

for check on server-side you can use https://tech.yandex.ru/detector/

**Comment by tadatuta** [comment]
@veged actually the question was as follows: https://github.com/bem/bem-forum-content-ru/issues/263#issuecomment-76726909

The templates for `ua` and `page` are quite reasonable on desktop service opened on mobile and we could think about merging them together at least partially.

**Comment by veged** [comment]
@tadatuta if we need to move some templates for icon to common level, ok then (but issue title should be more specific)

other templates from head should be discussed

anyway current issue title not about that ;-)

**Comment by veged** [comment]
could anyone provide more details: what templates defined in touch level should be moved to common?

**Comment by tadatuta** [comment]
All of them, actually. There's no need in touch level at all.

**Comment by veged** [comment]
as discussed today with @tadatuta — wont fix
