### ISSUE TITLE
i-bem: setMod should convert non-boolean value to string 

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#890]
``` js
block.setMod('blah', 2);
console.log(typeof block.getMod('blah'));  // number

block.setMod('blah', '2');
console.log(typeof block.getMod('blah'));  // string
```

Current behaviour looks weird and it seems that any value in the example above may fire several onSetMod-handlers (see [buildModFnName()](https://github.com/bem/bem-core/blob/6ce978f653cd84a7a490e654d6c6dbf378cb7546/common.blocks/i-bem/i-bem.vanilla.js#L53-L59)).

And the same goes to `hasMod`

**Comment by qfox** [comment]
:+1:
