### ISSUE TITLE
ua, touch: `screenSize` couldn't get value `normal`

### ISSUE THREAD

**Issue by Guria** [bem/bem-core#894]
https://github.com/bem/bem-core/blob/v2/touch.blocks/ua/ua.js#L155
It seems an error in conditions. `screenSize` couldn't get value `normal`

**Comment by hcodes** [comment]
normal: screen.width = 320

**Comment by Yeti-or** [comment]
`normal` means that you have an iPhone =)

**Comment by Guria** [comment]
@hcodes oh sorry, didn't noticed that. Thought that `normal` should be some range.
@YetiOr :+1:
