### ISSUE TITLE
Feedback for "Быстрый старт по BEMHTML"

### ISSUE THREAD

**Issue by raining** [bem/bem-core#896]
Напишем шаблон для блока hello в файле desktop.blocks/hello/hello.bemhtml:
https://ru.bem.info/technology/bemhtml/v2/intro/#Шаг-4-Написать-шаблон-приветствие-по-образцу

``` javascript
block('hello').content(function() {
    return ['Hello, ', this.ctx.name, '!'];
});
```

В этом и следующем примере ошибка в синтаксисе - нужно писать не 

``` javascript
content(function(){...})
```

а 

``` javascript
content()(function(){...})
```

**Comment by raining** [comment]
Ответ - в файле ошибка в синтаксисе примера - мода content не принимает аргументов, нужно писать не 
```javascript
content(function(){...})
```  
а 
```javascript
content()function(){...}
```

**Comment by gela-d** [comment]
@innabelaya Инна, посмотри, пожалуйста.

**Comment by innabelaya** [comment]
Corrected in https://github.com/bem/bem-core/commit/09d4d7f19d9fa077a919de2e12082f0161bac3b4
