### ISSUE TITLE
Stop using jshint-group in favour of latest jshint

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#900]
Since [jshint@2.50](https://github.com/jshint/jshint/releases/tag/2.5.0), which was released almost a year ago, it is possible to override particular lint rules for a subset of files, based on fsglob matching (see jshint release notes for examples). 

We may try to migrate to the latest version of jshint. This changes provide proper code linting, as jshint is supported by the wide range of code editors, including Vim and Idea.

**Comment by qfox** [comment]
:+1:
But how?

**Comment by narqo** [comment]
"How" what?

**Comment by dfilatov** [comment]
Closed in favour of #1246
