### ISSUE TITLE
Update deps in package.json

### ISSUE THREAD

**Issue by hcodes** [bem/bem-core#902]

**Comment by veged** [comment]
which deps should be updated?

**Comment by hcodes** [comment]
https://david-dm.org/bem/bem-core#info=dependencies&view=table
https://david-dm.org/bem/bem-core#info=devDependencies&view=table

**Comment by hcodes** [comment]
- add deps badge in README.md.

**Comment by dfilatov** [comment]
Let's don't update just for update. If we miss some particular functionality from new version of specific module let's create separate issue.
