### ISSUE TITLE
Доработать документ "Быстрый старт по BEMHTML"

### ISSUE THREAD

**Issue by VVE** [bem/bem-core#917]
Здравствуйте! По шагу 7:
1) создание файла desktop.blocks/hello/hello.js c содержанием из статьи, по-моему, не дает эффекта. Наверное, нужно что-то еще?
2) верно ли в статье написано про файл desktop.blocks/hello/hello.css, а не уже созданный файл desktop.blocks/hello/hello.styl ? Если создать такой css-файл, то к странице подключаются и он, и styl-файл.

**Comment by tadatuta** [comment]
1. Помимо `hello.js`, необходимо создать шаблон `hello.bemhtml`, в котором задать `block('hello').js()(true)` — про это написано чуть выше на 7 шаге.
   Если и шаблон и js присутствуют, а при клике на блок не появляется сообщение, что, видимо, где-то закралась ошибка. Напишите, пожалуйста, посмотрю внимательно.
2. Можно использовать созданный `styl`, а можно удалить его в пользу `css`. Текст статьи был написан до внедрения `Stylus`, поэтому данный момент никак не отражен в тексте. Поправим.

// cc @innabelaya

**Comment by VVE** [comment]
Большое спасибо!
1. работает.
2. ясно.

**Comment by tadatuta** [comment]
Написали новую документацию на bem-xjst: https://github.com/bem/bem-xjst/tree/master/docs/ru
