### ISSUE TITLE
bemconfig.json or bemconfig.js

### ISSUE THREAD

**Issue by belozer** [bem/bem-core#941]
Why not make the config file of the project in bem-core@v3?
This simple way for settings project, analog `generator-bem-stub`, but without rebase project.

Example:

``` json
{
    "tamplate" : "bh",
    "styles" : "styl",
    "levels" : [
        "destkop.blocks",
        "touch.blocks"
    ],
    "static" : true
}
```

``` js
{
    tamplate : "bh",
    styles : "styl",
    levels : [
        "destkop.blocks",
        "touch.blocks"
    ],
    static : true
}
```

Some people like bh, other bemhtml. But settings make file very hard work.
This is method allows make simple build settings.

**Comment by tadatuta** [comment]
We're kinda in progress of doing so for quite a long time. And as it turned out, that's not so easy thing to satisfy all the possible cases.

**Comment by Guria** [comment]
I was thought that bundles should  configure self in its own folder.

@belozyorcev you forgot a layers from library.

**Comment by belozer** [comment]
@tadatuta You can focus on the problems arising in the community.
@Guria this don't full config file, he is only example :)

**Comment by qfox** [comment]
I think this should be reviewed after bem/bem-components#1349 only.

**upd** Anyway, this issue about maker configurations and not related to `bem-core`.
