### ISSUE TITLE
Attribute escaping optimization

### ISSUE THREAD

**Issue by mishanga** [bem/bem-core#961]
У нас с незапамятных времен в базовых шаблонах BEMHTML функция attrEscape экранирует 4 символа: кавычку, амперсанд и треугольные скобки.
https://github.com/bem/bem-bl/blob/0.2/blocks-common/i-bem/__html/i-bem__html.bemhtml#L238
В bem-core так же: https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.bemhtml#L229
А вот в BT экранируются только кавычка и амперсанд: https://github.com/enb-make/enb-bt/blob/master/lib/bt.js#L802
Я покурил интернетики на эту тему, поэкспериментировал в браузерах и пришел к выводу, что эскейпить треугольные скобки действительно не нужно (это касается только атрибутов).
В BH уже есть фикс: https://github.com/bem/bh/pull/137/files

Если оторвать эскейпинг треугольных скобок, это немного уменьшит время шаблонизации.

**Comment by qfox** [comment]
:+1: кажется, да.

**Comment by aristov** [comment]
> уменьшит скорость шаблонизации

пывысит?

**Comment by mishanga** [comment]
@aristov хотел сказать "уменьшит время шаблонизации".
