### ISSUE TITLE
Feedback for "Быстрый старт по BEMHTML"

### ISSUE THREAD

**Issue by aimuzov** [bem/bem-core#964]
Шаг 5, походу не работает пример:

``` js
block('hello')(
    content()(function() {
        return (this.ctx.names || [this.ctx.name]).map(function(user) {
            return { elem: 'item', content: user };
        });
    }),
    elem('item')(
        content()(function() {
            return ['Hello, ', applyNext(), '!'];
        })
    )
);
```

На выходе вместо ожидаемого:

``` html
<div class="hello">
  <div class="hello__item">Hello, BEM!</div>
  <div class="hello__item">Hello, BEMJSON!</div>
  <div class="hello__item">Hello, BEMHTML!</div>
</div>
```

Получаем это:

``` html
<div class="hello">
  <div class="hello__item">Hello, !</div>
</div>
```

Если убрать первый аргумент из функции (content()...), то тогда выдает ожидаемый результат. Поясните, пожалуйста, как сохранить поддержку старого API о котором говорится в примере?

**Comment by veged** [comment]
можно уточнить, где именно и с какими версиями библиотек не работает пример?

попробовали в [repl](http://bem.github.io/bem-xjst/?bemhtml=block%28'hello'%29%28%0A%20%20%20%20content%28%29%28function%28%29%20%7B%0A%20%20%20%20%20%20%20%20return%20%28this.ctx.names%20%7C%7C%20%5Bthis.ctx.name%5D%29.map%28function%28user%29%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%7B%20elem%3A%20'item'%2C%20content%3A%20user%20%7D%3B%0A%20%20%20%20%20%20%20%20%7D%29%3B%0A%20%20%20%20%7D%29%2C%0A%20%20%20%20elem%28'item'%29%28%0A%20%20%20%20%20%20%20%20content%28%29%28function%28%29%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%5B'Hello%2C%20'%2C%20applyNext%28%29%2C%20'!'%5D%3B%0A%20%20%20%20%20%20%20%20%7D%29%0A%20%20%20%20%29%0A%29%3B&bemjson=%7B%20block%3A%20'hello'%2C%20names%3A%20%5B'BEM'%2C%20'BEMJSON'%2C%20'BEMHTML'%5D%20%7D%0A) — вроде работает

убедитесь, что вы подаёте на вход именно сокращённый BEMJSON:

``` js
{ block: 'hello', names: ['BEM', 'BEMJSON', 'BEMHTML'] }
```

а не полный:

``` js
{
    block: 'hello',
    content: [
        { elem: 'item', content: 'BEM' },
        { elem: 'item', content: 'BEMJSON' },
        { elem: 'item', content: 'BEMHTML' }
    ]
}
```
