### ISSUE TITLE
i-bem__dom: Think about getting rid of using jQuery's selectors methods

### ISSUE THREAD

**Issue by narqo** [bem/bem-core#965]
According to researches from Chrome DevTools Team and Wikipedia Tech guys, jQuery's selector methods (`jQuery#children()` specifically) can lead to unexpected performance penalties. 

As we use such methods internally in our `find*` methods, as well as `destruct` method, additional **performance investigations should be done**.

See ["DevTools: State Of The Union 2015" slides, starting from №54](https://speakerdeck.com/addyosmani/devtools-state-of-the-union-2015?slide=54) for reference.

Quote from the talk:

> [..] jQuery does a lot of magic around querySelectorAll. Use it on its own if possible.

**Comment by veged** [comment]
which performance investigations you suggest to do? on which synthetic pages?

**Comment by dfilatov** [comment]
Let's be honest — won't fix
