### ISSUE TITLE
querystring: Move to uri__querystring

### ISSUE THREAD

**Issue by veged** [bem/bem-core#967]
It's more natural hierarchy to have `uri` block and `uri__querystring` element.

**Comment by tadatuta** [comment]
@veged let's also think about getting rid of it at all in honour of https://github.com/bem/bem-history/tree/v2/common.blocks/uri as otherwise we'll get a conflict.

**Comment by dfilatov** [comment]
@tadatuta Since this is a major change in v3 so bem-history is supposed to consider that while migrating.
