### ISSUE TITLE
i-bem.bemhtml: decline support of nested mixes at all

### ISSUE THREAD

**Issue by aristov** [bem/bem-core#970]
See also https://github.com/bem/bh/issues/125
cc @mishanga @veged

**Comment by mishanga** [comment]
1) в О2 и Лего написаны парные шаблоны для всех блоков, а это значит, что указанная возможность не используется
2) не знаю ни одного человека и ни одного места в коде, который бы это реально использовал

Не вижу смысла нарушать консистентность.

**Comment by qfox** [comment]
> 2) не знаю ни одного человека и ни одного места в коде, который бы это реально использовал

с одной стороны, это правильно, но...

Консистентность это не «если 80% используют — значит она есть». Это «как в малом, так и в великом». Фрактальная структура, если хотите. Согласованность, логичность (не путать с бизнес логикой).

Когда одни правила применимы для CSS и JS, но не применимы для HTML — это неконсистенто.

Если ты не пользуешься теорией графов для расчета наиболее оптимального пути для покупки хлеба — это не значит, что теория графов не нужна. Но математическая полнота (с точки зрения совместимости между технологиями) нужна, иначе люди ожидают то, чего нет.

По https://github.com/bem/bh/issues/86 я отписывал.

Может быть сделать rethink по проблеме?

**Comment by tadatuta** [comment]
@zxqfox эту задачу и завели ради rethink, готового решения пока нет

**Comment by qfox** [comment]
@tadatuta Ну тут явно написано — decline ;-)

**Comment by tadatuta** [comment]
и лейбла question )

**Comment by dfilatov** [comment]
@veged: давайте будем честными :) Все дальнейшее обсуждение переносим в https://github.com/bem/bem-xjst
