### ISSUE TITLE
Feedback for "BEMHTML: описание шаблонизатора и его преимуществ"

### ISSUE THREAD

**Issue by kriku** [bem/bem-core#974]
https://ru.bem.info/technology/bemhtml/v2/rationale/#data-bind

не до конца понял, почему `knockout` так выделили..
и что значит тогда **data-bind**?
если **live-data-bind**  описан как _"отличается тем, что в шаблоне можно декларировать связь не со статическими, а изменяющимися данными"_, тогда наверно и `angular` стоит выделить также

**Comment by veged** [comment]
да, надо перенести Angular.js из примеров data-bind в примеры live-data-bind

**Comment by veged** [comment]
should be fine after https://github.com/bem/bem-info-libs/commit/d04b37c1e06b4a810995b06b98142bff9415d626 and https://github.com/bem-site/bem-md-renderer/pull/7
