### ISSUE TITLE
Use single quote instead of double in js params

### ISSUE THREAD

**Issue by sbmaxx** [bem/bem-core#980]
Это может немного уменьшить размер итогового `HTML`. В `BH` 4.0 @mishanga уже запили. Я попробовал на боевых проектах — 240 КБ превратилось в ~200 КБ.

Как побочный эффект — читать HTML становится приятней, глаз не спотыкается об `&quot;a: 'b'&quot;`

**Comment by mishanga** [comment]
А после gzip заметна разница?

**Comment by sbmaxx** [comment]
> А после gzip заметна разница?

пара КБ буквально

**Comment by narqo** [comment]
Same as #250 but for v2
