### ISSUE TITLE
i18n: add documentation

### ISSUE THREAD

**Issue by apsavin** [bem/bem-core#983]
It seems that it's missed.

**Comment by tadatuta** [comment]
@apsavin actually there's no `i18n` support yet but it's almost there ;)

**Comment by apsavin** [comment]
oh.
I just used it with bem-bl and I see that we have i-bem__i18n.
What is "almost"?) Could you estimate please?

**Comment by tadatuta** [comment]
@apsavin ~2 weeks till working state in `v3` branch then some time to backport it to `v2` (it should be fast), then some more time to make v2 release with i18n in it. hope will be there in a month +- 2 weeks.

**Comment by apsavin** [comment]
Thank you very much for such detailed answer.

**Comment by veged** [comment]
need documentation for #576
