### ISSUE TITLE
Rename .bemhtml files to .bemhtml.js

### ISSUE THREAD

**Issue by arikon** [bem/bem-core#984]
For that we will get:
- syntax highlighting on Github and in all the editors for free
- linters (jshint, jscs) will work with templates without additional configuration

Linked issue https://github.com/bem/bem-components/issues/1464

**Comment by qfox** [comment]
@arikon Somebody already doing it? Is it viable for v2 also?

**Comment by arikon** [comment]
@zxqfox I'm not sure about version branch. Let maintainers decide.

**Comment by sbmaxx** [comment]
:+1:

**Comment by veged** [comment]
:+1:

**Comment by tadatuta** [comment]
let's do it in `v3`?

cc @veged @narqo
