### ISSUE TITLE
bemhtml documentation: fix applyCtx description about assignment in args

### ISSUE THREAD

**Issue by vkz** [bem/bem-core#987]
`applyNext` is correct https://ru.bem.info/technology/bemhtml/v2/templating/#applynext (use `{assignObj}`).

`applyCtx` https://ru.bem.info/technology/bemhtml/v2/templating/#applyctx still uses raw assignment in arguments.

**Comment by tadatuta** [comment]
Fixed in https://github.com/bem/bem-core/pull/992
