### ISSUE TITLE
Make possible to use i-bem without jquery

### ISSUE THREAD

**Issue by qfox** [bem/bem-core#988]
It's easy to do with YM. We just need to replace jquery module with meta-block (that will load jquery or something other).

There are some other libraries which can be used instead of jQuery: https://tech.yandex.ru/jslibs/

We just need to ask user about several methods (that used inside `i-bem__dom`) and DOMEvents wrappers.

Refs:
- https://ru.bem.info/forum/issues/364/
- https://ru.bem.info/forum/issues/359/

**Comment by tadatuta** [comment]
...or just agree that anything else should still be called `jquery` and do nothing special then ;)

**Comment by qfox** [comment]
@tadatuta Well, why It's named `jquery` if it's not `jquery`? Bad idea imho.

**Comment by tadatuta** [comment]
@zxqfox as I've already said on forum, it's just fine for 99% of users and if we'll add one extra layer of abstraction for last 1% we'll get one more extra step for new comers. try to read it as "any module with interface of jquery" ;)

**Comment by qfox** [comment]
@tadatuta Let's rename it to `jquery-like` or to `any-module-with-interface-of-jquery` then.

**Comment by qfox** [comment]
@tadatuta Do you apply a PR if we're ready to make it?

**Comment by tadatuta** [comment]
@zxqfox you'd better try to convince @veged as a maintainer.
as for me as a user of `bem-core`, I'm just happy with current state of things ;)

**Comment by qfox** [comment]
@tadatuta Well, okay, but still it's a weak position when we can't switch between different modules providing the same functionality. It's a kind of oligopoly.

Let's say, what If I want another promise library? I should name it `vow`?

**Comment by pavelpower** [comment]
@zxqfox, @tadatuta  I'm ready to replace JQuery on just the interface. And give select users the ability a suitable implementation.

experience we already have in our projects.

Isn't it, @DenisChinin

**Comment by veged** [comment]
you always can mimic jQuery (just as @tadatuta says, with redefining of `jquery` module) — I can't see any needs to abstract it

**Comment by qfox** [comment]
@veged Inconsistency shit here. ;-(

**Comment by veged** [comment]
you just too pedant ;-)

**Comment by qfox** [comment]
Well, nope.

Simple case: I'm using something that mimic to jquery, then I want to use some library that want jquery => I'm writing my own jquery over other library.

Newcomers see this code and telling me that I'm an idiot that using BEM.

**Comment by veged** [comment]
if your library truly mimic jQuery it's enough for any other some library which want jQuery

**Comment by pavelpower** [comment]
@zxqfox  :+1:
