### ISSUE TITLE
Update jQuery to 1.11.3 and 2.1.4

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#999]

**Comment by qfox** [comment]
What if... Somebody can't use 2.x? ;-)

**Comment by tadatuta** [comment]
@zxqfox they should [keep calm](https://github.com/bem/bem-core/blob/v2/desktop.blocks/jquery/__config/jquery__config.js#L16) and carry on :)

**Comment by qfox** [comment]
Well, I hate that hardcode. You know. :smirk_cat:

**Comment by tadatuta** [comment]
https://github.com/bem/bem-core/pull/1073
